// Real-runtime check for verify/dotnet-marvin: Copyright (c) 2026 Thomas Dybdahl Ahle, MIT License
// (full text in marvin32_verify.c).
//
// Runs on the actual .NET runtime and prints, in this order:
//   1. the runtime version and this process's Marvin.DefaultSeed (read by reflection);
//   2. the seed protocol check: string.GetHashCode() == Marvin.ComputeHash32(UTF-16LE bytes, DefaultSeed)
//      for all four strings, and whether each pair collides in this process;
//   3. 64 known-answer vectors "V seed len data hash" from Marvin.ComputeHash32 at fixed seeds and messages
//      (generated by the splitmix64 stream below; marvin32_verify.c embeds the same table and regenerates
//      the inputs, so a mismatch there means the C transcription differs from the runtime);
//   4. the recorded witness seeds of both pairs through the real ComputeHash32;
//   5. both pairs under 2^k operating-system random 64-bit seeds (RandomNumberGenerator.Fill), split into
//      (p0, p1) exactly as String.GetHashCode splits DefaultSeed, with the collision count and rate.
// Usage: dotnet dotnet_check.dll [log2 N, default 24]
using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;

delegate int MarvinFn(ReadOnlySpan<byte> data, ulong seed);

static class DotnetCheck
{
    static ulong SplitMix(ref ulong s)
    {
        ulong z = (s += 0x9e3779b97f4a7c15UL);
        z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9UL;
        z = (z ^ (z >> 27)) * 0x94d049bb133111ebUL;
        return z ^ (z >> 31);
    }
    static byte[] Unhex(string h)
    {
        var b = new byte[h.Length / 2];
        for (int i = 0; i < b.Length; i++) b[i] = Convert.ToByte(h.Substring(2 * i, 2), 16);
        return b;
    }
    static string Hex(byte[] d) => d.Length == 0 ? "-" : Convert.ToHexString(d).ToLowerInvariant();

    static int Main(string[] args)
    {
        int lg = 24;
        if (args.Length > 1 || (args.Length == 1 && (!int.TryParse(args[0], out lg) || lg < 0 || lg > 40)))
        {
            Console.Error.WriteLine("usage: dotnet dotnet_check.dll [log2 N (0..40), default 24]");
            return 2;
        }
        long n = 1L << lg;

        Type marvin = typeof(string).Assembly.GetType("System.Marvin", true)!;
        ulong defaultSeed = (ulong)marvin.GetProperty("DefaultSeed", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)!.GetValue(null)!;
        var fn = (MarvinFn)Delegate.CreateDelegate(typeof(MarvinFn), marvin.GetMethod("ComputeHash32",
            BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, null,
            new[] { typeof(ReadOnlySpan<byte>), typeof(ulong) }, null)!);

        Console.WriteLine($"runtime: {RuntimeInformation.FrameworkDescription} {RuntimeInformation.ProcessArchitecture} {RuntimeInformation.OSDescription}");
        Console.WriteLine($"this process: Marvin.DefaultSeed = {defaultSeed:x16} (64 random bits drawn once per process; p0 = low 32, p1 = high 32)");

        string[] names = { "A", "B" };
        string[][] pairs = {
            new[] { "610061002f546d1662006200", "610061802f9579a262fc6100" },
            new[] { "6100610061006100", "7211721150ef4fef" },
        };
        ulong[] witness = { 0x9bcb44c8bff5b6f1UL, 0xc4cec22cffed4464UL };
        uint[] witnessHash = { 0x7eec677cu, 0x22e699d5u };

        int bad = 0;
        for (int p = 0; p < 2; p++)
        {
            byte[] b1 = Unhex(pairs[p][0]), b2 = Unhex(pairs[p][1]);
            string s1 = Encoding.Unicode.GetString(b1), s2 = Encoding.Unicode.GetString(b2);
            if (!Encoding.Unicode.GetBytes(s1).AsSpan().SequenceEqual(b1) || !Encoding.Unicode.GetBytes(s2).AsSpan().SequenceEqual(b2))
            { Console.WriteLine($"pair {names[p]}: bytes are not a UTF-16LE string"); return 1; }
            int h1 = s1.GetHashCode(), h2 = s2.GetHashCode();
            int r1 = fn(b1, defaultSeed), r2 = fn(b2, defaultSeed);
            bool ok = r1 == h1 && r2 == h2 && string.GetHashCode(s1.AsSpan()) == h1 && string.GetHashCode(s2.AsSpan()) == h2;
            if (!ok) bad++;
            Console.WriteLine($"pair {names[p]}: string.GetHashCode(M) = {(uint)h1:x8}, string.GetHashCode(M') = {(uint)h2:x8} " +
                              $"({(h1 == h2 ? "COLLIDE" : "differ")} under this process's seed); " +
                              $"equals Marvin.ComputeHash32(UTF-16LE bytes, DefaultSeed): {(ok ? "PASS" : "FAIL")}");
        }
        if (bad != 0) return 1;

        Console.WriteLine("vectors: Marvin.ComputeHash32(data, seed) at 4 splitmix64 seeds x lengths 0..15 (stream state 4d617276696e3332)");
        ulong st = 0x4d617276696e3332UL;
        for (int k = 0; k < 4; k++)
        {
            ulong seed = SplitMix(ref st);
            for (int len = 0; len <= 15; len++)
            {
                var data = new byte[len];
                for (int i = 0; i < len; i++) data[i] = (byte)SplitMix(ref st);
                Console.WriteLine($"V {seed:x16} {len} {Hex(data)} {(uint)fn(data, seed):x8}");
            }
        }

        for (int p = 0; p < 2; p++)
        {
            byte[] b1 = Unhex(pairs[p][0]), b2 = Unhex(pairs[p][1]);
            uint h1 = (uint)fn(b1, witness[p]), h2 = (uint)fn(b2, witness[p]);
            bool ok = h1 == h2 && h1 == witnessHash[p];
            if (!ok) bad++;
            Console.WriteLine($"recorded seed {witness[p]:x16} pair {names[p]}: ComputeHash32(M) = {h1:x8}, ComputeHash32(M') = {h2:x8}, expected {witnessHash[p]:x8}: {(ok ? "PASS" : "FAIL")}");
        }
        if (bad != 0) return 1;

        var buf = new byte[8 << 20];
        for (int p = 0; p < 2; p++)
        {
            byte[] b1 = Unhex(pairs[p][0]), b2 = Unhex(pairs[p][1]);
            long coll = 0; ulong first = 0; uint firstHash = 0;
            for (long done = 0; done < n;)
            {
                int m = (int)Math.Min(buf.Length / 8, n - done);
                RandomNumberGenerator.Fill(buf.AsSpan(0, m * 8));
                for (int i = 0; i < m; i++)
                {
                    ulong s = BitConverter.ToUInt64(buf, 8 * i);
                    int x = fn(b1, s);
                    if (x == fn(b2, s)) { if (coll == 0) { first = s; firstHash = (uint)x; } coll++; }
                }
                done += m;
            }
            double rate = (double)coll / n;
            Console.Write($"pair {names[p]}: OS random seeds: collisions = {coll} / {n}; rate = {rate:G12}");
            if (coll > 0) Console.WriteLine($"; log2(rate) = {Math.Log2(rate):F6}; first colliding seed {first:x16}: H(M)=H(M')={firstHash:x8}");
            else Console.WriteLine("; log2(rate) = -inf (zero hits)");
        }
        return 0;
    }
}
