/*
 * DO NOT EDIT THIS FILE
 *
 * It is generated by CMake during build configuration.
 * See <scratch>/codex/m2-rerun/smhasher3/platform/functions.cmake
 * for documentation on how and why this is generated.
 */
/*
 * SMHasher3
 * Copyright (C) 2021-2022  Frank J. T. Wojcik
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <https://www.gnu.org/licenses/>.
 *
 * This file incorporates work covered by the following copyright and
 * permission notice:
 *
 *     Copyright (c) 2011-2013 Austin Appleby
 *     Copyright (c) 2016      Leonid Yuriev
 *     Copyright (c) 2016      Mahmoud Al-Qudsi
 *     Copyright (c) 2016-2021 Reini Urban
 *     Copyright (c) 2019      Yann Collet
 *
 *     Permission is hereby granted, free of charge, to any person
 *     obtaining a copy of this software and associated documentation
 *     files (the "Software"), to deal in the Software without
 *     restriction, including without limitation the rights to use,
 *     copy, modify, merge, publish, distribute, sublicense, and/or
 *     sell copies of the Software, and to permit persons to whom the
 *     Software is furnished to do so, subject to the following
 *     conditions:
 *
 *     The above copyright notice and this permission notice shall be
 *     included in all copies or substantial portions of the Software.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *     EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 *     OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *     NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 *     HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 *     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *     FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 *     OTHER DEALINGS IN THE SOFTWARE.
 */
//-----------------------------------------------------------------------------
// Platform-specific cycle count (or estimate) timing function
// For ARM systems, there is seemingly no way to generically get actual CPU
// cycle counts as a regular user. There are OS-specific ways. There are
// HW-specific ways. There are ways that require some sort of elevated
// access (root privs or wheel group membership). But nothing reliably
// usable by SMHasher3.This also seems true of PPC and some other platforms.
//
// To emulate such a measuring tool, this will estimate the number of
// cycles (instructions, basically) per nanosecond, and then measure
// nanoseconds and convert to cycles.
//
// See https://gitlab.com/fwojcik/smhasher3/-/issues/87 for more. This
// approach is by James Price and was taken from:
// https://uob-hpc.github.io/2017/11/22/arm-clock-freq.html,
// except that no opcode is used in the asm statement; it is only used to
// prevent the compiler from optimizing the additions away. This approach
// should work on any platform, assuming the compiler accepts gcc-style asm
// statements.

extern double cycle_timer_mult;

static NEVER_INLINE void cycle_timer_init() {
    const uint64_t NUM_INSTR = UINT64_C(1000000000);
    uint64_t start, end, count = 0;

    start = monotonic_clock();

    while (count < NUM_INSTR) {
#define INST0 asm volatile ("":[i] "+r" (count)::"cc"); count++;
#define INST1 INST0 INST0 INST0 INST0   INST0 INST0 INST0 INST0 \
              INST0 INST0 INST0 INST0   INST0 INST0 INST0 INST0
#define INST2 INST1 INST1 INST1 INST1   INST1 INST1 INST1 INST1 \
              INST1 INST1 INST1 INST1   INST1 INST1 INST1 INST1
#define INST3 INST2 INST2 INST2 INST2   INST2 INST2 INST2 INST2 \
              INST2 INST2 INST2 INST2   INST2 INST2 INST2 INST2

        INST3;
    }

    end = monotonic_clock();

    // Units are cycles / nanosecond
    cycle_timer_mult = (double)count / (double)(end - start);
#if 0
    printf("Instructions executed = %ld\n", count);
    printf("Runtime (ns)          = %ld\n", end - start);
    printf("Estimated frequency   = %.2lf GHz\n", cycle_timer_mult);
#endif
}

static FORCE_INLINE uint64_t cycle_timer_start() {
    return monotonic_clock() * cycle_timer_mult;
}

static FORCE_INLINE uint64_t cycle_timer_end() {
    return monotonic_clock() * cycle_timer_mult;
}
