cmake_minimum_required(VERSION 3.16)
project(swiss_check CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(ABSL_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(ABSL_PROPAGATE_CXX_STD ON CACHE BOOL "" FORCE)
add_subdirectory(abseil-cpp EXCLUDE_FROM_ALL)
add_executable(swiss_check swiss_check.cc)
target_link_libraries(swiss_check absl::flat_hash_set absl::flat_hash_map absl::hash absl::raw_hash_set)
