[package]
name = "paircheck"
version = "0.1.0"
edition = "2021"
[dependencies]
m03 = { package = "museair", path = "../wt/v0.3" }
m04 = { package = "museair", path = "../wt/v0.4" }
m1  = { package = "museair", path = "../wt/v1" }
m2  = { package = "museair", path = "../wt/crate-0.6.0" }
[profile.release]
opt-level = 3
