/* rapidhash-v3: adapted for this package from paper_rows/rapid_v3_port.h (validated verbatim SMHasher3 bodies) and collision_driver.cpp.
 * The supplied independent verifier/driver is credited here;
 * adaptations: standalone C11 driver, explicit LE loads, asserted
 * SMHasher3 values and witnesses, single-thread deterministic sampling. */
// Generated by prepare_rapid.py; hash body copied verbatim from ref/rapidhash.cpp.
/*
 * rapidhash - Very fast, high quality, platform independant hashing algorithm.
 * Copyright (C) 2025 Nicolas De Carli
 * Copyright (C) 2025 Frank J. T. Wojcik
 *
 * Based on 'wyhash', by Wang Yi <godspeed_china@yeah.net>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * You can contact the author at:
 *   - rapidhash source repository: https://github.com/Nicoshev/rapidhash
 */
#include <stdint.h>
#include <stddef.h>
#include <string.h>

static uint64_t load_le(const uint8_t *p, unsigned n) {
    uint64_t x=0; for(unsigned i=0;i<n;i++) x|=(uint64_t)p[i]<<(8*i); return x;
}
#define likely(x) (x)
#define isProtected 0
#define unrolled 1
/*
 *  Read functions.
 */
static inline uint64_t rapid_read64( const uint8_t * p ) {
    return load_le(p,8);
}

static inline uint64_t rapid_read32( const uint8_t * p ) {
    return load_le(p,4);
}

/*
 *  64*64 -> 128bit multiply function.
 *
 *  @param A  Address of 64-bit number.
 *  @param B  Address of 64-bit number.
 *
 *  Calculates 128-bit C = A * B.
 *
 *  When isProtected is false:
 *  Overwritres A contents with C's low 64 bits.
 *  Overwritres B contents with C's high 64 bits.
 *
 *  When isProtected is true:
 *  Xors and overwrites A contents with C's low 64 bits.
 *  Xors and overwrites B contents with C's high 64 bits.
 */
static inline void rapid_mum( uint64_t * A, uint64_t * B ) {
    uint64_t rlo, rhi;

    __uint128_t product=(__uint128_t)*A * *B; rlo=(uint64_t)product; rhi=(uint64_t)(product>>64);
    if (isProtected) {
        *A ^= rlo; *B ^= rhi;
    } else {
        *A  = rlo; *B  = rhi;
    }
}

/*
 *  Multiply and xor mix function.
 *
 *  @param A  64-bit number.
 *  @param B  64-bit number.
 *
 *  Calculates 128-bit C = A * B.
 *  Returns 64-bit xor between high and low 64 bits of C.
 */
static inline uint64_t rapid_mix( uint64_t A, uint64_t B ) {
    rapid_mum(&A, &B);
    return A ^ B;
}

/*
 *  Default secret parameters.
 */
static const uint64_t rapid_secret[8] = {
    UINT64_C(0x2d358dccaa6c78a5), UINT64_C(0x8bb84b93962eacc9),
    UINT64_C(0x4b33a62ed433d4a3), UINT64_C(0x4d5a2da51de1aa47),
    UINT64_C(0xa0761d6478bd642f), UINT64_C(0xe7037ed1a0b428db),
    UINT64_C(0x90ed1765281c388c), UINT64_C(0xaaaaaaaaaaaaaaaa),
};

/*
 *  rapidhash main function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *  @param secrets Array of 8 64-bit secrets used to alter hash result predictably.
 *
 *  Returns a 64-bit hash.
 */
static inline uint64_t rapidhash( const void * key, size_t len, uint64_t seed, const uint64_t * secrets ) {
    const uint8_t * p = (const uint8_t *)key;
    size_t          i = len;
    uint64_t        a, b;

    seed ^= rapid_mix(seed ^ secrets[2], secrets[1]);

    if (likely(len <= 16)) {
        if (len >= 4) {
            seed ^= len;
            if (len >= 8) {
                const uint8_t * plast = p + len - 8;
                a = rapid_read64(p    );
                b = rapid_read64(plast);
            } else {
                const uint8_t * plast = p + len - 4;
                a = rapid_read32(p    );
                b = rapid_read32(plast);
            }
        } else if (likely(len > 0)) {
            a = (((uint64_t)p[0]) << 45) | p[len - 1];
            b = p[len >> 1];
        } else {
            a = b = 0;
        }
    } else {
        if (len > 112) {
            uint64_t see1 = seed, see2 = seed;
            uint64_t see3 = seed, see4 = seed;
            uint64_t see5 = seed, see6 = seed;
            if (unrolled) {
                while (i > 224) {
                    seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                            rapid_read64(p +   8) ^ seed);
                    see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                            rapid_read64(p +  24) ^ see1);
                    see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                            rapid_read64(p +  40) ^ see2);
                    see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                            rapid_read64(p +  56) ^ see3);
                    see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                            rapid_read64(p +  72) ^ see4);
                    see5 = rapid_mix(rapid_read64(p +  80) ^ secrets[5],
                            rapid_read64(p +  88) ^ see5);
                    see6 = rapid_mix(rapid_read64(p +  96) ^ secrets[6],
                            rapid_read64(p + 104) ^ see6);
                    seed = rapid_mix(rapid_read64(p + 112) ^ secrets[0],
                            rapid_read64(p + 120) ^ seed);
                    see1 = rapid_mix(rapid_read64(p + 128) ^ secrets[1],
                            rapid_read64(p + 136) ^ see1);
                    see2 = rapid_mix(rapid_read64(p + 144) ^ secrets[2],
                            rapid_read64(p + 152) ^ see2);
                    see3 = rapid_mix(rapid_read64(p + 160) ^ secrets[3],
                            rapid_read64(p + 168) ^ see3);
                    see4 = rapid_mix(rapid_read64(p + 176) ^ secrets[4],
                            rapid_read64(p + 184) ^ see4);
                    see5 = rapid_mix(rapid_read64(p + 192) ^ secrets[5],
                            rapid_read64(p + 200) ^ see5);
                    see6 = rapid_mix(rapid_read64(p + 208) ^ secrets[6],
                            rapid_read64(p + 216) ^ see6);
                    p   += 224; i -= 224;
                }
                if (i > 112) {
                    seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                            rapid_read64(p +   8) ^ seed);
                    see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                            rapid_read64(p +  24) ^ see1);
                    see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                            rapid_read64(p +  40) ^ see2);
                    see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                            rapid_read64(p +  56) ^ see3);
                    see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                            rapid_read64(p +  72) ^ see4);
                    see5 = rapid_mix(rapid_read64(p +  80) ^ secrets[5],
                            rapid_read64(p +  88) ^ see5);
                    see6 = rapid_mix(rapid_read64(p +  96) ^ secrets[6],
                            rapid_read64(p + 104) ^ see6);
                    p   += 112; i -= 112;
                }
            } else {
                do {
                    seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                            rapid_read64(p +   8) ^ seed);
                    see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                            rapid_read64(p +  24) ^ see1);
                    see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                            rapid_read64(p +  40) ^ see2);
                    see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                            rapid_read64(p +  56) ^ see3);
                    see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                            rapid_read64(p +  72) ^ see4);
                    see5 = rapid_mix(rapid_read64(p +  80) ^ secrets[5],
                            rapid_read64(p +  88) ^ see5);
                    see6 = rapid_mix(rapid_read64(p +  96) ^ secrets[6],
                            rapid_read64(p + 104) ^ see6);
                    p   += 112; i -= 112;
                } while (i > 112);
            }
            seed ^= see1;
            see2 ^= see3;
            see4 ^= see5;
            seed ^= see6;
            see2 ^= see4;
            seed ^= see2;
        }
        if (i > 16) {
            seed = rapid_mix(rapid_read64(p) ^ secrets[2],
                    rapid_read64(p + 8) ^ seed);
            if (i > 32) {
                seed = rapid_mix(rapid_read64(p + 16) ^ secrets[2],
                        rapid_read64(p + 24) ^ seed);
                if (i > 48) {
                    seed = rapid_mix(rapid_read64(p + 32) ^ secrets[1],
                            rapid_read64(p + 40) ^ seed);
                    if (i > 64) {
                        seed = rapid_mix(rapid_read64(p + 48) ^ secrets[1],
                                rapid_read64(p + 56) ^ seed);
                        if (i > 80) {
                            seed = rapid_mix(rapid_read64(p + 64) ^ secrets[2],
                                    rapid_read64(p + 72) ^ seed);
                            if (i > 96) {
                                seed = rapid_mix(rapid_read64(p + 80) ^ secrets[1],
                                        rapid_read64(p + 88) ^ seed);
                            }
                        }
                    }
                }
            }
        }
        a = rapid_read64(p + i - 16) ^ i;
        b = rapid_read64(p + i -  8);
    }
    a ^= secrets[1];
    b ^= seed;
    rapid_mum(&a, &b);
    return rapid_mix(a ^ secrets[7], b ^ secrets[1] ^ i);
}

/*
 *  rapidhashMicro main function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *  @param secrets Array of 8 64-bit secrets used to alter hash result predictably.
 *                 Note that secrets[5] and secrets[6] are unused here.
 *
 *  Returns a 64-bit hash.
 */
static inline uint64_t rapidhashMicro( const void * key, size_t len, uint64_t seed, const uint64_t * secrets ) {
    const uint8_t * p = (const uint8_t *)key;
    size_t          i = len;
    uint64_t        a, b;

    seed ^= rapid_mix(seed ^ secrets[2], secrets[1]);

    if (likely(len <= 16)) {
        if (len >= 4) {
            seed ^= len;
            if (len >= 8) {
                const uint8_t * plast = p + len - 8;
                a = rapid_read64(p    );
                b = rapid_read64(plast);
            } else {
                const uint8_t * plast = p + len - 4;
                a = rapid_read32(p    );
                b = rapid_read32(plast);
            }
        } else if (likely(len > 0)) {
            a = (((uint64_t)p[0]) << 45) | p[len - 1];
            b = p[len >> 1];
        } else {
            a = b = 0;
        }
    } else {
        if (len > 80) {
            uint64_t see1 = seed, see2 = seed;
            uint64_t see3 = seed, see4 = seed;
            do {
                seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                        rapid_read64(p +   8) ^ seed);
                see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                        rapid_read64(p +  24) ^ see1);
                see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                        rapid_read64(p +  40) ^ see2);
                see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                        rapid_read64(p +  56) ^ see3);
                see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                        rapid_read64(p +  72) ^ see4);
                p   += 80; i -= 80;
            } while (i > 80);
            seed ^= see1;
            see2 ^= see3;
            seed ^= see4;
            seed ^= see2;
        }
        if (i > 16) {
            seed = rapid_mix(rapid_read64(p) ^ secrets[2],
                    rapid_read64(p + 8) ^ seed);
            if (i > 32) {
                seed = rapid_mix(rapid_read64(p + 16) ^ secrets[2],
                        rapid_read64(p + 24) ^ seed);
                if (i > 48) {
                    seed = rapid_mix(rapid_read64(p + 32) ^ secrets[1],
                            rapid_read64(p + 40) ^ seed);
                    if (i > 64) {
                        seed = rapid_mix(rapid_read64(p + 48) ^ secrets[1],
                                rapid_read64(p + 56) ^ seed);
                    }
                }
            }
        }
        a = rapid_read64(p + i - 16) ^ i;
        b = rapid_read64(p + i -  8);
    }
    a ^= secrets[1];
    b ^= seed;
    rapid_mum(&a, &b);
    return rapid_mix(a ^ secrets[7], b ^ secrets[1] ^ i);
}

/*
 *  rapidhashNano main function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *  @param secrets Array of 8 64-bit secrets used to alter hash result predictably.
 *                 Note that secrets[3] through secrets[6] are unused here.
 *
 *  Returns a 64-bit hash.
 */
static inline uint64_t rapidhashNano( const void * key, size_t len, uint64_t seed, const uint64_t * secrets ) {
    const uint8_t * p = (const uint8_t *)key;
    size_t          i = len;
    uint64_t        a, b;

    seed ^= rapid_mix(seed ^ secrets[2], secrets[1]);

    if (likely(len <= 16)) {
        if (len >= 4) {
            seed ^= len;
            if (len >= 8) {
                const uint8_t * plast = p + len - 8;
                a = rapid_read64(p    );
                b = rapid_read64(plast);
            } else {
                const uint8_t * plast = p + len - 4;
                a = rapid_read32(p    );
                b = rapid_read32(plast);
            }
        } else if (likely(len > 0)) {
            a = (((uint64_t)p[0]) << 45) | p[len - 1];
            b = p[len >> 1];
        } else {
            a = b = 0;
        }
    } else {
        if (len > 48) {
            uint64_t see1 = seed, see2 = seed;
            do {
                seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                        rapid_read64(p +   8) ^ seed);
                see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                        rapid_read64(p +  24) ^ see1);
                see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                        rapid_read64(p +  40) ^ see2);
                p   += 48; i -= 48;
            } while (i > 48);
            seed ^= see1;
            seed ^= see2;
        }
        if (i > 16) {
            seed = rapid_mix(rapid_read64(p) ^ secrets[2],
                    rapid_read64(p + 8) ^ seed);
            if (i > 32) {
                seed = rapid_mix(rapid_read64(p + 16) ^ secrets[2],
                        rapid_read64(p + 24) ^ seed);
            }
        }
        a = rapid_read64(p + i - 16) ^ i;
        b = rapid_read64(p + i -  8);
    }
    a ^= secrets[1];
    b ^= seed;
    rapid_mum(&a, &b);
    return rapid_mix(a ^ secrets[7], b ^ secrets[1] ^ i);
}

//-----------------------------------------------------------------------------

/* Reproduction driver: Copyright (c) 2026 Thomas Dybdahl Ahle, MIT.
 * The implementation's separate attribution/license is retained above.
 * One process, one thread; no dependencies outside this file. */
