import ProvenHashes.Carryless

noncomputable section
namespace ProvenHashes.ChainHash
open Polynomial
set_option maxRecDepth 4096

/-- The degree of an irreducible binary polynomial is the order of Frobenius
on the field generated by its root. -/
theorem irreducible_dvd_frobenius_iff (g : BitsPolynomial) (hg : Irreducible g) (n : ℕ) :
    g ∣ X ^ (2 ^ n) - X ↔ g.natDegree ∣ n := by
  letI : Fact (Irreducible g) := ⟨hg⟩
  letI : Fintype (AdjoinRoot g) := Fintype.ofEquiv (Fin g.natDegree → ZMod 2)
    (AdjoinRoot.powerBasisAux hg.ne_zero).equivFun.symm.toEquiv
  let f := FiniteField.frobeniusAlgHom (ZMod 2) (AdjoinRoot g)
  have horder : orderOf f = g.natDegree := by
    rw [FiniteField.orderOf_frobeniusAlgHom]
    exact (AdjoinRoot.powerBasis hg.ne_zero).finrank
  have heval : (f ^ n) (AdjoinRoot.root g) = AdjoinRoot.root g ^ (2 ^ n) := by
    simp only [AlgHom.coe_pow, f, FiniteField.coe_frobeniusAlgHom, pow_iterate, ZMod.card]
  rw [← horder, orderOf_dvd_iff_pow_eq_one]
  constructor
  · intro hd
    apply AdjoinRoot.algHom_ext
    rw [heval, AlgHom.one_apply]
    have hzero := (AdjoinRoot.mk_eq_zero (f := g)).mpr hd
    simpa only [map_sub, map_pow, AdjoinRoot.mk_X, sub_eq_zero] using hzero
  · intro hf
    apply (AdjoinRoot.mk_eq_zero (f := g)).mp
    simp only [map_sub, map_pow, AdjoinRoot.mk_X, sub_eq_zero]
    rw [← heval, hf, AlgHom.one_apply]

/-- Rabin's criterion specialized to degree 128 = 2^7. Only the halfway
Frobenius gcd is needed because 2 is the only prime divisor of 128. -/
theorem binary_rabin128 (p : BitsPolynomial) (hp : p.Monic) (hdeg : p.natDegree = 128)
    (h128 : p ∣ X ^ (2 ^ 128) - X) (h64 : IsCoprime p (X ^ (2 ^ 64) - X)) :
    Irreducible p := by
  have hunit : ¬ IsUnit p := not_isUnit_of_natDegree_pos p (by omega)
  obtain ⟨g, hgmon, hg, hgp⟩ := Polynomial.exists_monic_irreducible_factor p hunit
  have hd : g.natDegree ∣ 128 := (irreducible_dvd_frobenius_iff g hg 128).mp (hgp.trans h128)
  have hd' : g.natDegree ∣ 2 ^ 7 := by norm_num at hd ⊢; exact hd
  obtain ⟨k, hk, hgdeg⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp hd'
  have hk6 : k = 7 := by
    by_contra hk6
    have hk5 : k ≤ 6 := by omega
    have hd64 : g.natDegree ∣ 64 := by
      rw [hgdeg]
      exact (pow_dvd_pow 2 hk5 : 2 ^ k ∣ 2 ^ 6)
    exact hg.not_isUnit (h64.isUnit_of_dvd' hgp
      ((irreducible_dvd_frobenius_iff g hg 64).mpr hd64))
  have hgeq : p = g := Polynomial.eq_of_monic_of_dvd_of_natDegree_le hgmon hp hgp (by
    rw [hdeg, hgdeg, hk6]; norm_num)
  exact hgeq.symm ▸ hg

end ProvenHashes.ChainHash
