/* Single-file program generated from: SMHasher3 platform header + include/hashlib/Mathmult.h,
 * SMHasher3 hashes/cityhash.cpp (verbatim, #include lines removed), and the key-free driver below. */
/* === SMHasher3 platform/Platform.h (generated form, clock+thread parts removed) === */
/*
 * DO NOT EDIT THIS FILE
 *
 * It is generated by CMake during build configuration.
 * See <smhasher3>/platform/functions.cmake
 * for documentation on how and why this is generated.
 */
/*
 * SMHasher3
 * Copyright (C) 2021-2022  Frank J. T. Wojcik
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <https://www.gnu.org/licenses/>.
 */
#include <cstdio>    // Allow printf() from anywhere
#include <cstring>   // For memcpy

//-----------------------------------------------------------------------------
// Fixed-width integers (required before all else)
#include <cstdint>
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
typedef unsigned __int128 uint128_t;
typedef          __int128  int128_t;
#pragma GCC diagnostic pop
#define HAVE_INT128
typedef uint64_t  seed_t; 
#define __STDC_FORMAT_MACROS 1 // Some older gcc installations need this
#include <cinttypes>

//-----------------------------------------------------------------------------
// MSVC-specific things (if required)


//-----------------------------------------------------------------------------
// Declarations for Platform.cpp


//-----------------------------------------------------------------------------
// Compiler-specific functions and macros

// Compiler branching hints
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#define expectp(x,p) __builtin_expect_with_probability(!!(x), 1, (p))
#define unpredictable(x) __builtin_unpredictable(x)

// Compiler behavioral bounds hints
#define assume(x) __builtin_assume(x)
#define unreachable() __builtin_unreachable()

// Compiler/CPU data prefetching
#define prefetch(ptr) __builtin_prefetch(ptr)

// Function inlining control
#define FORCE_INLINE __attribute__((__always_inline__)) inline
#define NEVER_INLINE __attribute__((__noinline__))

// Variable aliasing
#define MAY_ALIAS __attribute__((__may_alias__))

// C "restrict" keyword replacement
#define RESTRICT __restrict

// Integer rotation
// CAUTION: These are deliberately unsafe!
// They assume the rotation value is not 0 or >= {32,64}.
// If an invalid rotation amount is given, the result is undefined behavior.
static inline uint32_t _rotl32(uint32_t v, uint8_t n) {
    return (v << n) | (v >> ((-n) & 31));
}
static inline uint32_t _rotr32(uint32_t v, uint8_t n) {
    return (v >> n) | (v << ((-n) & 31));
}
#define ROTL32(v, n) _rotl32(v, n)
#define ROTR32(v, n) _rotr32(v, n)
static inline uint64_t _rotl64(uint64_t v, uint8_t n) {
    return (v << n) | (v >> ((-n) & 63));
}
static inline uint64_t _rotr64(uint64_t v, uint8_t n) {
    return (v >> n) | (v << ((-n) & 63));
}
#define ROTL64(v, n) _rotl64(v, n)
#define ROTR64(v, n) _rotr64(v, n)

// Population count (popcnt/popcount)
#define popcount4(x) __builtin_popcount(x)
#define popcount8(x) __builtin_popcountll(x)

// Leading zero-bit count (ffs/clz)
// CAUTION: Assumes x is not 0!
#define clz4(x) __builtin_clz(x)
#define clz8(x) __builtin_clzll(x)

// Integer byteswapping (endianness conversion)
// You can use the bit-specific ones directly, but the more generic
// versions below are preferred.
#define BSWAP16(x) __builtin_bswap16(x)
#define BSWAP32(x) __builtin_bswap32(x)
#define BSWAP64(x) __builtin_bswap64(x)

//-----------------------------------------------------------------------------
// Generic wrappers for BSWAP*()
template < typename T >
static FORCE_INLINE T BSWAP(T value) {
    switch(sizeof(T)) {
    case 2: value = BSWAP16((uint16_t)value); break;
    case 4: value = BSWAP32((uint32_t)value); break;
    case 8: value = BSWAP64((uint64_t)value); break;
    default: break;
    }
    return value;
}

template < typename T >
static FORCE_INLINE T COND_BSWAP(T value, bool doit) {
    if (!doit || (sizeof(T) < 2)) { return value; }
    return BSWAP(value);
}

//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// User-configurable implementations

// Endianness detection
static FORCE_INLINE bool isLE(void) {
const uint32_t   value = 0xb000000e;
const void *      addr = static_cast<const void *>(&value);
const uint8_t *   lsb  = static_cast<const uint8_t *>(addr);
return ((*lsb) == 0x0e);
}
static FORCE_INLINE bool isBE(void) {
const uint32_t   value = 0xb000000e;
const void *      addr = static_cast<const void *>(&value);
const uint8_t *   lsb  = static_cast<const uint8_t *>(addr);
return ((*lsb) == 0xb0);
}



//-----------------------------------------------------------------------------
// Routines for turning bytes in memory into integers. These move data
// in alignment-safe ways, with optional byte swapping.
//
// memcpy() is the only known way of safely moving data this way;
// "safe" meaning "defined C++ behavior" AND "working regardless of
// alignment". Every memcpy() call here has a fixed size, and modern
// compilers tend to inline these into alignment-safe data moves/loads
// that are best for the platform being compiled for. Earlier
// compilers did not always do this very well, at least on non-x86
// platforms.
//
// If someone ever wanted to allow hashes to use undefined-behavior
// for faster access, this is where different access methods could be
// introduced, such as reading through a union or just doing direct
// memory access by pointer type conversion. Both of those are
// undefined behavior (UB), though! Beware of nasal demons!
//
// It's also plausible to introduce different versions of these which
// handle known-to-be-aligned accesses in a different way, perhaps
// through another template parameter.

template < bool bswap >
static FORCE_INLINE uint64_t GET_U64(const uint8_t * b, const uint32_t i) {
    uint64_t n;
    memcpy(&n, &b[i], 8);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE uint32_t GET_U32(const uint8_t * b, const uint32_t i) {
    uint32_t n;
    memcpy(&n, &b[i], 4);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE uint16_t GET_U16(const uint8_t * b, const uint32_t i) {
    uint16_t n;
    memcpy(&n, &b[i], 2);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE void PUT_U16(uint16_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 2);
}

template < bool bswap >
static FORCE_INLINE void PUT_U32(uint32_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 4);
}

template < bool bswap >
static FORCE_INLINE void PUT_U64(uint64_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 8);
}

//-----------------------------------------------------------------------------
// Generic vector support
#define VECTOR_SIZE(SZ)  __attribute__ ((vector_size (SZ)))
#define HAVE_GENERIC_VECTOR


//-----------------------------------------------------------------------------
// VLA helper
//
// Allocates on heap when VLA is not available

#if defined(__STDC_NO_VLA__) || defined(_MSC_VER) && !defined(__clang__)
    #include <vector>
    #define VLA_ALLOC(type, name, count) std::vector<type> name(count)
#else
    #define VLA_ALLOC(type, name, count)  \
 _Pragma("GCC diagnostic push");          \
 _Pragma("GCC diagnostic ignored \"-Wvla\""); \
 _Pragma("clang diagnostic ignored \"-Wvla-extension\""); \
 type name[count];                            \
 _Pragma("GCC diagnostic pop");
#endif

//-----------------------------------------------------------------------------
// Debugging helpers
//
// Really wish these could be moved into the CMake generation-time
// detection, but I can't find a reliable way of checking if "-DDEBUG"
// will be passed to the compiler.

#if defined(DEBUG)
  #include <cassert>

  #undef assume
  #define assume(x) assert(x)

  #undef unreachable
  #define unreachable() assert(0)

  #define verify(x) assert(x)
#else
  static void warn_if(bool x, const char * s, const char * fn, uint64_t ln) {
      if (!x) {
          printf("Statement %s is not true: %s:%" PRId64 "\n", s, fn, ln);
      }
  }
  #define verify(x) warn_if(x, #x, __FILE__, __LINE__)
#endif

#define unused(x) (void)(x)

//-----------------------------------------------------------------------------
// Instruction-set architecture header detection, for internal use only

/* #undef HAVE_ARM_NEON */
/* #undef HAVE_ARM_ACLE */
/* #undef HAVE_IMMINTRIN */
/* #undef HAVE_AMMINTRIN */
/* #undef HAVE_X86INTRIN */

//-----------------------------------------------------------------------------
// Instruction-set architecture and platform feature availability

/* #undef HAVE_32BIT_PLATFORM */

/* #undef HAVE_GCC_COMPILER */

/* #undef HAVE_SSE_2 */
/* #undef HAVE_GOOD_LOADU_32 */
/* #undef HAVE_GOOD_LOADU_64 */
/* #undef HAVE_SSSE_3 */
/* #undef HAVE_SSE_4_1 */
/* #undef HAVE_XOP */
/* #undef HAVE_X86_64_CRC32C */
/* #undef HAVE_X86_64_CLMUL */
/* #undef HAVE_X86_64_AES */
/* #undef HAVE_X86_64_SHA1 */
/* #undef HAVE_X86_64_SHA2 */
/* #undef HAVE_AVX */
/* #undef HAVE_AVX2 */
/* #undef HAVE_AVX512_F */
/* #undef HAVE_AVX512_BW */
/* #undef HAVE_AVX512_VL */
/* #undef HAVE_UMULH */
/* #undef HAVE_UMUL128 */
/* #undef HAVE_X86_64_ASM */
/* #undef HAVE_ARM_AES */
/* #undef HAVE_ARM_SHA1 */
/* #undef HAVE_ARM_SHA2 */
/* HAVE_ARM_ASM removed: portable C paths only */
/* HAVE_ARM64_ASM removed */
/* #undef HAVE_PPC_VSX */
/* #undef HAVE_PPC_AES */
/* #undef HAVE_PPC_ASM */

/* === SMHasher3 include/hashlib/Mathmult.h (verbatim) === */
/*
 * Multiplication and addition routines for >=64-bit math,
 * in terms of <=64-bit variables.
 *
 * Copyright (C) 2021-2023  Frank J. T. Wojcik
 * Copyright (C) 2023       jason
 * Copyright (c) 2016 Vladimir Makarov <vmakarov@gcc.gnu.org>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Some of this is based off of code from PMP Multilinear hashes:
 *
 *     Copyright (C) 2021-2022  Frank J. T. Wojcik
 *     Copyright (c) 2014-2021 Reini Urban
 *     Copyright (c) 2014, Dmytro Ivanchykhin, Sergey Ignatchenko, Daniel Lemire
 *     All rights reserved.
 *
 *     Redistribution and use in source and binary forms, with or without
 *     modification, are permitted provided that the following conditions are met:
 *
 *     1. Redistributions of source code must retain the above copyright notice, this
 *        list of conditions and the following disclaimer.
 *     2. Redistributions in binary form must reproduce the above copyright notice,
 *        this list of conditions and the following disclaimer in the documentation
 *        and/or other materials provided with the distribution.
 *
 *     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 *     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *     ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * There are several places here which have different versions of this code
 * for clang, all of which check for that via "defined(__clang__)".
 *
 * This is because clang does not work well with asm constraints. One
 * example is that, given the option, clang has some sort of preference for
 * memory operands. It may spill a register to the stack, and operate on
 * the stack copy. Or it may spill to the stack, operate on the register,
 * and then spill the new value to the stack again, without ever reading or
 * operating on the stack copy even once. Therefore, clang is not given the
 * option of memory operands.
 *
 * This is still true for clang trunk as of July 2023. You can see more
 * about this issue at:
 *    http://stackoverflow.com/questions/16850309/
 *    https://github.com/llvm/llvm-project/issues/20571
 *    https://godbolt.org/z/Wr3EvKnhn
 */

namespace MathMult {

// 32x32->64 multiplication [rhi:rlo = a * b]
static FORCE_INLINE void mult32_64( uint32_t & rlo, uint32_t & rhi, uint32_t a, uint32_t b ) {
    // XXX Are either of these asm blocks better than just the plain code?
#if 0 && defined(HAVE_ARM_ASM)
    __asm__ ("UMULL %w0, %w1, %w2, %w3"
             : "+r" (rlo), "+r" (rhi)
             : "r" (a), "r" (b)
             : "cc", "memory"
    );
#elif 0 && defined(HAVE_X86_64_ASM)
    __asm__ ("mull  %[b]"
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), [b] "rm" (b)
    );
#else
    uint64_t r = (uint64_t)a * (uint64_t)b;
    rhi = (uint32_t)(r >> 32);
    rlo = (uint32_t)r;
#endif
}

// 32x32->64 multiplication [r64 = a32 * b32]
static FORCE_INLINE void mult32_64( uint64_t & r64, uint32_t a32, uint32_t b32 ) {
#if defined(_MSC_VER) && defined(_M_IX86)
    r64 = __emulu(a32, b32);
#else
    r64 = (uint64_t)a32 * (uint64_t)b32;
#endif
}

// 96-bit addition [rhi:rmi:rlo += addhi:addmi:addlo]
static FORCE_INLINE void add96( uint32_t & rlo, uint32_t & rmi, uint32_t & rhi, const uint32_t & addlo,
        const uint32_t & addmi, const uint32_t & addhi ) {
#if defined(HAVE_ARM_ASM)
    __asm__ ("ADDS %w0, %w3, %w0\n\t"
             "ADCS %w1, %w4, %w1\n\t"
             "ADC  %w2, %w5, %w2"
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "r" (addlo), "r" (addmi), "r" (addhi)
             : "cc"
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("addl %3, %0\n\t"
             "adcl %4, %1\n\t"
             "adcl %5, %2"
  #if defined(__clang__)
             : "+r" (rlo),   "+r" (rmi),   "+r" (rhi)
             : "re" (addlo), "re" (addmi), "re" (addhi)
  #else
             : "+g,g,g,g,r,r,r,r" (rlo),  "+g,g,r,r,g,g,r,r" (rmi),  "+g,r,g,r,g,r,g,r" (rhi)
             : "re,re,re,re,m,m,m,m" (addlo), "re,re,m,m,re,re,m,m" (addmi), "re,m,re,m,re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    uint64_t w = (((uint64_t)rmi  ) << 32) + ((uint64_t)rlo  );
    uint64_t r = (((uint64_t)addmi) << 32) + ((uint64_t)addlo) + w;
    rhi += addhi + (r < w);
    rmi  = (uint32_t)(r >> 32);
    rlo  = (uint32_t)(r      );
#endif
}

// 64-bit fused multiply addition [r64 += a * b]
static FORCE_INLINE void fma32_64( uint64_t & r64, uint32_t a, uint32_t b ) {
#if defined(HAVE_ARM_ASM)
    //uint64_t ret;
    __asm__("umaddl %x0, %w1, %w2, %x3" : "=r" (r64) : "r" (a), "r" (b), "r" (r64));
    //r64 = ret;
#else
    uint64_t v;
    MathMult::mult32_64(v, a, b);
    r64 += v;
#endif
}

// 96-bit fused multiply addition [rhi:rmi:rlo += a * b]
static FORCE_INLINE void fma32_96( uint32_t & rlo, uint32_t & rmi, uint32_t & rhi, uint32_t a, uint32_t b ) {
// These #defines are not correct; some arm seems to not support this
#if 0 && defined(HAVE_ARM_ASM)
    uint32_t tmphi, tmplo;
    __asm__ ("UMULL %w3, %w4, %w5, %w6\n\t"
             "ADDS  %w0, %w3, %w0\n\t"
             "ADCS  %w1, %w4, %w1\n\t"
             "ADC   %w2, %w2, #0x0"
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "r" (a), "r" (b)
             : "cc"
    );
#elif defined(HAVE_X86_64_ASM)
    uint32_t tmplo, tmphi;
    __asm__ ("mull %6\n\t"
             "addl %%eax, %0\n\t"
             "adcl %%edx, %1\n\t"
             "adcl $0, %2"
  #if defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc"
    );
#else
    uint32_t tmplo, tmpmi, tmphi = 0;
    mult32_64(tmplo, tmpmi, a, b);
    add96(rlo, rmi, rhi, tmplo, tmpmi, tmphi);
#endif
}

// 64x64->128 multiplication [rhi:rlo = a * b]
static FORCE_INLINE void mult64_128( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_UMUL128)
    rlo = _umul128(a, b, &rhi);
#elif defined(HAVE_UMULH)
    rlo = a * b;
    rhi = __umulh(a, b);
#elif defined(HAVE_ARM64_ASM)
    /*
     * AARCH64 needs 2 insns to calculate 128-bit result of the
     * multiplication.  If we use a generic code we actually call a
     * function doing 128x128->128 bit multiplication. The function
     * is very slow.
     */
    rlo = a * b;
    __asm__ ("umulh %0, %1, %2"
             : "=r" (rhi)
             : "r" (a), "r" (b)
    );
#elif defined(HAVE_PPC_ASM)
    rlo = a * b;
    __asm__ ("mulhdu %0, %1, %2"
             : "=r" (rhi)
             : "r" (a), "r" (b)
    );
#elif defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    /*
     * We want to use AVX2 insn MULX instead of generic x86-64 MULQ
     * where it is possible.  Although on modern Intel processors MULQ
     * takes 3-cycles vs. 4 for MULX, MULX permits more freedom in
     * insn scheduling as it uses less fixed registers.
     */
    __asm__ ("mulxq %3, %1, %0"
  #if defined(__clang__)
             : "=r" (rhi), "=r" (rlo)
             : "%d" (a), "r" (b)
  #else
             : "=r" (rhi), "=r" (rlo)
             : "%d" (a), "rm" (b)
  #endif
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("mulq %3"
  #if defined(__clang__)
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), "r" (b)
  #else
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), "rm" (b)
  #endif
             : "cc"
    );
#elif defined(HAVE_INT128)
    // Maybe move this before the other x64 ASM methods?
    // Seems like it's more compiler-friendly, but it produces slower code.
    uint128_t r = (uint128_t)a * (uint128_t)b;
    rhi = (uint64_t)(r >> 64);
    rlo = (uint64_t)r;
#else
    /*
     * Implementation of 64x64->128-bit multiplication by four
     * 32x32->64 bit multiplication.
     */
    uint64_t ahi = a >> 32, bhi = b >> 32;
    uint64_t alo = (uint32_t)a, blo = (uint32_t)b;
    uint64_t tmphi   = ahi * bhi;
    uint64_t tmpmi_0 = ahi * blo;
    uint64_t tmpmi_1 = alo * bhi;
    uint64_t tmplo   = alo * blo;
    uint64_t t, carry = 0;

    t      = (tmpmi_0 << 32   ) + tmplo;
    carry += (t        < tmplo);
    rlo    = (tmpmi_1 << 32   ) + t;
    carry += (rlo      < t    );
    rhi    = (tmpmi_0 >> 32   ) + (tmpmi_1 >> 32) + tmphi + carry;
#endif
}

// 64x64->128 multiplication with no cross-lane carry [rhi:rlo ~= a * b]
static FORCE_INLINE void mult64_128_nocarry( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
    /*
     * Implementation of 64x64->128-bit multiplication by four
     * 32x32->64 bit multiplication, excluding the carry bits.  This
     * is a bit faster in the absence of a real 128-bit multiply
     * instruction, and almost as good for hashing.
     */
    uint64_t ahi = a >> 32, bhi = b >> 32;
    uint64_t alo = (uint32_t)a, blo = (uint32_t)b;
    uint64_t tmphi   = ahi * bhi;
    uint64_t tmpmi_0 = ahi * blo;
    uint64_t tmpmi_1 = alo * bhi;
    uint64_t tmplo   = alo * blo;

    rlo = tmplo + (tmpmi_0 << 32) + (tmpmi_1 << 32);
    rhi = tmphi + (tmpmi_0 >> 32) + (tmpmi_1 >> 32);
}

// 128-bit addition special case [rhi:rlo += 0:addlo]
static FORCE_INLINE void add128( uint64_t & rlo, uint64_t & rhi, uint64_t addlo ) {
#if defined(HAVE_X86_64_ASM)
    __asm__ ("addq %2, %0\n\t"
             "adcq $0, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi)
             : "r" (addlo)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi)
             : "re" (addlo)
  #else
             : "+g,r" (rlo), "+g,g" (rhi)
             : "re,m" (addlo)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rhi += (rlo < addlo);
#endif
}

// 128-bit addition [rhi:rlo += addhi:addlo]
static FORCE_INLINE void add128( uint64_t & rlo, uint64_t & rhi, uint64_t addlo, uint64_t addhi ) {
#if defined(HAVE_PPC_ASM)
    __asm__ ("addc %1, %1, %3\n\t"
             "adde %0, %0, %2"
             : "+r" (rhi), "+r" (rlo)
             : "r" (addhi), "r" (addlo)
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("addq %2, %0\n\t"
             "adcq %3, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi)
             : "r" (addlo), "r" (addhi)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi)
             : "re" (addlo), "re" (addhi)
  #else
             : "+g,g,r,r" (rlo), "+g,r,g,r" (rhi)
             : "re,re,m,m" (addlo), "re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rhi += (rlo < addlo);
    rhi += addhi;
#endif
}

// 192-bit addition [rhi:rmi:rlo += addhi:addmi:addlo]
static FORCE_INLINE void add192( uint64_t & rlo, uint64_t & rmi, uint64_t & rhi, const uint64_t & addlo,
        const uint64_t & addmi, const uint64_t & addhi ) {
#if defined(HAVE_X86_64_ASM)
    __asm__ ("addq %3, %0\n\t"
             "adcq %4, %1\n\t"
             "adcq %5, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "r" (addlo), "r" (addmi), "r" (addhi)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "re" (addlo), "re" (addmi), "re" (addhi)
  #else
             : "+g,g,g,g,r,r,r,r" (rlo), "+g,g,r,r,g,g,r,r" (rmi), "+g,r,g,r,g,r,g,r" (rhi)
             : "re,re,re,re,m,m,m,m" (addlo), "re,re,m,m,re,re,m,m" (addmi), "re,m,re,m,re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rmi += (rlo < addlo);
    rmi += addmi;
    rhi += (rmi < addmi);
    rhi += addhi;
#endif
}

// 128-bit fused multiply addition [rhi:rlo += a * b]
static FORCE_INLINE void fma64_128( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulxq %5, %2, %3\n\t"
             "addq %2, %0\n\t"
             "adcq %3, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "d" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "rm" (b)
  #endif
             : "cc");
#elif defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulq %5\n\t"
             "addq %%rax, %0\n\t"
             "adcq %%rdx, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "a" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc");
#else
    uint64_t tmplo, tmphi;
    mult64_128(tmplo, tmphi, a, b);
    add128(rlo, rhi, tmplo, tmphi);
#endif
}

// 192-bit fused multiply addition [rhi:rmi:rlo += a * b]
static FORCE_INLINE void fma64_192( uint64_t & rlo, uint64_t & rmi, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulxq %6, %3, %4\n\t"
             "addq %3, %0\n\t"
             "adcq %4, %1\n\t"
             "adcq $0, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "d" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "rm" (b)
  #endif
             : "cc");
#elif defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulq %6\n\t"
             "addq %%rax, %0\n\t"
             "adcq %%rdx, %1\n\t"
             "adcq $0, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "a" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc");
#else
    uint64_t tmplo, tmpmi, tmphi = 0;
    mult64_128(tmplo, tmpmi, a, b);
    add192(rlo, rmi, rhi, tmplo, tmpmi, tmphi);
#endif
}

// 128x128->128 multiplication [rhi:rlo = ahi:alo * bhi:blo]
static FORCE_INLINE void mult128_128( uint64_t & rlo, uint64_t & rhi, uint64_t alo,
        uint64_t ahi, uint64_t blo, uint64_t bhi ) {
#if defined(HAVE_INT128)
    uint128_t r = (((uint128_t)ahi) << 64) + (uint128_t)alo;
    uint128_t c = (((uint128_t)bhi) << 64) + (uint128_t)blo;
    r   = r * c;
    rhi = (uint64_t)(r >> 64);
    rlo = (uint64_t)r;
#else
    mult64_128(rlo, rhi, alo, blo);
    rhi += bhi * alo;
    rhi += blo * ahi;
#endif
}

} // namespace MathMult

/* ---- minimal stand-in for SMHasher3 Hashinfo.h / Hashlib.h registration ---- */
#include <vector>
#include <set>
#include <string>
#define FLAG_EXPAND_LIST(X) X(HASH_DONOTHING) X(HASH_MOCK) X(HASH_CRYPTOGRAPHIC) X(HASH_CRYPTOGRAPHIC_WEAK) X(HASH_CRC_BASED) X(HASH_AES_BASED) X(HASH_CLMUL_BASED) X(HASH_LOOKUP_TABLE) X(HASH_XL_SEED) X(HASH_SMALL_SEED) X(HASH_NO_SEED) X(HASH_SYSTEM_SPECIFIC) X(HASH_ENDIAN_INDEPENDENT) X(HASH_FLOATING_POINT) \
 X(IMPL_SANITY_FAILS) X(IMPL_SLOW) X(IMPL_VERY_SLOW) X(IMPL_READ_PAST_EOB) X(IMPL_TYPE_PUNNING) X(IMPL_INCREMENTAL) X(IMPL_INCREMENTAL_DIFFERENT) X(IMPL_128BIT) X(IMPL_MULTIPLY) X(IMPL_MULTIPLY_64_64) X(IMPL_MULTIPLY_64_128) X(IMPL_MULTIPLY_128_128) X(IMPL_ROTATE) X(IMPL_ROTATE_VARIABLE) X(IMPL_SHIFT_VARIABLE) X(IMPL_MODULUS) X(IMPL_ASM) X(IMPL_CANONICAL_LE) X(IMPL_CANONICAL_BE) X(IMPL_CANONICAL_BOTH) X(IMPL_SEED_WITH_HINT) X(IMPL_LICENSE_PUBLIC_DOMAIN) X(IMPL_LICENSE_BOOST) X(IMPL_LICENSE_BSD) X(IMPL_LICENSE_MIT) X(IMPL_LICENSE_APACHE2) X(IMPL_LICENSE_ZLIB) X(IMPL_LICENSE_GPL3)
#define FE1(n) FLAG_ENUM_##n,
enum { FLAG_EXPAND_LIST(FE1) FLAG_ENUM_COUNT };
#define FE2(n) static const uint64_t FLAG_##n = 1ULL << FLAG_ENUM_##n;
FLAG_EXPAND_LIST(FE2)
class HashInfo;
typedef void   (*HashFn)(const void *in, const size_t len, const seed_t seed, void *out);
typedef seed_t (*HashSeedfixFn)(const HashInfo *hinfo, const seed_t seed);
struct HashFamilyInfo { enum SrcStatus { SRC_UNKNOWN, SRC_FROZEN, SRC_STABLEISH, SRC_ACTIVE }; const char *name; const char *src_url = ""; int src_status = 0;
  HashFamilyInfo(const char *n) : name(n) {} };
struct HashInfo {
  const char *name, *family; const char *desc = ""; const char *impl = "";
  uint64_t hash_flags = 0, impl_flags = 0; uint32_t bits = 0;
  uint32_t verification_LE = 0, verification_BE = 0;
  HashFn hashfn_native = nullptr, hashfn_bswap = nullptr;
  HashSeedfixFn seedfixfn = nullptr; std::set<seed_t> badseeds; const char *badseeddesc = "";
  uint32_t sort_order = 0;
  HashInfo(const char *n, const char *f) : name(n), family(f) {}
};
static std::vector<HashInfo> &registry() { static std::vector<HashInfo> r; return r; }
static unsigned register_hash(const HashInfo *h) { registry().push_back(*h); return 0; }
static seed_t excludeBadseeds(const HashInfo *hinfo, const seed_t seed) { (void)hinfo; return seed; }
#define CONCAT_INNER(x, y) x ## y
#define CONCAT(x, y) CONCAT_INNER(x, y)
#define REGISTER_FAMILY(N, ...) static HashFamilyInfo THIS_HASH_FAMILY = []{ HashFamilyInfo $(#N); __VA_ARGS__; return $; }(); unsigned CONCAT(N,_ref)
#define REGISTER_HASH(N, ...) static HashInfo CONCAT(Hash_,N) = []{ HashInfo $(#N, THIS_HASH_FAMILY.name); __VA_ARGS__; register_hash(&$); return $; }()
static const HashInfo *findHash(const char *n) { for (auto &h : registry()) if (!strcmp(h.name, n)) return &h; return nullptr; }
/* SMHasher3 lib/Hashinfo.cpp _ComputedVerifyImpl, native endianness, SEED_FORCED (no seedfn in these files) */
static uint32_t sm3_verification(const HashInfo *hi) {
  const uint32_t hb = hi->bits / 8; std::vector<uint8_t> key(256, 0), hashes(hb * 256, 0), total(hb, 0);
  for (int i = 0; i < 256; i++) { hi->hashfn_native(key.data(), i, (seed_t)(256 - i), &hashes[i * hb]); key[i] = (uint8_t)i; }
  hi->hashfn_native(hashes.data(), hb * 256, 0, total.data());
  return (uint32_t)total[0] | ((uint32_t)total[1] << 8) | ((uint32_t)total[2] << 16) | ((uint32_t)total[3] << 24);
}
/* ===================== SMHasher3 hashes/cityhash.cpp (verbatim) ===================== */
/*
 * CityHash family v1.1.1, by Geoff Pike and Jyrki Alakuijala
 *
 * Copyright (C) 2022 Frank J. T. Wojcik
 * Copyright (c) 2014-2015 Reini Urban
 * Copyright (c) 2011 Google, Inc.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#if !defined(IMPORT_CITY)
#endif

// CityHash128WithSeed is no longer enabled in this family. This is because
// this exact same hash function is part of the (later) FarmHash family,
// and there's no point in testing them twice.

#if defined(HAVE_X86_64_CRC32C)
#endif

using namespace std;

//------------------------------------------------------------
#if defined(HAVE_INT128)

static inline uint64_t Uint128Low64( const uint128_t x ) {
    return static_cast<uint64_t>(x);
}

static inline uint64_t Uint128High64( const uint128_t x ) {
    return static_cast<uint64_t>(x >> 64);
}

static inline uint128_t Uint128( uint64_t lo, uint64_t hi ) {
    return lo + (((uint128_t)hi) << 64);
}

#else
typedef std::pair<uint64_t, uint64_t> uint128_t;

static inline uint64_t Uint128Low64( const uint128_t x ) {
    return x.first;
}

static inline uint64_t Uint128High64( const uint128_t x ) {
    return x.second;
}

static inline uint128_t Uint128( uint64_t lo, uint64_t hi ) {
    return uint128_t(lo, hi);
}

#endif

//------------------------------------------------------------
template <bool bswap>
static inline uint32_t Fetch32( const uint8_t * p ) {
    return GET_U32<bswap>(p, 0);
}

template <bool bswap>
static inline uint64_t Fetch64( const uint8_t * p ) {
    return GET_U64<bswap>(p, 0);
}

//------------------------------------------------------------
// Some primes between 2^63 and 2^64 for various uses.
static const uint64_t k0 = UINT64_C(0xc3a5c85c97cb3127);
static const uint64_t k1 = UINT64_C(0xb492b66fbe98f273);
static const uint64_t k2 = UINT64_C(0x9ae16a3b2f90404f);

// Magic numbers for 32-bit hashing.  Copied from Murmur3.
static const uint32_t c1 = 0xcc9e2d51;
static const uint32_t c2 = 0x1b873593;

//------------------------------------------------------------
// A 32-bit to 32-bit integer hash copied from Murmur3.
static uint32_t fmix( uint32_t h ) {
    h ^= h >> 16;
    h *= 0x85ebca6b;
    h ^= h >> 13;
    h *= 0xc2b2ae35;
    h ^= h >> 16;
    return h;
}

// Helper from Murmur3 for combining two 32-bit values.
static uint32_t Mur( uint32_t a, uint32_t h ) {
    a *= c1;
    a  = ROTR32(a, 17);
    a *= c2;
    h ^= a;
    h  = ROTR32(h, 19);
    return h * 5 + 0xe6546b64;
}

#define PERMUTE3(a, b, c) do { std::swap(a, b); std::swap(a, c); } while (0)

//------------------------------------------------------------
// All seeding for these 32-bit functions is unofficial and home-grown for
// SMHasher3

static uint32_t Hash32Len0to4( const uint8_t * s, size_t len, uint32_t seed ) {
    uint32_t b = seed;
    uint32_t c = 9;

    for (size_t i = 0; i < len; i++) {
        b  = b * c1 + s[i];
        c ^= b;
    }
    return fmix(Mur(b, Mur(len, c)));
}

template <bool bswap>
static uint32_t Hash32Len5to12( const uint8_t * s, size_t len, uint32_t seed ) {
    uint32_t a = len + seed, b = a * 5, c = 9, d = b;

    a += Fetch32<bswap>(s);
    b += Fetch32<bswap>(s + len - 4);
    c += Fetch32<bswap>(s + ((len >> 1) & 4));
    return fmix(Mur(c, Mur(b, Mur(a, d))));
}

template <bool bswap>
static uint32_t Hash32Len13to24( const uint8_t * s, size_t len, uint32_t seed ) {
    uint32_t a = Fetch32<bswap>(s - 4   + (len >> 1));
    uint32_t b = Fetch32<bswap>(s + 4               );
    uint32_t c = Fetch32<bswap>(s + len - 8         );
    uint32_t d = Fetch32<bswap>(s +       (len >> 1));
    uint32_t e = Fetch32<bswap>(s                   );
    uint32_t f = Fetch32<bswap>(s + len - 4         );
    uint32_t h = seed + len;

    return fmix(Mur(f, Mur(e, Mur(d, Mur(c, Mur(b, Mur(a, h)))))));
}

template <bool bswap>
static uint32_t CityHash32WithSeed( const uint8_t * s, size_t len, uint32_t seed ) {
    if (len <= 24) {
        return len <= 12 ?
                   (len <= 4 ?
                       Hash32Len0to4(s, len, seed) :
                       Hash32Len5to12<bswap>(s, len, seed)) :
                   Hash32Len13to24<bswap>(s, len, seed);
    }

    // len > 24
    uint32_t h = len + seed, g = c1 * h, f = g;
    uint32_t a0 = ROTR32(Fetch32<bswap>(s + len -  4) * c1, 17) * c2;
    uint32_t a1 = ROTR32(Fetch32<bswap>(s + len -  8) * c1, 17) * c2;
    uint32_t a2 = ROTR32(Fetch32<bswap>(s + len - 16) * c1, 17) * c2;
    uint32_t a3 = ROTR32(Fetch32<bswap>(s + len - 12) * c1, 17) * c2;
    uint32_t a4 = ROTR32(Fetch32<bswap>(s + len - 20) * c1, 17) * c2;
    h ^= a0;
    h  = ROTR32(h, 19);
    h  = h * 5 + 0xe6546b64;
    h ^= a2;
    h  = ROTR32(h, 19);
    h  = h * 5 + 0xe6546b64;
    g ^= a1;
    g  = ROTR32(g, 19);
    g  = g * 5 + 0xe6546b64;
    g ^= a3;
    g  = ROTR32(g, 19);
    g  = g * 5 + 0xe6546b64;
    f += a4;
    f  = ROTR32(f, 19);
    f  = f * 5 + 0xe6546b64;
    size_t iters = (len - 1) / 20;
    do {
        uint32_t a0 = ROTR32(Fetch32<bswap>(s)      * c1, 17) * c2;
        uint32_t a1 = Fetch32<bswap>(s +  4);
        uint32_t a2 = ROTR32(Fetch32<bswap>(s +  8) * c1, 17) * c2;
        uint32_t a3 = ROTR32(Fetch32<bswap>(s + 12) * c1, 17) * c2;
        uint32_t a4 = Fetch32<bswap>(s + 16);
        h ^= a0;
        h  = ROTR32(h, 18);
        h  = h * 5 + 0xe6546b64;
        f += a1;
        f  = ROTR32(f, 19);
        f  = f * c1;
        g += a2;
        g  = ROTR32(g, 18);
        g  = g * 5 + 0xe6546b64;
        h ^= a3 + a1;
        h  = ROTR32(h, 19);
        h  = h * 5 + 0xe6546b64;
        g ^= a4;
        g  = BSWAP(g) * 5;
        h += a4 * 5;
        h  = BSWAP(h);
        f += a0;
        PERMUTE3(f, h, g);
        s += 20;
    } while (--iters != 0);
    g = ROTR32(g, 11) * c1;
    g = ROTR32(g, 17) * c1;
    f = ROTR32(f, 11) * c1;
    f = ROTR32(f, 17) * c1;
    h = h + g;
    h = ROTR32(h, 19);
    h = h * 5 + 0xe6546b64;
    h = ROTR32(h, 17) * c1;
    h = h + f;
    h = ROTR32(h, 19);
    h = h * 5 + 0xe6546b64;
    h = ROTR32(h, 17) * c1;
    return h;
}

//------------------------------------------------------------
// Hash 128 input bits down to 64 bits of output.
// This is intended to be a reasonably good hash function.
static inline uint64_t Hash128to64( const uint128_t & x ) {
    // Murmur-inspired hashing.
    const uint64_t kMul = UINT64_C(0x9ddfea08eb382d69);
    uint64_t       a    = (Uint128Low64(x)  ^ Uint128High64(x)) * kMul;
    uint64_t       b;

    a ^= (a >> 47);
    b  = (Uint128High64(x) ^ a) * kMul;
    b ^= (b >> 47);
    b *= kMul;
    return b;
}

static uint64_t HashLen16( uint64_t u, uint64_t v ) {
    return Hash128to64(Uint128(u, v));
}

static uint64_t HashLen16( uint64_t u, uint64_t v, uint64_t mul ) {
    // Murmur-inspired hashing.
    uint64_t a = (u ^ v) * mul;

    a ^= (a >> 47);
    uint64_t b = (v ^ a) * mul;
    b ^= (b >> 47);
    b *= mul;
    return b;
}

static uint64_t ShiftMix( uint64_t val ) {
    return val ^ (val >> 47);
}

// Return a 16-byte hash for 48 bytes.  Quick and dirty.
// Callers do best to use "random-looking" values for a and b.
static pair<uint64_t, uint64_t> WeakHashLen32WithSeeds( uint64_t w, uint64_t x,
        uint64_t y, uint64_t z, uint64_t a, uint64_t b ) {
    a += w;
    uint64_t c = a;
    b  = b + a + z;
    b  = ROTR64(b, 21);
    a += x;
    a += y;
    b += ROTR64(a, 44);
    return make_pair(a + z, b + c);
}

// Return a 16-byte hash for s[0] ... s[31], a, and b.  Quick and dirty.
template <bool bswap>
static pair<uint64_t, uint64_t> WeakHashLen32WithSeeds( const uint8_t * s, uint64_t a, uint64_t b ) {
    return WeakHashLen32WithSeeds(Fetch64<bswap>(s), Fetch64<bswap>(
            s + 8), Fetch64<bswap>(s + 16), Fetch64<bswap>(s + 24), a, b);
}

//------------------------------------------------------------
template <bool bswap>
static uint64_t HashLen0to16( const uint8_t * s, size_t len ) {
    if (len >= 8) {
        uint64_t mul = k2 + len * 2;
        uint64_t a   = Fetch64<bswap>(s) + k2;
        uint64_t b   = Fetch64<bswap>(s + len - 8);
        uint64_t c   = ROTR64(b, 37) * mul + a;
        uint64_t d   = (ROTR64(a, 25) + b) * mul;
        return HashLen16(c, d, mul);
    }
    if (len >= 4) {
        uint64_t mul = k2 + len * 2;
        uint64_t a   = Fetch32<bswap>(s);
        return HashLen16(len + (a << 3), Fetch32<bswap>(s + len - 4), mul);
    }
    if (len > 0) {
        uint8_t  a = s[0];
        uint8_t  b = s[len >> 1];
        uint8_t  c = s[len  - 1];
        uint32_t y = static_cast<uint32_t>(a)   + (static_cast<uint32_t>(b) << 8);
        uint32_t z = static_cast<uint32_t>(len) + (static_cast<uint32_t>(c) << 2);
        return ShiftMix(y * k2 ^ z * k0) * k2;
    }
    return k2;
}

// This probably works well for 16-byte strings as well, but it may be overkill
// in that case.
template <bool bswap>
static uint64_t HashLen17to32( const uint8_t * s, size_t len ) {
    uint64_t mul = k2 + len * 2;
    uint64_t a   = Fetch64<bswap>(s           ) * k1;
    uint64_t b   = Fetch64<bswap>(s + 8       );
    uint64_t c   = Fetch64<bswap>(s + len -  8) * mul;
    uint64_t d   = Fetch64<bswap>(s + len - 16) * k2;

    return HashLen16(ROTR64(a + b, 43) + ROTR64(c, 30) + d, a + ROTR64(b + k2, 18) + c, mul);
}

// Return an 8-byte hash for 33 to 64 bytes.
template <bool bswap>
static uint64_t HashLen33to64( const uint8_t * s, size_t len ) {
    uint64_t mul = k2 + len * 2;
    uint64_t a   = Fetch64<bswap>(s    ) * k2;
    uint64_t b   = Fetch64<bswap>(s + 8);
    uint64_t c   = Fetch64<bswap>(s + len - 24);
    uint64_t d   = Fetch64<bswap>(s + len - 32);
    uint64_t e   = Fetch64<bswap>(s + 16) * k2;
    uint64_t f   = Fetch64<bswap>(s + 24) * 9;
    uint64_t g   = Fetch64<bswap>(s + len -  8);
    uint64_t h   = Fetch64<bswap>(s + len - 16) * mul;
    uint64_t u   = ROTR64(a + g, 43) + (ROTR64(b, 30) + c) * 9;
    uint64_t v   = ((a + g) ^ d) + f + 1;
    uint64_t w   = BSWAP((u + v) * mul) + h;
    uint64_t x   = ROTR64(e + f, 42) + c;
    uint64_t y   = (BSWAP((v + w) * mul) + g) * mul;
    uint64_t z   = e + f + c;
    a = BSWAP((x + z) * mul + y) + b;
    b = ShiftMix((z + a) * mul + d + h) * mul;
    return b + x;
}

template <bool bswap>
static uint64_t CityHash64( const uint8_t * s, size_t len ) {
    if (len <= 32) {
        if (len <= 16) {
            return HashLen0to16<bswap>(s, len);
        } else {
            return HashLen17to32<bswap>(s, len);
        }
    } else if (len <= 64) {
        return HashLen33to64<bswap>(s, len);
    }

    // For strings over 64 bytes we hash the end first, and then as we
    // loop we keep 56 bytes of state: v, w, x, y, and z.
    uint64_t x = Fetch64<bswap>(s + len - 40);
    uint64_t y = Fetch64<bswap>(s + len - 16) + Fetch64<bswap>(s + len - 56);
    uint64_t z = HashLen16(Fetch64<bswap>(s + len - 48) + len, Fetch64<bswap>(s + len - 24));
    pair<uint64_t, uint64_t> v = WeakHashLen32WithSeeds<bswap>(s + len - 64, len   , z);
    pair<uint64_t, uint64_t> w = WeakHashLen32WithSeeds<bswap>(s + len - 32, y + k1, x);
    x = x * k1 + Fetch64<bswap>(s);

    // Decrease len to the nearest multiple of 64, and operate on 64-byte chunks.
    len = (len - 1) & ~static_cast<size_t>(63);
    do {
        x    = ROTR64(x + y        + v.first + Fetch64<bswap>(s +  8), 37) * k1;
        y    = ROTR64(y + v.second +           Fetch64<bswap>(s + 48), 42) * k1;
        x   ^= w.second;
        y   += v.first + Fetch64<bswap>(s + 40);
        z    = ROTR64(z + w.first, 33) * k1;
        v    = WeakHashLen32WithSeeds<bswap>(s     , v.second * k1, x + w.first);
        w    = WeakHashLen32WithSeeds<bswap>(s + 32, z + w.second , y + Fetch64<bswap>(s + 16));
        std::swap(z, x);
        s   += 64;
        len -= 64;
    } while (len != 0);
    return HashLen16(HashLen16(v.first, w.first) + ShiftMix(y) * k1 + z, HashLen16(v.second, w.second) + x);
}

template <bool bswap>
static uint64_t CityHash64WithSeeds( const uint8_t * s, size_t len, uint64_t seed0, uint64_t seed1 ) {
    return HashLen16(CityHash64<bswap>(s, len) - seed0, seed1);
}

template <bool bswap>
static uint64_t CityHash64WithSeed( const uint8_t * s, size_t len, uint64_t seed ) {
    return CityHash64WithSeeds<bswap>(s, len, k2, seed);
}

//------------------------------------------------------------
template <bool bswap>
static uint128_t CityMurmur( const uint8_t * s, size_t len, uint128_t seed ) {
    uint64_t a = Uint128Low64(seed);
    uint64_t b = Uint128High64(seed);
    uint64_t c = 0;
    uint64_t d = 0;

    if (len <= 16) {
        a = ShiftMix(a * k1) * k1;
        c = b * k1 + HashLen0to16<bswap>(s, len);
        d = ShiftMix(a + (len >= 8 ? Fetch64<bswap>(s) : c));
    } else {
        c  = HashLen16(Fetch64<bswap>(s + len - 8) + k1, a      );
        d  = HashLen16(b + len, c + Fetch64<bswap>(s + len - 16));
        a += d;
        // len > 16 here, so do...while is safe
        do {
            a   ^= ShiftMix(Fetch64<bswap>(s)     * k1) * k1;
            a   *= k1;
            b   ^= a;
            c   ^= ShiftMix(Fetch64<bswap>(s + 8) * k1) * k1;
            c   *= k1;
            d   ^= c;
            s   += 16;
            len -= 16;
        } while (len > 16);
    }
    a = HashLen16(a, c);
    b = HashLen16(d, b);
    return Uint128(a ^ b, HashLen16(b, a));
}

template <bool bswap>
static uint128_t CityHash128WithSeed( const uint8_t * s, size_t len, uint128_t seed ) {
    if (len < 128) {
        return CityMurmur<bswap>(s, len, seed);
    }

    // We expect len >= 128 to be the common case.  Keep 56 bytes of state:
    // v, w, x, y, and z.
    pair<uint64_t, uint64_t> v, w;
    uint64_t x = Uint128Low64(seed);
    uint64_t y = Uint128High64(seed);
    uint64_t z = len * k1;
    v.first  = ROTR64(y ^ k1 , 49) * k1 + Fetch64<bswap>(s);
    v.second = ROTR64(v.first, 42) * k1 + Fetch64<bswap>(s + 8);
    w.first  = ROTR64(y + z  , 35) * k1 + x;
    w.second = ROTR64(x + Fetch64<bswap>(s + 88), 53) * k1;

    // This is the same inner loop as CityHash64(), manually unrolled.
    do {
        x    = ROTR64(x + y        + v.first + Fetch64<bswap>(s +  8), 37) * k1;
        y    = ROTR64(y + v.second +           Fetch64<bswap>(s + 48), 42) * k1;
        x   ^= w.second;
        y   += v.first + Fetch64<bswap>(s + 40);
        z    = ROTR64(z + w.first, 33) * k1;
        v    = WeakHashLen32WithSeeds<bswap>(s     , v.second * k1, x + w.first);
        w    = WeakHashLen32WithSeeds<bswap>(s + 32, z + w.second , y + Fetch64<bswap>(s + 16));
        std::swap(z, x);
        s   += 64;
        x    = ROTR64(x + y        + v.first + Fetch64<bswap>(s +  8), 37) * k1;
        y    = ROTR64(y + v.second +           Fetch64<bswap>(s + 48), 42) * k1;
        x   ^= w.second;
        y   += v.first + Fetch64<bswap>(s + 40);
        z    = ROTR64(z + w.first, 33) * k1;
        v    = WeakHashLen32WithSeeds<bswap>(s     , v.second * k1, x + w.first);
        w    = WeakHashLen32WithSeeds<bswap>(s + 32, z + w.second , y + Fetch64<bswap>(s + 16));
        std::swap(z, x);
        s   += 64;
        len -= 128;
    } while (likely(len >= 128));
    x += ROTR64(v.first + z, 49) * k0;
    y  = y * k0 + ROTR64(w.second, 37);
    z  = z * k0 + ROTR64(w.first,  27);
    w.first *= 9;
    v.first *= k0;
    // If 0 < len < 128, hash up to 4 chunks of 32 bytes each from the end of s.
    for (size_t tail_done = 0; tail_done < len;) {
        tail_done += 32;
        y          = ROTR64(x + y, 42) * k0 + v.second;
        w.first   += Fetch64<bswap>(s + len - tail_done + 16);
        x          = x                 * k0 + w.first;
        z         += w.second +     Fetch64<bswap>(s + len - tail_done);
        w.second  += v.first;
        v          = WeakHashLen32WithSeeds<bswap>(s + len - tail_done, v.first + z, v.second);
        v.first   *= k0;
    }
    // At this point our 56 bytes of state should contain more than
    // enough information for a strong 128-bit hash.  We use two
    // different 56-byte-to-8-byte hashes to get a 16-byte final result.
    x = HashLen16(x    , v.first);
    y = HashLen16(y + z, w.first);
    return Uint128(HashLen16(x + v.second, w.second) + y, HashLen16(x + w.second, y + v.second));
}

template <bool bswap>
static uint128_t CityHash128( const char * s, size_t len ) {
    return len >= 16 ?
               CityHash128WithSeed<bswap>(s + 16, len - 16, Uint128(Fetch64<bswap>(s), Fetch64<bswap>(s + 8) + k0)) :
               CityHash128WithSeed<bswap>(s     , len     , Uint128(k0, k1));
}

//------------------------------------------------------------
#if defined(HAVE_X86_64_CRC32C)

// Requires len >= 240.
template <bool bswap>
static void CityHashCrc256Long( const uint8_t * s, size_t len, uint32_t seed, uint64_t * result ) {
    uint64_t a = Fetch64<bswap>(s +  56) + k0;
    uint64_t b = Fetch64<bswap>(s +  96) + k0;
    uint64_t c = HashLen16(b, len);
    uint64_t d = Fetch64<bswap>(s + 120) * k0 + len;
    uint64_t e = Fetch64<bswap>(s + 184) + seed;
    uint64_t f = 0;
    uint64_t g = 0;
    uint64_t h = c + d;
    uint64_t x = seed;
    uint64_t y = 0;
    uint64_t z = 0;

    result[0] = c;
    result[1] = d;

    // 240 bytes of input per iter.
    size_t iters = len / 240;
    len -= iters * 240;
    do {
#undef CHUNK
#define CHUNK(r)                      \
        PERMUTE3(x, z, y);            \
        b += Fetch64<bswap>(s);       \
        c += Fetch64<bswap>(s + 8);   \
        d += Fetch64<bswap>(s + 16);  \
        e += Fetch64<bswap>(s + 24);  \
        f += Fetch64<bswap>(s + 32);  \
        a += b;                       \
        h += f;                       \
        b += c;                       \
        f += d;                       \
        g += e;                       \
        e += z;                       \
        g += x;                       \
        z  = _mm_crc32_u64(z, b + g); \
        y  = _mm_crc32_u64(y, e + h); \
        x  = _mm_crc32_u64(x, f + a); \
        e  = ROTR64(e, r);            \
        c += e;                       \
        s += 40

        CHUNK( 0); PERMUTE3(a, h, c);
        CHUNK(33); PERMUTE3(a, h, f);
        CHUNK( 0); PERMUTE3(b, h, f);
        CHUNK(42); PERMUTE3(b, h, d);
        CHUNK( 0); PERMUTE3(b, h, e);
        CHUNK(33); PERMUTE3(a, h, e);
    } while (--iters > 0);

    while (len >= 40) {
        CHUNK(29);
        e ^= ROTR64(a, 20);
        h += ROTR64(b, 30);
        g ^= ROTR64(c, 40);
        f += ROTR64(d, 34);
        PERMUTE3(c, h, g);
        len -= 40;
    }
    if (len > 0) {
        s = s + len - 40;
        CHUNK(33);
        e ^= ROTR64(a, 43);
        h += ROTR64(b, 42);
        g ^= ROTR64(c, 41);
        f += ROTR64(d, 40);
    }
    result[0] ^= h;
    result[1] ^= g;

    g += h;
    a  = HashLen16(a, g + z);
    x += y << 32;
    b += x;
    c  = HashLen16(c, z) + h;
    d  = HashLen16(d, e + result[0]);
    g += e;
    h += HashLen16(x, f);
    e  = HashLen16(a, d) + g;
    z  = HashLen16(b, c) + a;
    y  = HashLen16(g, h) + c;

    result[0]  = e + z + y + x;
    a          = ShiftMix((a + y) * k0) * k0 + b;
    result[1] += a + result[0];
    a          = ShiftMix(a * k0) * k0 + c;
    result[2]  = a + result[1];
    a          = ShiftMix((a + e) * k0) * k0;
    result[3]  = a + result[2];
}

// Requires len < 240.
template <bool bswap>
static void CityHashCrc256Short( const uint8_t * s, size_t len, uint64_t * result ) {
    uint8_t buf[240];

    memcpy(buf, s, len);
    memset(buf + len, 0, 240 - len);
    CityHashCrc256Long<bswap>(buf, 240, ~static_cast<uint32_t>(len), result);
}

template <bool bswap>
static void CityHashCrc256( const uint8_t * s, size_t len, uint64_t * result ) {
    if (likely(len >= 240)) {
        CityHashCrc256Long<bswap>(s, len, 0, result);
    } else {
        CityHashCrc256Short<bswap>(s, len, result);
    }
}

// Requires len < 240.
// Unofficial homegrown seeding for SMHasher3
template <bool bswap>
static void CityHashCrc256ShortWithSeed( const uint8_t * s, size_t len, uint32_t seed, uint64_t * result ) {
    uint8_t buf[240];

    memcpy(buf, s, len);
    memset(buf + len, 0, 240 - len);
    CityHashCrc256Long<bswap>(buf, 240, HashLen16(seed, ~static_cast<uint32_t>(len)), result);
}

// Unofficial
template <bool bswap>
static void CityHashCrc256WithSeed( const uint8_t * s, size_t len, uint32_t seed, uint64_t * result ) {
    if (likely(len >= 240)) {
        CityHashCrc256Long<bswap>(s, len, seed, result);
    } else {
        CityHashCrc256ShortWithSeed<bswap>(s, len, seed, result);
    }
}

template <bool bswap>
static uint128_t CityHashCrc128WithSeed( const uint8_t * s, size_t len, uint128_t seed ) {
    if (len <= 900) {
        return CityHash128WithSeed<bswap>(s, len, seed);
    } else {
        uint64_t result[4];
        CityHashCrc256<bswap>(s, len, result);
        uint64_t u = Uint128High64(seed) + result[0];
        uint64_t v = Uint128Low64(seed)  + result[1];
        return Uint128(HashLen16(u, v + result[2]), HashLen16(ROTR64(v, 32), u * k0 + result[3]));
    }
}

template <bool bswap>
static uint128_t CityHashCrc128( const uint8_t * s, size_t len ) {
    if (len <= 900) {
        return CityHash128<bswap>(s, len);
    } else {
        uint64_t result[4];
        CityHashCrc256<bswap>(s, len, result);
        return Uint128(result[2], result[3]);
    }
}

#endif

//------------------------------------------------------------
template <bool bswap>
static void City32( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint32_t h;

    h = CityHash32WithSeed<bswap>((const uint8_t *)in, len, (uint32_t)seed);
    PUT_U32<bswap>(h, (uint8_t *)out, 0);
}

template <bool bswap>
static void City64( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint64_t h;

    h = CityHash64WithSeed<bswap>((const uint8_t *)in, len, (uint64_t)seed);
    PUT_U64<bswap>(h, (uint8_t *)out, 0);
}

#if 0

template <bool bswap, uint32_t seedmode>
static void City128( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint128_t seed128;

    switch (seedmode) {
    case 1: seed128 = Uint128((uint64_t)seed, 0); break;
    case 2: seed128 = Uint128(0, (uint64_t)seed); break;
    case 3: seed128 = Uint128((uint64_t)seed, (uint64_t)seed); break;
    default: exit(1);
    }

    uint128_t h;
    h = CityHash128WithSeed<bswap>((const uint8_t *)in, len, seed128);
    PUT_U64<bswap>(Uint128Low64(h) , (uint8_t *)out, 0);
    PUT_U64<bswap>(Uint128High64(h), (uint8_t *)out, 8);
}

template <bool bswap, uint32_t seedmode>
static void CityMurmur_128( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint128_t seed128;

    switch (seedmode) {
    case 1: seed128 = Uint128((uint64_t)seed, 0); break;
    case 2: seed128 = Uint128(0, (uint64_t)seed); break;
    case 3: seed128 = Uint128((uint64_t)seed, (uint64_t)seed); break;
    default: exit(1);
    }

    uint128_t h;
    h = CityMurmur<bswap>((const uint8_t *)in, len, seed128);
    PUT_U64<bswap>(Uint128Low64(h) , (uint8_t *)out, 0);
    PUT_U64<bswap>(Uint128High64(h), (uint8_t *)out, 8);
}

#endif

#if defined(HAVE_X86_64_CRC32C)

template <bool bswap, uint32_t seedmode>
static void CityCrc128( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint128_t seed128;

    switch (seedmode) {
    case 1: seed128 = Uint128((uint64_t)seed, 0); break;
    case 2: seed128 = Uint128(0, (uint64_t)seed); break;
    case 3: seed128 = Uint128((uint64_t)seed, (uint64_t)seed); break;
    default: exit(1);
    }

    uint128_t h;
    h = CityHashCrc128WithSeed<bswap>((const uint8_t *)in, len, seed128);
    PUT_U64<bswap>(Uint128Low64(h) , (uint8_t *)out, 0);
    PUT_U64<bswap>(Uint128High64(h), (uint8_t *)out, 8);
}

template <bool bswap>
static void CityCrc256( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint64_t result[4];

    CityHashCrc256WithSeed<bswap>((const uint8_t *)in, len, (uint64_t)seed, result);
    PUT_U64<bswap>(result[0], (uint8_t *)out,  0);
    PUT_U64<bswap>(result[1], (uint8_t *)out,  8);
    PUT_U64<bswap>(result[2], (uint8_t *)out, 16);
    PUT_U64<bswap>(result[3], (uint8_t *)out, 24);
}

#endif

//------------------------------------------------------------
#if !defined(IMPORT_CITY)
REGISTER_FAMILY(cityhash,
   $.src_url    = "https://github.com/google/cityhash",
   $.src_status = HashFamilyInfo::SRC_FROZEN
 );

REGISTER_HASH(CityHash_32,
   $.desc       = "Google CityHash32 (modified seeding)",
   $.hash_flags =
         FLAG_HASH_NO_SEED         |
         FLAG_HASH_SMALL_SEED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 32,
   $.verification_LE = 0xEDED9084,
   $.verification_BE = 0x2E033380,
   $.hashfn_native   = City32<false>,
   $.hashfn_bswap    = City32<true>
 );

REGISTER_HASH(CityHash_64,
   $.desc       = "Google CityHash64WithSeed",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x5FABC5C5,
   $.verification_BE = 0x355FC63A,
   $.hashfn_native   = City64<false>,
   $.hashfn_bswap    = City64<true>
 );

  #if 0
REGISTER_HASH(CityHash_128__seed1,
   $.desc       = "Google CityHash128WithSeed (seeded low 64 bits)",
   $.hash_flags =
         FLAG_HASH_XL_SEED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0x305C0D9A,
   $.verification_BE = 0,
   $.hashfn_native   = City128<false, 1>,
   $.hashfn_bswap    = City128<true, 1>
 );

REGISTER_HASH(CityHash_128__seed2,
   $.desc       = "Google CityHash128WithSeed (seeded high 64 bits)",
   $.hash_flags =
         FLAG_HASH_XL_SEED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0x0DB4D383,
   $.verification_BE = 0,
   $.hashfn_native   = City128<false, 2>,
   $.hashfn_bswap    = City128<true, 2>
 );

REGISTER_HASH(CityHash_128__seed3,
   $.desc       = "Google CityHash128WithSeed (seeded low+high 64 bits)",
   $.hash_flags =
         FLAG_HASH_XL_SEED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0xA93EBF71,
   $.verification_BE = 0,
   $.hashfn_native   = City128<false, 3>,
   $.hashfn_bswap    = City128<true, 3>
 );
  #endif

  #if 0
REGISTER_HASH(CityMurmur__seed1,
   $.desc       = "CityMurmur (seeded low 64 bits)",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0x6593FD6D,
   $.verification_BE = 0,
   $.hashfn_native   = CityMurmur_128<false, 1>,
   $.hashfn_bswap    = CityMurmur_128<true, 1>
 );

REGISTER_HASH(CityMurmur__seed2,
   $.desc       = "CityMurmur (seeded high 64 bits)",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0xF1483884,
   $.verification_BE = 0,
   $.hashfn_native   = CityMurmur_128<false, 2>,
   $.hashfn_bswap    = CityMurmur_128<true, 2>
 );

REGISTER_HASH(CityMurmur__seed3,
   $.desc       = "CityMurmur (seeded low+high 64 bits)",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0x6D028510,
   $.verification_BE = 0,
   $.hashfn_native   = CityMurmur_128<false, 3>,
   $.hashfn_bswap    = CityMurmur_128<true, 3>
 );
  #endif

  #if defined(HAVE_X86_64_CRC32C)

REGISTER_HASH(CityHashCrc_128__seed1,
   $.desc       = "Google CityHashCrc128WithSeed (seeded low 64 bits)",
   $.impl       = "hwcrc_x64",
   $.hash_flags =
         FLAG_HASH_XL_SEED         |
         FLAG_HASH_CRC_BASED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0x98C09AB4,
   $.verification_BE = 0xF3DF4378,
   $.hashfn_native   = CityCrc128<false, 1>,
   $.hashfn_bswap    = CityCrc128<true, 1>
 );

REGISTER_HASH(CityHashCrc_128__seed2,
   $.desc       = "Google CityHashCrc128WithSeed (seeded high 64 bits)",
   $.impl       = "hwcrc_x64",
   $.hash_flags =
         FLAG_HASH_XL_SEED         |
         FLAG_HASH_CRC_BASED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0xDA655B2C,
   $.verification_BE = 0x8CF5BD76,
   $.hashfn_native   = CityCrc128<false, 2>,
   $.hashfn_bswap    = CityCrc128<true, 2>
 );

REGISTER_HASH(CityHashCrc_128__seed3,
   $.desc       = "Google CityHashCrc128WithSeed (seeded low+high 64 bits)",
   $.impl       = "hwcrc_x64",
   $.hash_flags =
         FLAG_HASH_XL_SEED         |
         FLAG_HASH_CRC_BASED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0x85279D96,
   $.verification_BE = 0xFBB049D5,
   $.hashfn_native   = CityCrc128<false, 3>,
   $.hashfn_bswap    = CityCrc128<true, 3>
 );

REGISTER_HASH(CityHashCrc_256,
   $.desc       = "Google CityHashCrc256 (with modified seeding)",
   $.impl       = "hwcrc_x64",
   $.hash_flags =
         FLAG_HASH_NO_SEED         |
         FLAG_HASH_SMALL_SEED      |
         FLAG_HASH_CRC_BASED,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64  |
         FLAG_IMPL_ROTATE          |
         FLAG_IMPL_SLOW            |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 256,
   $.verification_LE = 0xB5F99A90,
   $.verification_BE = 0xD5FEE0A0,
   $.hashfn_native   = CityCrc256<false>,
   $.hashfn_bswap    = CityCrc256<true>
 );

  #endif
#endif
/* ===================== longA shared helpers (own code; adapted from the keyfree group) ===================== */
#include <cstdlib>
#include <cmath>
#include <functional>
#include <string>
static uint64_t sm_state;
static uint64_t splitmix64(void) { uint64_t z = (sm_state += UINT64_C(0x9e3779b97f4a7c15));
  z = (z ^ (z >> 30)) * UINT64_C(0xbf58476d1ce4e5b9); z = (z ^ (z >> 27)) * UINT64_C(0x94d049bb133111eb); return z ^ (z >> 31); }
static uint64_t xs[4];
static inline uint64_t rotl_(uint64_t x, int k) { return (x << k) | (x >> (64 - k)); }
static void rng_init(uint64_t s) { sm_state = s; for (int i = 0; i < 4; i++) xs[i] = splitmix64(); }
static inline uint64_t rng64(void) { const uint64_t r = rotl_(xs[1] * 5, 7) * 9, t = xs[1] << 17;
  xs[2] ^= xs[0]; xs[3] ^= xs[1]; xs[1] ^= xs[2]; xs[0] ^= xs[3]; xs[2] ^= t; xs[3] = rotl_(xs[3], 45); return r; }
static std::vector<uint8_t> unhex(const char *h) { std::vector<uint8_t> v; size_t n = strlen(h);
  for (size_t i = 0; i + 1 < n; i += 2) { unsigned b; sscanf(h + i, "%2x", &b); v.push_back((uint8_t)b); } return v; }
static std::string tohex(const uint8_t *p, size_t n) { std::string s; char b[3]; for (size_t i = 0; i < n; i++) { snprintf(b, 3, "%02x", p[i]); s += b; } return s; }
/* 95% Clopper-Pearson interval, closed forms for the two edge cases, bisection otherwise */
static double betainc_cdf(double x, double a, double b) { /* simple numerical integration fallback */
  const int N = 20000; double s = 0, lb = lgamma(a + b) - lgamma(a) - lgamma(b);
  for (int i = 0; i < N; i++) { double t = x * (i + 0.5) / N; s += exp(lb + (a - 1) * log(t) + (b - 1) * log1p(-t)); } return s * x / N; }
static void cp95(uint64_t k, uint64_t n, double *lo, double *hi) {
  if (k == n) { *hi = 1; *lo = pow(0.025, 1.0 / (double)n); if (k == 0) *lo = 0; return; }
  if (k == 0) { *lo = 0; *hi = 1 - pow(0.025, 1.0 / (double)n); return; }
  /* normal approximation (only used for 0<k<n, not needed for key-free rows) */
  double p = (double)k / n, se = sqrt(p * (1 - p) / n); *lo = p - 1.96 * se; *hi = p + 1.96 * se; (void)betainc_cdf; }
typedef std::function<void(const uint8_t *, size_t, uint64_t, uint64_t, uint8_t *)> HFn; /* msg,len,seedA,seedB,out */
static int g_fail = 0;
static void check_verif(const char *name, uint32_t expect) {
  const HashInfo *h = findHash(name); if (!h) { printf("MISSING %s\n", name); g_fail = 1; return; }
  uint32_t v = sm3_verification(h);
  printf("verification %-24s computed %08X expected %08X registered %08X %s\n", name, v, expect, h->verification_LE,
         (v == expect && v == h->verification_LE) ? "OK" : "MISMATCH");
  if (v != expect || v != h->verification_LE) g_fail = 1;
}
static HFn sm3fn(const char *name) { const HashInfo *h = findHash(name); HashFn f = h->hashfn_native;
  return [f](const uint8_t *m, size_t n, uint64_t s, uint64_t, uint8_t *o) { f(m, n, (seed_t)s, o); }; }
/* seed models: 64 = uniform 64-bit, 32 = uniform 32-bit zero-extended, 128 = two independent 64-bit seeds */
static uint64_t run_pair(const char *label, HFn f, unsigned outbytes, int seedbits, const char *mh, const char *mph,
                         unsigned logN, bool control, int cidx = -1) {
  std::vector<uint8_t> a = unhex(mh), b = unhex(mph);
  if (control) { if (cidx < 0) b.back() ^= 0x01; else b[cidx] ^= 0x01; }
  uint64_t N = 1ULL << logN, hits = 0, exs = 0, exs2 = 0; bool have = false; uint8_t oa[64], ob[64], ea[64] = {0};
  for (uint64_t t = 0; t < N; t++) {
    uint64_t s1 = rng64(), s2 = seedbits == 128 ? rng64() : 0; if (seedbits == 32) s1 &= 0xffffffffULL;
    f(a.data(), a.size(), s1, s2, oa); f(b.data(), b.size(), s1, s2, ob);
    if (!memcmp(oa, ob, outbytes)) { hits++; if (!have) { have = true; exs = s1; exs2 = s2; memcpy(ea, oa, outbytes); } }
  }
  double lo, hi; cp95(hits, N, &lo, &hi);
  printf("%-34s %s seed%-3d |m|=%zu |m'|=%zu L=%zu  %llu/%llu  rate=%.6f  95%%CI[%.8f,%.8f]",
         label, control ? "CONTROL" : "PAIR   ", seedbits, a.size(), b.size(), (std::max(a.size(), b.size()) + 7) / 8,
         (unsigned long long)hits, (unsigned long long)N, (double)hits / N, lo, hi);
  if (have) { printf("  ex seed=%016llx", (unsigned long long)exs); if (seedbits == 128) printf(",%016llx", (unsigned long long)exs2);
    printf(" out=%s", tohex(ea, outbytes).c_str()); }
  printf("\n"); fflush(stdout);
  return hits;
}
/* key-free expectation: all N collide; control: none */
static void expect_keyfree(const char *label, HFn f, unsigned ob, int sb, const char *m, const char *mp, unsigned logN, int cidx = -1) {
  uint64_t h = run_pair(label, f, ob, sb, m, mp, logN, false);
  if (h != (1ULL << logN)) { printf("  !! not every seed\n"); g_fail = 1; }
  uint64_t c = run_pair(label, f, ob, sb, m, mp, logN > 16 ? 16 : logN, true, cidx);
  if (c != 0) { printf("  !! control collided\n"); }
}
/* ---- multicollision set checker: every member must equal member 0 on the full output ---- */
#include <algorithm>
#include <unordered_set>
static uint64_t check_family(const char *label, HFn f, unsigned outbytes, int seedbits,
                             const std::vector<std::vector<uint8_t>> &S, unsigned logK) {
  { std::vector<std::vector<uint8_t>> T = S; std::sort(T.begin(), T.end());
    size_t d = std::unique(T.begin(), T.end()) - T.begin();
    size_t mx = 0; for (auto &m : S) mx = std::max(mx, m.size());
    printf("%s: family of %zu messages, %zu distinct, max length %zu bytes (L=%zu)\n", label, S.size(), d, mx, (mx + 7) / 8);
    if (d != S.size()) { printf("  !! duplicate members\n"); g_fail = 1; } }
  uint64_t K = 1ULL << logK, all = 0, lo16 = 0; uint8_t o0[64], o[64]; uint64_t ex = 0; bool have = false; uint8_t eo[64];
  size_t minlargest = S.size();
  for (uint64_t t = 0; t < K; t++) {
    uint64_t s1 = rng64(), s2 = seedbits == 128 ? rng64() : 0; if (seedbits == 32) s1 &= 0xffffffffULL;
    f(S[0].data(), S[0].size(), s1, s2, o0); size_t same = 1, same16 = 1;
    for (size_t i = 1; i < S.size(); i++) { f(S[i].data(), S[i].size(), s1, s2, o);
      if (!memcmp(o, o0, outbytes)) same++; if (!memcmp(o, o0, 2)) same16++; }
    if (same == S.size()) { all++; if (!have) { have = true; ex = s1; memcpy(eo, o0, outbytes); } }
    if (same16 == S.size()) lo16++;
    minlargest = std::min(minlargest, same);
  }
  double lo, hi; cp95(all, K, &lo, &hi);
  printf("  keys where ALL %zu members share the full %u-bit output: %llu/%llu (95%%CI [%.6f,1]); low-16-bit agreement %llu/%llu; min members sharing member 0's value over keys: %zu\n",
         S.size(), outbytes * 8, (unsigned long long)all, (unsigned long long)K, lo, (unsigned long long)lo16, (unsigned long long)K, minlargest);
  if (have) printf("  example key %016llx -> common output %s\n", (unsigned long long)ex, tohex(eo, outbytes).c_str());
  for (int i = 0; i < 3 && i < (int)S.size(); i++) printf("  member[%d] = %s\n", i, tohex(S[i].data(), S[i].size()).c_str());
  printf("  member[%zu] = %s\n", S.size() - 1, tohex(S.back().data(), S.back().size()).c_str());
  if (all != K) g_fail = 1;
  fflush(stdout); return all;
}
/* ===================== longA driver (own code) ===================== */
/* CityHash64 v1.1 / FarmHash64 NA (identical > 64-byte loop), long inputs.
 * Loop body (per 64-byte block, words m0..m7):
 *   v = WeakHashLen32WithSeeds(m0..m3, v.second * k1, x + w.first)
 *   w = WeakHashLen32WithSeeds(m4..m7, z + w.second, y + m2)
 *   Weak(w0,w1,w2,w3, a, b): a += w0; c = a; b = rotr(b + a + w3, 21); a += w1 + w2; b += rotr(a, 44); return (a + w3, b + c)
 * Difference m0 += d, m3 -= d: a and c move by +d, b's first input a + w3 and v.first = a + w3 are unchanged, and
 * v.second moves by rotr(A + d, 44) - rotr(A, 44) + d (A = the running a).  For d = 0x0f0f0f0f0f0f0f0f this is 0
 * for 88.6% of A: the block's output state is then identical.  m1, m2 (used elsewhere in the block) are untouched.
 * Same for the w lane with (m4, m7).  The seed enters only after the loop (Hash64WithSeed = HashLen16(Hash64 - k2,
 * seed)), so a state collision is a collision for every seed, and the condition is a public property of the content.
 * Usage: ./X_long [log2 random contents per length] [rng seed] [log2 seeds per pair check] */
static const uint64_t D0 = UINT64_C(0x0f0f0f0f0f0f0f0f);
static uint64_t ld64le(const uint8_t *p) { uint64_t v = 0; for (int i = 7; i >= 0; i--) v = (v << 8) | p[i]; return v; }
static void st64le(uint8_t *p, uint64_t v) { for (int i = 0; i < 8; i++) p[i] = (uint8_t)(v >> (8 * i)); }
static void apply(uint8_t *m, size_t blockoff, int lane, uint64_t d) {      /* lane 0: words 0,3; lane 1: words 4,7 */
  size_t o0 = blockoff + (lane ? 32 : 0), o3 = o0 + 24;
  st64le(m + o0, ld64le(m + o0) + d); st64le(m + o3, ld64le(m + o3) - d);
}
static int main_common(const char *name, uint64_t (*U)(const uint8_t *, size_t), HFn seeded, int argc, char **argv) {
  unsigned logR = argc > 1 ? atoi(argv[1]) : 14, logS = argc > 3 ? atoi(argv[3]) : 12;
  rng_init(argc > 2 ? strtoull(argv[2], 0, 0) : UINT64_C(0x4c6f6e6744));
  const size_t lens[5] = { 192, 256, 1024, 65536, 1048576 };
  for (int lane = 0; lane < 3; lane++) {
    printf("\n%s: %s, position-independent differential, random content, random block (not block 0, not in the last 64 bytes)\n", name,
           lane == 0 ? "v lane (m0 += d, m3 -= d)" : lane == 1 ? "w lane (m4 += d, m7 -= d)" : "both lanes of one block");
    for (int li = 0; li < 5; li++) {
      size_t n = lens[li], nb = (n - 64) / 64;                      /* usable blocks 1 .. nb-1 */
      uint64_t R = UINT64_C(1) << (n > 100000 ? (logR > 8 ? logR - 6 : logR) : n > 2000 ? (logR > 4 ? logR - 2 : logR) : logR), hit = 0;
      std::vector<uint8_t> A(n), B(n);
      for (uint64_t r = 0; r < R; r++) {
        for (auto &x : A) x = (uint8_t)rng64(); B = A;
        size_t j = 1 + rng64() % (nb - 1), off = 64 * j;
        if (lane != 1) apply(B.data(), off, 0, D0);
        if (lane != 0) apply(B.data(), off, 1, D0);
        hit += U(A.data(), n) == U(B.data(), n);
      }
      double lo, hi, p = (double)hit / R, se = sqrt(p * (1 - p) / R);
      lo = p - 1.96 * se; hi = p + 1.96 * se;
      printf("  len %8zu (L=%6zu): %llu/%llu random contents collide (unseeded 64-bit) = %.4f  95%%CI [%.4f, %.4f]  (predicted %.4f)\n",
             n, (n + 7) / 8, (unsigned long long)hit, (unsigned long long)R, p, lo, hi, lane == 2 ? 0.885758 * 0.885758 : 0.885758);
    }
  }
  /* explicit pair at 1 KiB + seeded check, and a 2^16 family with known content */
  { size_t n = 1024; std::vector<uint8_t> A(n); for (auto &x : A) x = (uint8_t)rng64();
    std::vector<uint8_t> B = A; size_t off = 64 * 7; apply(B.data(), off, 0, D0);
    while (U(A.data(), n) != U(B.data(), n)) { for (auto &x : A) x = (uint8_t)rng64(); B = A; apply(B.data(), off, 0, D0); }
    uint64_t N = UINT64_C(1) << logS, hits = 0, ex = 0; uint8_t oa[8], ob[8], eo[8];
    for (uint64_t t = 0; t < N; t++) { uint64_t sd = rng64(); seeded(A.data(), n, sd, 0, oa); seeded(B.data(), n, sd, 0, ob);
      if (!memcmp(oa, ob, 8)) { if (!hits) { ex = sd; memcpy(eo, oa, 8); } hits++; } }
    printf("\nexplicit 1024-byte pair (block 7, v lane): WithSeed collisions %llu/%llu; e.g. seed %016llx -> %s\n  m  = %s\n  m' = %s\n",
           (unsigned long long)hits, (unsigned long long)N, (unsigned long long)ex, tohex(eo, 8).c_str(), tohex(A.data(), n).c_str(), tohex(B.data(), n).c_str());
    if (hits != N) g_fail = 1; }
  { size_t n = 1024 + 40; std::vector<uint8_t> A(n); for (auto &x : A) x = (uint8_t)rng64();
    std::vector<std::pair<size_t, int>> slots;                          /* (block offset, lane) whose condition holds */
    size_t tested = 0;
    for (size_t j = 1; 64 * (j + 1) <= n - 64 && slots.size() < 16; j++) for (int lane = 0; lane < 2 && slots.size() < 16; lane++) {
      std::vector<uint8_t> B = A; apply(B.data(), 64 * j, lane, D0); tested++;
      if (U(A.data(), n) == U(B.data(), n)) slots.push_back({64 * j, lane}); }
    printf("\nfamily at %zu bytes: %zu of the first %zu slots satisfy the condition for this content (public check)\n", n, slots.size(), tested);
    if (slots.size() == 16) {
      std::vector<std::vector<uint8_t>> F;
      for (uint32_t i = 0; i < 65536; i++) { std::vector<uint8_t> B = A; for (int s = 0; s < 16; s++) if ((i >> s) & 1) apply(B.data(), slots[s].first, slots[s].second, D0); F.push_back(B); }
      size_t same = 0; uint64_t u0 = U(F[0].data(), n); for (auto &m : F) same += U(m.data(), n) == u0;
      printf("  unseeded Hash64 equal for %zu/65536 members\n", same);
      check_family(name, seeded, 8, 64, F, logS > 8 ? 8 : logS);
      /* random-content version: the same 16 slot positions on fresh random content, probability that the whole cube collides */
      uint64_t R = 256, full = 0;
      for (uint64_t r = 0; r < R; r++) { std::vector<uint8_t> C(n); for (auto &x : C) x = (uint8_t)rng64(); uint64_t c0 = U(C.data(), n); int ok = 1;
        for (int s = 0; s < 16 && ok; s++) { std::vector<uint8_t> Cc = C; apply(Cc.data(), slots[s].first, slots[s].second, D0); ok = U(Cc.data(), n) == c0; }
        full += ok; }
      printf("  fresh random content, same 16 slots: all 16 single-slot conditions hold (=> whole 2^16 cube collides) for %llu/%llu contents (predicted 0.886^16 = %.3f)\n",
             (unsigned long long)full, (unsigned long long)R, pow(0.885758, 16));
    } else g_fail = 1;
  }
  printf(g_fail ? "RESULT: FAIL\n" : "RESULT: PASS\n"); return g_fail;
}
static uint64_t Ucity(const uint8_t *p, size_t n) { return CityHash64<false>(p, n); }
int main(int argc, char **argv) {
  check_verif("CityHash_64", 0x5FABC5C5); if (g_fail) return 1;
  return main_common("CityHash64 v1.1 (CityHash64WithSeed)", Ucity, sm3fn("CityHash_64"), argc, argv);
}
