/* rapidhash-v3: adapted for this package from paper_rows/rapid_v3_port.h (validated verbatim SMHasher3 bodies) and collision_driver.cpp.
 * The supplied independent verifier/driver is credited here;
 * adaptations: standalone C11 driver, explicit LE loads, asserted
 * SMHasher3 values and witnesses, single-thread deterministic sampling. */
// Generated by prepare_rapid.py; hash body copied verbatim from ref/rapidhash.cpp.
/*
 * rapidhash - Very fast, high quality, platform independant hashing algorithm.
 * Copyright (C) 2025 Nicolas De Carli
 * Copyright (C) 2025 Frank J. T. Wojcik
 *
 * Based on 'wyhash', by Wang Yi <godspeed_china@yeah.net>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * You can contact the author at:
 *   - rapidhash source repository: https://github.com/Nicoshev/rapidhash
 */
#include <stdint.h>
#include <stddef.h>
#include <string.h>

static uint64_t load_le(const uint8_t *p, unsigned n) {
    uint64_t x=0; for(unsigned i=0;i<n;i++) x|=(uint64_t)p[i]<<(8*i); return x;
}
#define likely(x) (x)
#define isProtected 0
#define unrolled 1
/*
 *  Read functions.
 */
static inline uint64_t rapid_read64( const uint8_t * p ) {
    return load_le(p,8);
}

static inline uint64_t rapid_read32( const uint8_t * p ) {
    return load_le(p,4);
}

/*
 *  64*64 -> 128bit multiply function.
 *
 *  @param A  Address of 64-bit number.
 *  @param B  Address of 64-bit number.
 *
 *  Calculates 128-bit C = A * B.
 *
 *  When isProtected is false:
 *  Overwritres A contents with C's low 64 bits.
 *  Overwritres B contents with C's high 64 bits.
 *
 *  When isProtected is true:
 *  Xors and overwrites A contents with C's low 64 bits.
 *  Xors and overwrites B contents with C's high 64 bits.
 */
static inline void rapid_mum( uint64_t * A, uint64_t * B ) {
    uint64_t rlo, rhi;

    __uint128_t product=(__uint128_t)*A * *B; rlo=(uint64_t)product; rhi=(uint64_t)(product>>64);
    if (isProtected) {
        *A ^= rlo; *B ^= rhi;
    } else {
        *A  = rlo; *B  = rhi;
    }
}

/*
 *  Multiply and xor mix function.
 *
 *  @param A  64-bit number.
 *  @param B  64-bit number.
 *
 *  Calculates 128-bit C = A * B.
 *  Returns 64-bit xor between high and low 64 bits of C.
 */
static inline uint64_t rapid_mix( uint64_t A, uint64_t B ) {
    rapid_mum(&A, &B);
    return A ^ B;
}

/*
 *  Default secret parameters.
 */
static const uint64_t rapid_secret[8] = {
    UINT64_C(0x2d358dccaa6c78a5), UINT64_C(0x8bb84b93962eacc9),
    UINT64_C(0x4b33a62ed433d4a3), UINT64_C(0x4d5a2da51de1aa47),
    UINT64_C(0xa0761d6478bd642f), UINT64_C(0xe7037ed1a0b428db),
    UINT64_C(0x90ed1765281c388c), UINT64_C(0xaaaaaaaaaaaaaaaa),
};

/*
 *  rapidhash main function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *  @param secrets Array of 8 64-bit secrets used to alter hash result predictably.
 *
 *  Returns a 64-bit hash.
 */
static inline uint64_t rapidhash( const void * key, size_t len, uint64_t seed, const uint64_t * secrets ) {
    const uint8_t * p = (const uint8_t *)key;
    size_t          i = len;
    uint64_t        a, b;

    seed ^= rapid_mix(seed ^ secrets[2], secrets[1]);

    if (likely(len <= 16)) {
        if (len >= 4) {
            seed ^= len;
            if (len >= 8) {
                const uint8_t * plast = p + len - 8;
                a = rapid_read64(p    );
                b = rapid_read64(plast);
            } else {
                const uint8_t * plast = p + len - 4;
                a = rapid_read32(p    );
                b = rapid_read32(plast);
            }
        } else if (likely(len > 0)) {
            a = (((uint64_t)p[0]) << 45) | p[len - 1];
            b = p[len >> 1];
        } else {
            a = b = 0;
        }
    } else {
        if (len > 112) {
            uint64_t see1 = seed, see2 = seed;
            uint64_t see3 = seed, see4 = seed;
            uint64_t see5 = seed, see6 = seed;
            if (unrolled) {
                while (i > 224) {
                    seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                            rapid_read64(p +   8) ^ seed);
                    see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                            rapid_read64(p +  24) ^ see1);
                    see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                            rapid_read64(p +  40) ^ see2);
                    see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                            rapid_read64(p +  56) ^ see3);
                    see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                            rapid_read64(p +  72) ^ see4);
                    see5 = rapid_mix(rapid_read64(p +  80) ^ secrets[5],
                            rapid_read64(p +  88) ^ see5);
                    see6 = rapid_mix(rapid_read64(p +  96) ^ secrets[6],
                            rapid_read64(p + 104) ^ see6);
                    seed = rapid_mix(rapid_read64(p + 112) ^ secrets[0],
                            rapid_read64(p + 120) ^ seed);
                    see1 = rapid_mix(rapid_read64(p + 128) ^ secrets[1],
                            rapid_read64(p + 136) ^ see1);
                    see2 = rapid_mix(rapid_read64(p + 144) ^ secrets[2],
                            rapid_read64(p + 152) ^ see2);
                    see3 = rapid_mix(rapid_read64(p + 160) ^ secrets[3],
                            rapid_read64(p + 168) ^ see3);
                    see4 = rapid_mix(rapid_read64(p + 176) ^ secrets[4],
                            rapid_read64(p + 184) ^ see4);
                    see5 = rapid_mix(rapid_read64(p + 192) ^ secrets[5],
                            rapid_read64(p + 200) ^ see5);
                    see6 = rapid_mix(rapid_read64(p + 208) ^ secrets[6],
                            rapid_read64(p + 216) ^ see6);
                    p   += 224; i -= 224;
                }
                if (i > 112) {
                    seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                            rapid_read64(p +   8) ^ seed);
                    see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                            rapid_read64(p +  24) ^ see1);
                    see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                            rapid_read64(p +  40) ^ see2);
                    see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                            rapid_read64(p +  56) ^ see3);
                    see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                            rapid_read64(p +  72) ^ see4);
                    see5 = rapid_mix(rapid_read64(p +  80) ^ secrets[5],
                            rapid_read64(p +  88) ^ see5);
                    see6 = rapid_mix(rapid_read64(p +  96) ^ secrets[6],
                            rapid_read64(p + 104) ^ see6);
                    p   += 112; i -= 112;
                }
            } else {
                do {
                    seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                            rapid_read64(p +   8) ^ seed);
                    see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                            rapid_read64(p +  24) ^ see1);
                    see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                            rapid_read64(p +  40) ^ see2);
                    see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                            rapid_read64(p +  56) ^ see3);
                    see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                            rapid_read64(p +  72) ^ see4);
                    see5 = rapid_mix(rapid_read64(p +  80) ^ secrets[5],
                            rapid_read64(p +  88) ^ see5);
                    see6 = rapid_mix(rapid_read64(p +  96) ^ secrets[6],
                            rapid_read64(p + 104) ^ see6);
                    p   += 112; i -= 112;
                } while (i > 112);
            }
            seed ^= see1;
            see2 ^= see3;
            see4 ^= see5;
            seed ^= see6;
            see2 ^= see4;
            seed ^= see2;
        }
        if (i > 16) {
            seed = rapid_mix(rapid_read64(p) ^ secrets[2],
                    rapid_read64(p + 8) ^ seed);
            if (i > 32) {
                seed = rapid_mix(rapid_read64(p + 16) ^ secrets[2],
                        rapid_read64(p + 24) ^ seed);
                if (i > 48) {
                    seed = rapid_mix(rapid_read64(p + 32) ^ secrets[1],
                            rapid_read64(p + 40) ^ seed);
                    if (i > 64) {
                        seed = rapid_mix(rapid_read64(p + 48) ^ secrets[1],
                                rapid_read64(p + 56) ^ seed);
                        if (i > 80) {
                            seed = rapid_mix(rapid_read64(p + 64) ^ secrets[2],
                                    rapid_read64(p + 72) ^ seed);
                            if (i > 96) {
                                seed = rapid_mix(rapid_read64(p + 80) ^ secrets[1],
                                        rapid_read64(p + 88) ^ seed);
                            }
                        }
                    }
                }
            }
        }
        a = rapid_read64(p + i - 16) ^ i;
        b = rapid_read64(p + i -  8);
    }
    a ^= secrets[1];
    b ^= seed;
    rapid_mum(&a, &b);
    return rapid_mix(a ^ secrets[7], b ^ secrets[1] ^ i);
}

/*
 *  rapidhashMicro main function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *  @param secrets Array of 8 64-bit secrets used to alter hash result predictably.
 *                 Note that secrets[5] and secrets[6] are unused here.
 *
 *  Returns a 64-bit hash.
 */
static inline uint64_t rapidhashMicro( const void * key, size_t len, uint64_t seed, const uint64_t * secrets ) {
    const uint8_t * p = (const uint8_t *)key;
    size_t          i = len;
    uint64_t        a, b;

    seed ^= rapid_mix(seed ^ secrets[2], secrets[1]);

    if (likely(len <= 16)) {
        if (len >= 4) {
            seed ^= len;
            if (len >= 8) {
                const uint8_t * plast = p + len - 8;
                a = rapid_read64(p    );
                b = rapid_read64(plast);
            } else {
                const uint8_t * plast = p + len - 4;
                a = rapid_read32(p    );
                b = rapid_read32(plast);
            }
        } else if (likely(len > 0)) {
            a = (((uint64_t)p[0]) << 45) | p[len - 1];
            b = p[len >> 1];
        } else {
            a = b = 0;
        }
    } else {
        if (len > 80) {
            uint64_t see1 = seed, see2 = seed;
            uint64_t see3 = seed, see4 = seed;
            do {
                seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                        rapid_read64(p +   8) ^ seed);
                see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                        rapid_read64(p +  24) ^ see1);
                see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                        rapid_read64(p +  40) ^ see2);
                see3 = rapid_mix(rapid_read64(p +  48) ^ secrets[3],
                        rapid_read64(p +  56) ^ see3);
                see4 = rapid_mix(rapid_read64(p +  64) ^ secrets[4],
                        rapid_read64(p +  72) ^ see4);
                p   += 80; i -= 80;
            } while (i > 80);
            seed ^= see1;
            see2 ^= see3;
            seed ^= see4;
            seed ^= see2;
        }
        if (i > 16) {
            seed = rapid_mix(rapid_read64(p) ^ secrets[2],
                    rapid_read64(p + 8) ^ seed);
            if (i > 32) {
                seed = rapid_mix(rapid_read64(p + 16) ^ secrets[2],
                        rapid_read64(p + 24) ^ seed);
                if (i > 48) {
                    seed = rapid_mix(rapid_read64(p + 32) ^ secrets[1],
                            rapid_read64(p + 40) ^ seed);
                    if (i > 64) {
                        seed = rapid_mix(rapid_read64(p + 48) ^ secrets[1],
                                rapid_read64(p + 56) ^ seed);
                    }
                }
            }
        }
        a = rapid_read64(p + i - 16) ^ i;
        b = rapid_read64(p + i -  8);
    }
    a ^= secrets[1];
    b ^= seed;
    rapid_mum(&a, &b);
    return rapid_mix(a ^ secrets[7], b ^ secrets[1] ^ i);
}

/*
 *  rapidhashNano main function.
 *
 *  @param key     Buffer to be hashed.
 *  @param len     @key length, in bytes.
 *  @param seed    64-bit seed used to alter the hash result predictably.
 *  @param secrets Array of 8 64-bit secrets used to alter hash result predictably.
 *                 Note that secrets[3] through secrets[6] are unused here.
 *
 *  Returns a 64-bit hash.
 */
static inline uint64_t rapidhashNano( const void * key, size_t len, uint64_t seed, const uint64_t * secrets ) {
    const uint8_t * p = (const uint8_t *)key;
    size_t          i = len;
    uint64_t        a, b;

    seed ^= rapid_mix(seed ^ secrets[2], secrets[1]);

    if (likely(len <= 16)) {
        if (len >= 4) {
            seed ^= len;
            if (len >= 8) {
                const uint8_t * plast = p + len - 8;
                a = rapid_read64(p    );
                b = rapid_read64(plast);
            } else {
                const uint8_t * plast = p + len - 4;
                a = rapid_read32(p    );
                b = rapid_read32(plast);
            }
        } else if (likely(len > 0)) {
            a = (((uint64_t)p[0]) << 45) | p[len - 1];
            b = p[len >> 1];
        } else {
            a = b = 0;
        }
    } else {
        if (len > 48) {
            uint64_t see1 = seed, see2 = seed;
            do {
                seed = rapid_mix(rapid_read64(p      ) ^ secrets[0],
                        rapid_read64(p +   8) ^ seed);
                see1 = rapid_mix(rapid_read64(p +  16) ^ secrets[1],
                        rapid_read64(p +  24) ^ see1);
                see2 = rapid_mix(rapid_read64(p +  32) ^ secrets[2],
                        rapid_read64(p +  40) ^ see2);
                p   += 48; i -= 48;
            } while (i > 48);
            seed ^= see1;
            seed ^= see2;
        }
        if (i > 16) {
            seed = rapid_mix(rapid_read64(p) ^ secrets[2],
                    rapid_read64(p + 8) ^ seed);
            if (i > 32) {
                seed = rapid_mix(rapid_read64(p + 16) ^ secrets[2],
                        rapid_read64(p + 24) ^ seed);
            }
        }
        a = rapid_read64(p + i - 16) ^ i;
        b = rapid_read64(p + i -  8);
    }
    a ^= secrets[1];
    b ^= seed;
    rapid_mum(&a, &b);
    return rapid_mix(a ^ secrets[7], b ^ secrets[1] ^ i);
}

//-----------------------------------------------------------------------------

/* Reproduction driver: Copyright (c) 2026 Thomas Dybdahl Ahle, MIT.
 * The implementation's separate attribution/license is retained above.
 * One process, one thread; no dependencies outside this file. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <errno.h>
#include <math.h>

typedef struct { uint64_t lo, hi; } Result;
typedef Result (*Hash)(const uint8_t *, size_t, uint64_t);
typedef struct {
    const char *name; Hash hash; int bits, seed_bits, canonical;
    uint32_t verification;
} Variant;
typedef struct {
    const char *name, *a, *b;
    int variant, every_seed;
    uint64_t seed;
    Result expected;
} Pair;

#define HAS_STRUCTURE_CHECKS 0
/* Key models.  "default": one uniform 64-bit API seed per trial with the shipped public secret
 * words (the historical experiment).  "random-secret": one uniform 64-bit seed and 8
 * independent uniform 64-bit secret words per trial, passed to the hash's secret parameter; this is
 * the strongest key model the API supports and the model the article scores. */
#define NSECRET 8
static const uint64_t *active_secret = rapid_secret;
static Result hash_0(const uint8_t *p, size_t n, uint64_t seed) { return (Result){rapidhash(p,n,seed,active_secret),0}; }
static Result hash_1(const uint8_t *p, size_t n, uint64_t seed) { return (Result){rapidhashMicro(p,n,seed,active_secret),0}; }
static Result hash_2(const uint8_t *p, size_t n, uint64_t seed) { return (Result){rapidhashNano(p,n,seed,active_secret),0}; }
static const Variant variants[] = {
    {"rapidhash v3",hash_0,64,64,0,0x1FDC65EE},
    {"rapidhash v3 micro",hash_1,64,64,0,0x6F183D61},
    {"rapidhash v3 nano",hash_2,64,64,0,0x2C200DC7},
};
static const Pair pairs[] = {
    {"rapid3_32","9bd4604137366abec688a63706aa4a2188d35499de169df633e0964e8c04600c","642b9fbec8c99541397759c8f955b5de88d35499de169df633e0964e8c04600c",0,0,UINT64_C(0x3187ae8a8617e034),{UINT64_C(0xa7ee6375a78a86f0),UINT64_C(0x0)}},
    {"rapid3_48","9bd4604137366abec688a63706aa4a2188d35499de169df633e0964e8c04600c48c651edae76208e840fc51f1cccbb02","642b9fbec8c99541397759c8f955b5de88d35499de169df633e0964e8c04600c48c651edae76208e840fc51f1cccbb02",0,0,UINT64_C(0x3187ae8a8617e034),{UINT64_C(0xb52b5b5759f1d08a),UINT64_C(0x0)}},
    {"rapid3_micro_32","9bd4604137366abec688a63706aa4a2188d35499de169df633e0964e8c04600c","642b9fbec8c99541397759c8f955b5de88d35499de169df633e0964e8c04600c",1,0,UINT64_C(0x3187ae8a8617e034),{UINT64_C(0xa7ee6375a78a86f0),UINT64_C(0x0)}},
    {"rapid3_micro_48","9bd4604137366abec688a63706aa4a2188d35499de169df633e0964e8c04600c48c651edae76208e840fc51f1cccbb02","642b9fbec8c99541397759c8f955b5de88d35499de169df633e0964e8c04600c48c651edae76208e840fc51f1cccbb02",1,0,UINT64_C(0x3187ae8a8617e034),{UINT64_C(0xb52b5b5759f1d08a),UINT64_C(0x0)}},
    {"rapid3_nano_32","9bd4604137366abec688a63706aa4a2188d35499de169df633e0964e8c04600c","642b9fbec8c99541397759c8f955b5de88d35499de169df633e0964e8c04600c",2,0,UINT64_C(0x3187ae8a8617e034),{UINT64_C(0xa7ee6375a78a86f0),UINT64_C(0x0)}},
    {"rapid3_nano_48","9bd4604137366abec688a63706aa4a2188d35499de169df633e0964e8c04600c48c651edae76208e840fc51f1cccbb02","642b9fbec8c99541397759c8f955b5de88d35499de169df633e0964e8c04600c48c651edae76208e840fc51f1cccbb02",2,0,UINT64_C(0x3187ae8a8617e034),{UINT64_C(0xb52b5b5759f1d08a),UINT64_C(0x0)}},
};
typedef struct { const char *name; int pair; uint64_t seed, secret[NSECRET]; Result expected; } KeyWitness;
static const uint64_t *const default_secret = rapid_secret;
/* Random-secret witnesses from the 2026-09-19 measurement (records/witness-searches/random-secret/rapid3/verify/logs/10_pairA_random_2p30.txt):
 * seed and eight secret words through rapidhash_internal; both 32-byte messages of pair A hash to d832bac31b8fda6c.
 * Standard, micro and nano share the 17..48-byte path, so the same key is a witness for all three 32-byte cases. */
static const KeyWitness key_witnesses[] = {
    {"rapid3_32",0,UINT64_C(0x27d3b5addafed424),{UINT64_C(0x8201394795b91ef9),UINT64_C(0xbc80d672c2c377f6),UINT64_C(0x5afd557e26c19903),UINT64_C(0xa3a9fab4fc0d80e2),UINT64_C(0x5108fe3feb9bd088),UINT64_C(0x6742ee43cec628a4),UINT64_C(0x2267c78c10996237),UINT64_C(0xd96b61ed51f62b33)},{UINT64_C(0xd832bac31b8fda6c),UINT64_C(0x0)}},
    {"rapid3_micro_32",2,UINT64_C(0x27d3b5addafed424),{UINT64_C(0x8201394795b91ef9),UINT64_C(0xbc80d672c2c377f6),UINT64_C(0x5afd557e26c19903),UINT64_C(0xa3a9fab4fc0d80e2),UINT64_C(0x5108fe3feb9bd088),UINT64_C(0x6742ee43cec628a4),UINT64_C(0x2267c78c10996237),UINT64_C(0xd96b61ed51f62b33)},{UINT64_C(0xd832bac31b8fda6c),UINT64_C(0x0)}},
    {"rapid3_nano_32",4,UINT64_C(0x27d3b5addafed424),{UINT64_C(0x8201394795b91ef9),UINT64_C(0xbc80d672c2c377f6),UINT64_C(0x5afd557e26c19903),UINT64_C(0xa3a9fab4fc0d80e2),UINT64_C(0x5108fe3feb9bd088),UINT64_C(0x6742ee43cec628a4),UINT64_C(0x2267c78c10996237),UINT64_C(0xd96b61ed51f62b33)},{UINT64_C(0xd832bac31b8fda6c),UINT64_C(0x0)}},
};
static int structure_checks(void) { return 1; }

static uint64_t rng_state[4];
static uint64_t rng_rot(uint64_t x, unsigned n) { return x<<n | x>>(64-n); }
static uint64_t splitmix(uint64_t *s) {
    uint64_t z=(*s+=UINT64_C(0x9e3779b97f4a7c15));
    z=(z^(z>>30))*UINT64_C(0xbf58476d1ce4e5b9);
    z=(z^(z>>27))*UINT64_C(0x94d049bb133111eb);
    return z^(z>>31);
}
static void rng_init(uint64_t s) { for(int i=0;i<4;i++) rng_state[i]=splitmix(&s); }
static uint64_t rng_next(void) {
    uint64_t *s=rng_state, r=rng_rot(s[1]*5,7)*9, t=s[1]<<17;
    s[2]^=s[0]; s[3]^=s[1]; s[1]^=s[2]; s[0]^=s[3]; s[2]^=t; s[3]=rng_rot(s[3],45);
    return r;
}
static int equal(Result a, Result b) { return a.lo==b.lo && a.hi==b.hi; }
static void print_result(Result h, int bits) {
    if(bits==128) printf("%016" PRIx64, h.hi);
    if(bits==32) printf("%08" PRIx32, (uint32_t)h.lo);
    else printf("%016" PRIx64, h.lo);
}
static void encode(uint8_t *p, Result h, const Variant *v) {
    int n=v->bits/8;
    for(int i=0;i<n;i++) {
        /* XXH3's SMHasher3 wrapper emits canonical big-endian output,
         * high half first at 128 bits; other registrations emit LE. */
        int j=v->canonical ? n-1-i : i;
        p[i]=(uint8_t)((j<8?h.lo:h.hi) >> (8*(j%8)));
    }
}
static uint32_t verification(const Variant *v) {
    uint8_t key[256]={0}, hashes[4096], final[16];
    int bytes=v->bits/8;
    for(int i=0;i<256;i++) {
        encode(hashes+i*bytes,v->hash(key,(size_t)i,(uint64_t)(256-i)),v);
        key[i]=(uint8_t)i;
    }
    encode(final,v->hash(hashes,(size_t)256*bytes,0),v);
    return (uint32_t)final[0] | (uint32_t)final[1]<<8 | (uint32_t)final[2]<<16 | (uint32_t)final[3]<<24;
}
static size_t decode(const char *s, uint8_t *out) {
    size_t n=strlen(s)/2;
    if(strlen(s)%2 || n>512) { fputs("invalid built-in pair\n",stderr); exit(1); }
    for(size_t i=0;i<n;i++) {
        unsigned x;
        if(sscanf(s+2*i,"%2x",&x)!=1) exit(1);
        out[i]=(uint8_t)x;
    }
    return n;
}
static uint64_t argument(const char *s, uint64_t max) {
    char *end;
    if(!*s || *s=='-' || *s=='+' || *s==' ' || *s=='\t') goto bad;
    errno=0;
    uint64_t x=strtoull(s,&end,0);
    if(errno || *end || x>max) goto bad;
    return x;
bad: fputs("invalid argument\n",stderr); exit(2);
}
int main(int argc, char **argv) {
    if(argc>4) { fprintf(stderr,"usage: %s [log2 N (0..40), default 20] [rng seed, default 1] [default|random-secret]\n",argv[0]); return 2; }
    unsigned lg=argc>1?(unsigned)argument(argv[1],40):20;
    uint64_t rseed=argc>2?argument(argv[2],UINT64_MAX):1;
    int random_secret=0;
    if(argc>3) {
        if(!strcmp(argv[3],"random-secret")) random_secret=1;
        else if(strcmp(argv[3],"default")) { fputs("key model must be default or random-secret\n",stderr); return 2; }
    }
    uint64_t n=UINT64_C(1)<<lg;
    for(size_t i=0;i<sizeof(variants)/sizeof(*variants);i++) {
        uint32_t got=verification(&variants[i]);
        printf("SMHasher3 %s: %08" PRIX32 " expected %08" PRIX32 " %s\n",variants[i].name,got,variants[i].verification,got==variants[i].verification?"PASS":"FAIL");
        if(got!=variants[i].verification) return 1;
    }
    if(!structure_checks()) { fputs("structural assertion failed\n",stderr); return 1; }
    if(HAS_STRUCTURE_CHECKS) puts("structural checks PASS");
    else puts("SMHasher3 checks complete; recorded output assertions follow");
    printf("key model: %s\n",random_secret?"uniform 64-bit seed and eight uniform 64-bit secret words per trial (576 bits), rapidhash_internal(key,len,seed,secret)":"uniform 64-bit API seed; shipped public secret words (default)");
    for(size_t i=0;i<sizeof(pairs)/sizeof(*pairs);i++) {
        const Pair *p=&pairs[i]; const Variant *v=&variants[p->variant];
        uint8_t a[512],b[512]; size_t na=decode(p->a,a),nb=decode(p->b,b);
        if(na==nb && !memcmp(a,b,na)) return 1;
        printf("\n%s / %s\nM (%zu B) = %s\nM' (%zu B) = %s\n",p->name,v->name,na,p->a,nb,p->b);
        Result ha=v->hash(a,na,p->seed), hb=v->hash(b,nb,p->seed);
        printf("recorded colliding seed %016" PRIx64 ": H(M)=",p->seed); print_result(ha,v->bits);
        printf(" H(M')="); print_result(hb,v->bits); puts("");
        if(!equal(ha,hb) || !equal(ha,p->expected)) { fputs("recorded output mismatch\n",stderr); return 1; }
        if(random_secret) for(size_t k=0;k<sizeof(key_witnesses)/sizeof(*key_witnesses);k++) {
            const KeyWitness *w=&key_witnesses[k]; if(w->pair!=(int)i) continue;
            active_secret=w->secret;
            ha=v->hash(a,na,w->seed); hb=v->hash(b,nb,w->seed);
            active_secret=default_secret;
            printf("recorded colliding key (random-secret model) seed %016" PRIx64 " secret",w->seed);
            for(int j=0;j<NSECRET;j++) printf("%c%016" PRIx64,j?',':' ',w->secret[j]);
            printf(": H(M)="); print_result(ha,v->bits); printf(" H(M')="); print_result(hb,v->bits); puts("");
            if(!equal(ha,hb) || !equal(ha,w->expected)) { fputs("recorded random-secret output mismatch\n",stderr); return 1; }
        }
        uint64_t count=0, first_seed=0, first_secret[NSECRET]={0}, words[NSECRET]; Result first={0,0};
        rng_init(rseed); /* Same stream per pair, deliberately correlated. */
        for(uint64_t t=0;t<n;t++) {
            uint64_t seed=rng_next();
            if(v->seed_bits==32) seed=(uint32_t)seed;
            if(random_secret) { for(int j=0;j<NSECRET;j++) words[j]=rng_next(); active_secret=words; }
            ha=v->hash(a,na,seed); hb=v->hash(b,nb,seed);
            if(equal(ha,hb)) {
                if(!count) { first_seed=seed; first=ha; memcpy(first_secret,words,sizeof first_secret); }
                count++;
            } else if(p->every_seed) {
                fprintf(stderr,"non-colliding seed %016" PRIx64 " violates every-seed claim\n",seed); return 1;
            }
        }
        active_secret=default_secret;
        double rate=(double)count/(double)n;
        printf("collisions = %" PRIu64 " / %" PRIu64 "; rate = %.12g",count,n,rate);
        if(count) printf("; log2(rate) = %.6f; sampled score = %.6f",log2(rate),log2((double)(((na>nb?na:nb)+7)/8))-log2(rate));
        else printf("; no rate/score estimate from zero hits (resolution 1/N)");
        puts("");
        if(count) {
            printf("first sampled colliding seed %016" PRIx64,first_seed);
            if(random_secret) { printf(" secret"); for(int j=0;j<NSECRET;j++) printf("%c%016" PRIx64,j?',':' ',first_secret[j]); }
            printf(": H(M)=H(M')="); print_result(first,v->bits); puts("");
        }
        else puts("no sampled collision; the recorded witness above was checked separately");
    }
    return 0;
}
