# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# compile C with /usr/bin/cc
# compile CXX with /usr/bin/c++
C_DEFINES = -DHAVE_THREADS

C_INCLUDES = -I<scratch>/codex/chainhash-m2-adjacent/build/include -I<scratch>/codex/chainhash-m2-adjacent/smhasher3/include/hashlib -I<scratch>/codex/chainhash-m2-adjacent/smhasher3/include/common -isystem /opt/homebrew/opt/openssl@3/include

C_FLAGSarm64 = -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

C_FLAGS = -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

CXX_DEFINES = -DHAVE_THREADS

CXX_INCLUDES = -I<scratch>/codex/chainhash-m2-adjacent/build/include -I<scratch>/codex/chainhash-m2-adjacent/smhasher3/include/hashlib -I<scratch>/codex/chainhash-m2-adjacent/smhasher3/include/common -isystem /opt/homebrew/opt/openssl@3/include

CXX_FLAGSarm64 = -Xclang -target-feature -Xclang +aes -O3 -march=native -g -ggdb3 -Wall -Wextra -Wvla -Wpedantic       -Wno-unused-function -Wno-unknown-pragmas -DNDEBUG -std=c++11 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

CXX_FLAGS = -Xclang -target-feature -Xclang +aes -O3 -march=native -g -ggdb3 -Wall -Wextra -Wvla -Wpedantic       -Wno-unused-function -Wno-unknown-pragmas -DNDEBUG -std=c++11 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

# Custom include directories: CMakeFiles/SMHasher3Hashlib.dir/lib/Hashinfo.cpp.o_INCLUDE_DIRECTORIES = <scratch>/codex/chainhash-m2-adjacent/smhasher3/util

# Custom flags: CMakeFiles/SMHasher3Hashlib.dir/hashes/halftimehash.cpp.o_FLAGS = -flax-vector-conversions -Wno-ignored-attributes

# Custom flags: CMakeFiles/SMHasher3Hashlib.dir/hashes/floppsyhash.cpp.o_FLAGS = -ffp-contract=off

# Custom flags: CMakeFiles/SMHasher3Hashlib.dir/hashes/vendor/umash/umash_impl.c.o_FLAGS = -O3 -std=c11 -march=armv8-a+crypto

# Custom flags: CMakeFiles/SMHasher3Hashlib.dir/hashes/vendor/umash/umash_bswap.c.o_FLAGS = -O3 -std=c11 -march=armv8-a+crypto

# Custom flags: CMakeFiles/SMHasher3Hashlib.dir/hashes/vendor/clhash/clhash.c.o_FLAGS = -O3 -std=c11 -march=armv8-a+crypto

# Custom flags: CMakeFiles/SMHasher3Hashlib.dir/hashes/vendor/clhash/clhash_bswap.c.o_FLAGS = -O3 -std=c11 -march=armv8-a+crypto

