/* Single-file program generated from: SMHasher3 platform header + include/hashlib/Mathmult.h,
 * SMHasher3 hashes/mum_mir.cpp (verbatim, #include lines removed), and the key-free driver below. */
/* === SMHasher3 platform/Platform.h (generated form, clock+thread parts removed) === */
/*
 * DO NOT EDIT THIS FILE
 *
 * It is generated by CMake during build configuration.
 * See <smhasher3>/platform/functions.cmake
 * for documentation on how and why this is generated.
 */
/*
 * SMHasher3
 * Copyright (C) 2021-2022  Frank J. T. Wojcik
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <https://www.gnu.org/licenses/>.
 */
#include <cstdio>    // Allow printf() from anywhere
#include <cstring>   // For memcpy

//-----------------------------------------------------------------------------
// Fixed-width integers (required before all else)
#include <cstdint>
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
typedef unsigned __int128 uint128_t;
typedef          __int128  int128_t;
#pragma GCC diagnostic pop
#define HAVE_INT128
typedef uint64_t  seed_t; 
#define __STDC_FORMAT_MACROS 1 // Some older gcc installations need this
#include <cinttypes>

//-----------------------------------------------------------------------------
// MSVC-specific things (if required)


//-----------------------------------------------------------------------------
// Declarations for Platform.cpp


//-----------------------------------------------------------------------------
// Compiler-specific functions and macros

// Compiler branching hints
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#define expectp(x,p) __builtin_expect_with_probability(!!(x), 1, (p))
#define unpredictable(x) __builtin_unpredictable(x)

// Compiler behavioral bounds hints
#define assume(x) __builtin_assume(x)
#define unreachable() __builtin_unreachable()

// Compiler/CPU data prefetching
#define prefetch(ptr) __builtin_prefetch(ptr)

// Function inlining control
#define FORCE_INLINE __attribute__((__always_inline__)) inline
#define NEVER_INLINE __attribute__((__noinline__))

// Variable aliasing
#define MAY_ALIAS __attribute__((__may_alias__))

// C "restrict" keyword replacement
#define RESTRICT __restrict

// Integer rotation
// CAUTION: These are deliberately unsafe!
// They assume the rotation value is not 0 or >= {32,64}.
// If an invalid rotation amount is given, the result is undefined behavior.
static inline uint32_t _rotl32(uint32_t v, uint8_t n) {
    return (v << n) | (v >> ((-n) & 31));
}
static inline uint32_t _rotr32(uint32_t v, uint8_t n) {
    return (v >> n) | (v << ((-n) & 31));
}
#define ROTL32(v, n) _rotl32(v, n)
#define ROTR32(v, n) _rotr32(v, n)
static inline uint64_t _rotl64(uint64_t v, uint8_t n) {
    return (v << n) | (v >> ((-n) & 63));
}
static inline uint64_t _rotr64(uint64_t v, uint8_t n) {
    return (v >> n) | (v << ((-n) & 63));
}
#define ROTL64(v, n) _rotl64(v, n)
#define ROTR64(v, n) _rotr64(v, n)

// Population count (popcnt/popcount)
#define popcount4(x) __builtin_popcount(x)
#define popcount8(x) __builtin_popcountll(x)

// Leading zero-bit count (ffs/clz)
// CAUTION: Assumes x is not 0!
#define clz4(x) __builtin_clz(x)
#define clz8(x) __builtin_clzll(x)

// Integer byteswapping (endianness conversion)
// You can use the bit-specific ones directly, but the more generic
// versions below are preferred.
#define BSWAP16(x) __builtin_bswap16(x)
#define BSWAP32(x) __builtin_bswap32(x)
#define BSWAP64(x) __builtin_bswap64(x)

//-----------------------------------------------------------------------------
// Generic wrappers for BSWAP*()
template < typename T >
static FORCE_INLINE T BSWAP(T value) {
    switch(sizeof(T)) {
    case 2: value = BSWAP16((uint16_t)value); break;
    case 4: value = BSWAP32((uint32_t)value); break;
    case 8: value = BSWAP64((uint64_t)value); break;
    default: break;
    }
    return value;
}

template < typename T >
static FORCE_INLINE T COND_BSWAP(T value, bool doit) {
    if (!doit || (sizeof(T) < 2)) { return value; }
    return BSWAP(value);
}

//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// User-configurable implementations

// Endianness detection
static FORCE_INLINE bool isLE(void) {
const uint32_t   value = 0xb000000e;
const void *      addr = static_cast<const void *>(&value);
const uint8_t *   lsb  = static_cast<const uint8_t *>(addr);
return ((*lsb) == 0x0e);
}
static FORCE_INLINE bool isBE(void) {
const uint32_t   value = 0xb000000e;
const void *      addr = static_cast<const void *>(&value);
const uint8_t *   lsb  = static_cast<const uint8_t *>(addr);
return ((*lsb) == 0xb0);
}



//-----------------------------------------------------------------------------
// Routines for turning bytes in memory into integers. These move data
// in alignment-safe ways, with optional byte swapping.
//
// memcpy() is the only known way of safely moving data this way;
// "safe" meaning "defined C++ behavior" AND "working regardless of
// alignment". Every memcpy() call here has a fixed size, and modern
// compilers tend to inline these into alignment-safe data moves/loads
// that are best for the platform being compiled for. Earlier
// compilers did not always do this very well, at least on non-x86
// platforms.
//
// If someone ever wanted to allow hashes to use undefined-behavior
// for faster access, this is where different access methods could be
// introduced, such as reading through a union or just doing direct
// memory access by pointer type conversion. Both of those are
// undefined behavior (UB), though! Beware of nasal demons!
//
// It's also plausible to introduce different versions of these which
// handle known-to-be-aligned accesses in a different way, perhaps
// through another template parameter.

template < bool bswap >
static FORCE_INLINE uint64_t GET_U64(const uint8_t * b, const uint32_t i) {
    uint64_t n;
    memcpy(&n, &b[i], 8);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE uint32_t GET_U32(const uint8_t * b, const uint32_t i) {
    uint32_t n;
    memcpy(&n, &b[i], 4);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE uint16_t GET_U16(const uint8_t * b, const uint32_t i) {
    uint16_t n;
    memcpy(&n, &b[i], 2);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE void PUT_U16(uint16_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 2);
}

template < bool bswap >
static FORCE_INLINE void PUT_U32(uint32_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 4);
}

template < bool bswap >
static FORCE_INLINE void PUT_U64(uint64_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 8);
}

//-----------------------------------------------------------------------------
// Generic vector support
#define VECTOR_SIZE(SZ)  __attribute__ ((vector_size (SZ)))
#define HAVE_GENERIC_VECTOR


//-----------------------------------------------------------------------------
// VLA helper
//
// Allocates on heap when VLA is not available

#if defined(__STDC_NO_VLA__) || defined(_MSC_VER) && !defined(__clang__)
    #include <vector>
    #define VLA_ALLOC(type, name, count) std::vector<type> name(count)
#else
    #define VLA_ALLOC(type, name, count)  \
 _Pragma("GCC diagnostic push");          \
 _Pragma("GCC diagnostic ignored \"-Wvla\""); \
 _Pragma("clang diagnostic ignored \"-Wvla-extension\""); \
 type name[count];                            \
 _Pragma("GCC diagnostic pop");
#endif

//-----------------------------------------------------------------------------
// Debugging helpers
//
// Really wish these could be moved into the CMake generation-time
// detection, but I can't find a reliable way of checking if "-DDEBUG"
// will be passed to the compiler.

#if defined(DEBUG)
  #include <cassert>

  #undef assume
  #define assume(x) assert(x)

  #undef unreachable
  #define unreachable() assert(0)

  #define verify(x) assert(x)
#else
  static void warn_if(bool x, const char * s, const char * fn, uint64_t ln) {
      if (!x) {
          printf("Statement %s is not true: %s:%" PRId64 "\n", s, fn, ln);
      }
  }
  #define verify(x) warn_if(x, #x, __FILE__, __LINE__)
#endif

#define unused(x) (void)(x)

//-----------------------------------------------------------------------------
// Instruction-set architecture header detection, for internal use only

/* #undef HAVE_ARM_NEON */
/* #undef HAVE_ARM_ACLE */
/* #undef HAVE_IMMINTRIN */
/* #undef HAVE_AMMINTRIN */
/* #undef HAVE_X86INTRIN */

//-----------------------------------------------------------------------------
// Instruction-set architecture and platform feature availability

/* #undef HAVE_32BIT_PLATFORM */

/* #undef HAVE_GCC_COMPILER */

/* #undef HAVE_SSE_2 */
/* #undef HAVE_GOOD_LOADU_32 */
/* #undef HAVE_GOOD_LOADU_64 */
/* #undef HAVE_SSSE_3 */
/* #undef HAVE_SSE_4_1 */
/* #undef HAVE_XOP */
/* #undef HAVE_X86_64_CRC32C */
/* #undef HAVE_X86_64_CLMUL */
/* #undef HAVE_X86_64_AES */
/* #undef HAVE_X86_64_SHA1 */
/* #undef HAVE_X86_64_SHA2 */
/* #undef HAVE_AVX */
/* #undef HAVE_AVX2 */
/* #undef HAVE_AVX512_F */
/* #undef HAVE_AVX512_BW */
/* #undef HAVE_AVX512_VL */
/* #undef HAVE_UMULH */
/* #undef HAVE_UMUL128 */
/* #undef HAVE_X86_64_ASM */
/* #undef HAVE_ARM_AES */
/* #undef HAVE_ARM_SHA1 */
/* #undef HAVE_ARM_SHA2 */
/* HAVE_ARM_ASM removed: portable C paths only */
/* HAVE_ARM64_ASM removed */
/* #undef HAVE_PPC_VSX */
/* #undef HAVE_PPC_AES */
/* #undef HAVE_PPC_ASM */

/* === SMHasher3 include/hashlib/Mathmult.h (verbatim) === */
/*
 * Multiplication and addition routines for >=64-bit math,
 * in terms of <=64-bit variables.
 *
 * Copyright (C) 2021-2023  Frank J. T. Wojcik
 * Copyright (C) 2023       jason
 * Copyright (c) 2016 Vladimir Makarov <vmakarov@gcc.gnu.org>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Some of this is based off of code from PMP Multilinear hashes:
 *
 *     Copyright (C) 2021-2022  Frank J. T. Wojcik
 *     Copyright (c) 2014-2021 Reini Urban
 *     Copyright (c) 2014, Dmytro Ivanchykhin, Sergey Ignatchenko, Daniel Lemire
 *     All rights reserved.
 *
 *     Redistribution and use in source and binary forms, with or without
 *     modification, are permitted provided that the following conditions are met:
 *
 *     1. Redistributions of source code must retain the above copyright notice, this
 *        list of conditions and the following disclaimer.
 *     2. Redistributions in binary form must reproduce the above copyright notice,
 *        this list of conditions and the following disclaimer in the documentation
 *        and/or other materials provided with the distribution.
 *
 *     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 *     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *     ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * There are several places here which have different versions of this code
 * for clang, all of which check for that via "defined(__clang__)".
 *
 * This is because clang does not work well with asm constraints. One
 * example is that, given the option, clang has some sort of preference for
 * memory operands. It may spill a register to the stack, and operate on
 * the stack copy. Or it may spill to the stack, operate on the register,
 * and then spill the new value to the stack again, without ever reading or
 * operating on the stack copy even once. Therefore, clang is not given the
 * option of memory operands.
 *
 * This is still true for clang trunk as of July 2023. You can see more
 * about this issue at:
 *    http://stackoverflow.com/questions/16850309/
 *    https://github.com/llvm/llvm-project/issues/20571
 *    https://godbolt.org/z/Wr3EvKnhn
 */

namespace MathMult {

// 32x32->64 multiplication [rhi:rlo = a * b]
static FORCE_INLINE void mult32_64( uint32_t & rlo, uint32_t & rhi, uint32_t a, uint32_t b ) {
    // XXX Are either of these asm blocks better than just the plain code?
#if 0 && defined(HAVE_ARM_ASM)
    __asm__ ("UMULL %w0, %w1, %w2, %w3"
             : "+r" (rlo), "+r" (rhi)
             : "r" (a), "r" (b)
             : "cc", "memory"
    );
#elif 0 && defined(HAVE_X86_64_ASM)
    __asm__ ("mull  %[b]"
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), [b] "rm" (b)
    );
#else
    uint64_t r = (uint64_t)a * (uint64_t)b;
    rhi = (uint32_t)(r >> 32);
    rlo = (uint32_t)r;
#endif
}

// 32x32->64 multiplication [r64 = a32 * b32]
static FORCE_INLINE void mult32_64( uint64_t & r64, uint32_t a32, uint32_t b32 ) {
#if defined(_MSC_VER) && defined(_M_IX86)
    r64 = __emulu(a32, b32);
#else
    r64 = (uint64_t)a32 * (uint64_t)b32;
#endif
}

// 96-bit addition [rhi:rmi:rlo += addhi:addmi:addlo]
static FORCE_INLINE void add96( uint32_t & rlo, uint32_t & rmi, uint32_t & rhi, const uint32_t & addlo,
        const uint32_t & addmi, const uint32_t & addhi ) {
#if defined(HAVE_ARM_ASM)
    __asm__ ("ADDS %w0, %w3, %w0\n\t"
             "ADCS %w1, %w4, %w1\n\t"
             "ADC  %w2, %w5, %w2"
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "r" (addlo), "r" (addmi), "r" (addhi)
             : "cc"
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("addl %3, %0\n\t"
             "adcl %4, %1\n\t"
             "adcl %5, %2"
  #if defined(__clang__)
             : "+r" (rlo),   "+r" (rmi),   "+r" (rhi)
             : "re" (addlo), "re" (addmi), "re" (addhi)
  #else
             : "+g,g,g,g,r,r,r,r" (rlo),  "+g,g,r,r,g,g,r,r" (rmi),  "+g,r,g,r,g,r,g,r" (rhi)
             : "re,re,re,re,m,m,m,m" (addlo), "re,re,m,m,re,re,m,m" (addmi), "re,m,re,m,re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    uint64_t w = (((uint64_t)rmi  ) << 32) + ((uint64_t)rlo  );
    uint64_t r = (((uint64_t)addmi) << 32) + ((uint64_t)addlo) + w;
    rhi += addhi + (r < w);
    rmi  = (uint32_t)(r >> 32);
    rlo  = (uint32_t)(r      );
#endif
}

// 64-bit fused multiply addition [r64 += a * b]
static FORCE_INLINE void fma32_64( uint64_t & r64, uint32_t a, uint32_t b ) {
#if defined(HAVE_ARM_ASM)
    //uint64_t ret;
    __asm__("umaddl %x0, %w1, %w2, %x3" : "=r" (r64) : "r" (a), "r" (b), "r" (r64));
    //r64 = ret;
#else
    uint64_t v;
    MathMult::mult32_64(v, a, b);
    r64 += v;
#endif
}

// 96-bit fused multiply addition [rhi:rmi:rlo += a * b]
static FORCE_INLINE void fma32_96( uint32_t & rlo, uint32_t & rmi, uint32_t & rhi, uint32_t a, uint32_t b ) {
// These #defines are not correct; some arm seems to not support this
#if 0 && defined(HAVE_ARM_ASM)
    uint32_t tmphi, tmplo;
    __asm__ ("UMULL %w3, %w4, %w5, %w6\n\t"
             "ADDS  %w0, %w3, %w0\n\t"
             "ADCS  %w1, %w4, %w1\n\t"
             "ADC   %w2, %w2, #0x0"
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "r" (a), "r" (b)
             : "cc"
    );
#elif defined(HAVE_X86_64_ASM)
    uint32_t tmplo, tmphi;
    __asm__ ("mull %6\n\t"
             "addl %%eax, %0\n\t"
             "adcl %%edx, %1\n\t"
             "adcl $0, %2"
  #if defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc"
    );
#else
    uint32_t tmplo, tmpmi, tmphi = 0;
    mult32_64(tmplo, tmpmi, a, b);
    add96(rlo, rmi, rhi, tmplo, tmpmi, tmphi);
#endif
}

// 64x64->128 multiplication [rhi:rlo = a * b]
static FORCE_INLINE void mult64_128( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_UMUL128)
    rlo = _umul128(a, b, &rhi);
#elif defined(HAVE_UMULH)
    rlo = a * b;
    rhi = __umulh(a, b);
#elif defined(HAVE_ARM64_ASM)
    /*
     * AARCH64 needs 2 insns to calculate 128-bit result of the
     * multiplication.  If we use a generic code we actually call a
     * function doing 128x128->128 bit multiplication. The function
     * is very slow.
     */
    rlo = a * b;
    __asm__ ("umulh %0, %1, %2"
             : "=r" (rhi)
             : "r" (a), "r" (b)
    );
#elif defined(HAVE_PPC_ASM)
    rlo = a * b;
    __asm__ ("mulhdu %0, %1, %2"
             : "=r" (rhi)
             : "r" (a), "r" (b)
    );
#elif defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    /*
     * We want to use AVX2 insn MULX instead of generic x86-64 MULQ
     * where it is possible.  Although on modern Intel processors MULQ
     * takes 3-cycles vs. 4 for MULX, MULX permits more freedom in
     * insn scheduling as it uses less fixed registers.
     */
    __asm__ ("mulxq %3, %1, %0"
  #if defined(__clang__)
             : "=r" (rhi), "=r" (rlo)
             : "%d" (a), "r" (b)
  #else
             : "=r" (rhi), "=r" (rlo)
             : "%d" (a), "rm" (b)
  #endif
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("mulq %3"
  #if defined(__clang__)
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), "r" (b)
  #else
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), "rm" (b)
  #endif
             : "cc"
    );
#elif defined(HAVE_INT128)
    // Maybe move this before the other x64 ASM methods?
    // Seems like it's more compiler-friendly, but it produces slower code.
    uint128_t r = (uint128_t)a * (uint128_t)b;
    rhi = (uint64_t)(r >> 64);
    rlo = (uint64_t)r;
#else
    /*
     * Implementation of 64x64->128-bit multiplication by four
     * 32x32->64 bit multiplication.
     */
    uint64_t ahi = a >> 32, bhi = b >> 32;
    uint64_t alo = (uint32_t)a, blo = (uint32_t)b;
    uint64_t tmphi   = ahi * bhi;
    uint64_t tmpmi_0 = ahi * blo;
    uint64_t tmpmi_1 = alo * bhi;
    uint64_t tmplo   = alo * blo;
    uint64_t t, carry = 0;

    t      = (tmpmi_0 << 32   ) + tmplo;
    carry += (t        < tmplo);
    rlo    = (tmpmi_1 << 32   ) + t;
    carry += (rlo      < t    );
    rhi    = (tmpmi_0 >> 32   ) + (tmpmi_1 >> 32) + tmphi + carry;
#endif
}

// 64x64->128 multiplication with no cross-lane carry [rhi:rlo ~= a * b]
static FORCE_INLINE void mult64_128_nocarry( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
    /*
     * Implementation of 64x64->128-bit multiplication by four
     * 32x32->64 bit multiplication, excluding the carry bits.  This
     * is a bit faster in the absence of a real 128-bit multiply
     * instruction, and almost as good for hashing.
     */
    uint64_t ahi = a >> 32, bhi = b >> 32;
    uint64_t alo = (uint32_t)a, blo = (uint32_t)b;
    uint64_t tmphi   = ahi * bhi;
    uint64_t tmpmi_0 = ahi * blo;
    uint64_t tmpmi_1 = alo * bhi;
    uint64_t tmplo   = alo * blo;

    rlo = tmplo + (tmpmi_0 << 32) + (tmpmi_1 << 32);
    rhi = tmphi + (tmpmi_0 >> 32) + (tmpmi_1 >> 32);
}

// 128-bit addition special case [rhi:rlo += 0:addlo]
static FORCE_INLINE void add128( uint64_t & rlo, uint64_t & rhi, uint64_t addlo ) {
#if defined(HAVE_X86_64_ASM)
    __asm__ ("addq %2, %0\n\t"
             "adcq $0, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi)
             : "r" (addlo)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi)
             : "re" (addlo)
  #else
             : "+g,r" (rlo), "+g,g" (rhi)
             : "re,m" (addlo)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rhi += (rlo < addlo);
#endif
}

// 128-bit addition [rhi:rlo += addhi:addlo]
static FORCE_INLINE void add128( uint64_t & rlo, uint64_t & rhi, uint64_t addlo, uint64_t addhi ) {
#if defined(HAVE_PPC_ASM)
    __asm__ ("addc %1, %1, %3\n\t"
             "adde %0, %0, %2"
             : "+r" (rhi), "+r" (rlo)
             : "r" (addhi), "r" (addlo)
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("addq %2, %0\n\t"
             "adcq %3, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi)
             : "r" (addlo), "r" (addhi)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi)
             : "re" (addlo), "re" (addhi)
  #else
             : "+g,g,r,r" (rlo), "+g,r,g,r" (rhi)
             : "re,re,m,m" (addlo), "re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rhi += (rlo < addlo);
    rhi += addhi;
#endif
}

// 192-bit addition [rhi:rmi:rlo += addhi:addmi:addlo]
static FORCE_INLINE void add192( uint64_t & rlo, uint64_t & rmi, uint64_t & rhi, const uint64_t & addlo,
        const uint64_t & addmi, const uint64_t & addhi ) {
#if defined(HAVE_X86_64_ASM)
    __asm__ ("addq %3, %0\n\t"
             "adcq %4, %1\n\t"
             "adcq %5, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "r" (addlo), "r" (addmi), "r" (addhi)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "re" (addlo), "re" (addmi), "re" (addhi)
  #else
             : "+g,g,g,g,r,r,r,r" (rlo), "+g,g,r,r,g,g,r,r" (rmi), "+g,r,g,r,g,r,g,r" (rhi)
             : "re,re,re,re,m,m,m,m" (addlo), "re,re,m,m,re,re,m,m" (addmi), "re,m,re,m,re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rmi += (rlo < addlo);
    rmi += addmi;
    rhi += (rmi < addmi);
    rhi += addhi;
#endif
}

// 128-bit fused multiply addition [rhi:rlo += a * b]
static FORCE_INLINE void fma64_128( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulxq %5, %2, %3\n\t"
             "addq %2, %0\n\t"
             "adcq %3, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "d" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "rm" (b)
  #endif
             : "cc");
#elif defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulq %5\n\t"
             "addq %%rax, %0\n\t"
             "adcq %%rdx, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "a" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc");
#else
    uint64_t tmplo, tmphi;
    mult64_128(tmplo, tmphi, a, b);
    add128(rlo, rhi, tmplo, tmphi);
#endif
}

// 192-bit fused multiply addition [rhi:rmi:rlo += a * b]
static FORCE_INLINE void fma64_192( uint64_t & rlo, uint64_t & rmi, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulxq %6, %3, %4\n\t"
             "addq %3, %0\n\t"
             "adcq %4, %1\n\t"
             "adcq $0, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "d" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "rm" (b)
  #endif
             : "cc");
#elif defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulq %6\n\t"
             "addq %%rax, %0\n\t"
             "adcq %%rdx, %1\n\t"
             "adcq $0, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "a" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc");
#else
    uint64_t tmplo, tmpmi, tmphi = 0;
    mult64_128(tmplo, tmpmi, a, b);
    add192(rlo, rmi, rhi, tmplo, tmpmi, tmphi);
#endif
}

// 128x128->128 multiplication [rhi:rlo = ahi:alo * bhi:blo]
static FORCE_INLINE void mult128_128( uint64_t & rlo, uint64_t & rhi, uint64_t alo,
        uint64_t ahi, uint64_t blo, uint64_t bhi ) {
#if defined(HAVE_INT128)
    uint128_t r = (((uint128_t)ahi) << 64) + (uint128_t)alo;
    uint128_t c = (((uint128_t)bhi) << 64) + (uint128_t)blo;
    r   = r * c;
    rhi = (uint64_t)(r >> 64);
    rlo = (uint64_t)r;
#else
    mult64_128(rlo, rhi, alo, blo);
    rhi += bhi * alo;
    rhi += blo * ahi;
#endif
}

} // namespace MathMult

/* ---- minimal stand-in for SMHasher3 Hashinfo.h / Hashlib.h registration ---- */
#include <vector>
#include <set>
#include <string>
#define FLAG_EXPAND_LIST(X) X(HASH_DONOTHING) X(HASH_MOCK) X(HASH_CRYPTOGRAPHIC) X(HASH_CRYPTOGRAPHIC_WEAK) X(HASH_CRC_BASED) X(HASH_AES_BASED) X(HASH_CLMUL_BASED) X(HASH_LOOKUP_TABLE) X(HASH_XL_SEED) X(HASH_SMALL_SEED) X(HASH_NO_SEED) X(HASH_SYSTEM_SPECIFIC) X(HASH_ENDIAN_INDEPENDENT) X(HASH_FLOATING_POINT) \
 X(IMPL_SANITY_FAILS) X(IMPL_SLOW) X(IMPL_VERY_SLOW) X(IMPL_READ_PAST_EOB) X(IMPL_TYPE_PUNNING) X(IMPL_INCREMENTAL) X(IMPL_INCREMENTAL_DIFFERENT) X(IMPL_128BIT) X(IMPL_MULTIPLY) X(IMPL_MULTIPLY_64_64) X(IMPL_MULTIPLY_64_128) X(IMPL_MULTIPLY_128_128) X(IMPL_ROTATE) X(IMPL_ROTATE_VARIABLE) X(IMPL_SHIFT_VARIABLE) X(IMPL_MODULUS) X(IMPL_ASM) X(IMPL_CANONICAL_LE) X(IMPL_CANONICAL_BE) X(IMPL_CANONICAL_BOTH) X(IMPL_SEED_WITH_HINT) X(IMPL_LICENSE_PUBLIC_DOMAIN) X(IMPL_LICENSE_BOOST) X(IMPL_LICENSE_BSD) X(IMPL_LICENSE_MIT) X(IMPL_LICENSE_APACHE2) X(IMPL_LICENSE_ZLIB) X(IMPL_LICENSE_GPL3)
#define FE1(n) FLAG_ENUM_##n,
enum { FLAG_EXPAND_LIST(FE1) FLAG_ENUM_COUNT };
#define FE2(n) static const uint64_t FLAG_##n = 1ULL << FLAG_ENUM_##n;
FLAG_EXPAND_LIST(FE2)
class HashInfo;
typedef void   (*HashFn)(const void *in, const size_t len, const seed_t seed, void *out);
typedef seed_t (*HashSeedfixFn)(const HashInfo *hinfo, const seed_t seed);
struct HashFamilyInfo { enum SrcStatus { SRC_UNKNOWN, SRC_FROZEN, SRC_STABLEISH, SRC_ACTIVE }; const char *name; const char *src_url = ""; int src_status = 0;
  HashFamilyInfo(const char *n) : name(n) {} };
struct HashInfo {
  const char *name, *family; const char *desc = ""; const char *impl = "";
  uint64_t hash_flags = 0, impl_flags = 0; uint32_t bits = 0;
  uint32_t verification_LE = 0, verification_BE = 0;
  HashFn hashfn_native = nullptr, hashfn_bswap = nullptr;
  HashSeedfixFn seedfixfn = nullptr; std::set<seed_t> badseeds; const char *badseeddesc = "";
  uint32_t sort_order = 0;
  HashInfo(const char *n, const char *f) : name(n), family(f) {}
};
static std::vector<HashInfo> &registry() { static std::vector<HashInfo> r; return r; }
static unsigned register_hash(const HashInfo *h) { registry().push_back(*h); return 0; }
static seed_t excludeBadseeds(const HashInfo *hinfo, const seed_t seed) { (void)hinfo; return seed; }
#define CONCAT_INNER(x, y) x ## y
#define CONCAT(x, y) CONCAT_INNER(x, y)
#define REGISTER_FAMILY(N, ...) static HashFamilyInfo THIS_HASH_FAMILY = []{ HashFamilyInfo $(#N); __VA_ARGS__; return $; }(); unsigned CONCAT(N,_ref)
#define REGISTER_HASH(N, ...) static HashInfo CONCAT(Hash_,N) = []{ HashInfo $(#N, THIS_HASH_FAMILY.name); __VA_ARGS__; register_hash(&$); return $; }()
static const HashInfo *findHash(const char *n) { for (auto &h : registry()) if (!strcmp(h.name, n)) return &h; return nullptr; }
/* SMHasher3 lib/Hashinfo.cpp _ComputedVerifyImpl, native endianness, SEED_FORCED (no seedfn in these files) */
static uint32_t sm3_verification(const HashInfo *hi) {
  const uint32_t hb = hi->bits / 8; std::vector<uint8_t> key(256, 0), hashes(hb * 256, 0), total(hb, 0);
  for (int i = 0; i < 256; i++) { hi->hashfn_native(key.data(), i, (seed_t)(256 - i), &hashes[i * hb]); key[i] = (uint8_t)i; }
  hi->hashfn_native(hashes.data(), hb * 256, 0, total.data());
  return (uint32_t)total[0] | ((uint32_t)total[1] << 8) | ((uint32_t)total[2] << 16) | ((uint32_t)total[3] << 24);
}
/* ===================== SMHasher3 hashes/mum_mir.cpp (verbatim) ===================== */
/*
 * MUM and MIR hashes
 * Copyright (C) 2021-2022  Frank J. T. Wojcik
 * Copyright (c) 2016 Vladimir Makarov <vmakarov@gcc.gnu.org>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


//-----------------------------------------------------------------------------
// Multiply 64-bit V and P and return sum of high and low parts of the
// result.
//
// On systems without a 64*64->128 multiply instruction, this
// computation is done via 64*64->64-bit multiplies. However, since
// true mathematical precision is not needed, an alternative mode of
// hash operation is to ignore the carry bits, leading to a similar
// but slightly different result, which is faster to compute if no
// 128-bit multiply result is available.
//
// The code has been reworked to allow both forms to always be
// calculable on every platform.
template <bool exact>
static inline uint64_t _mum( uint64_t v, uint64_t p ) {
    uint64_t hi, lo;

    if (exact) {
        MathMult::mult64_128(lo, hi, v, p);
    } else {
        MathMult::mult64_128_nocarry(lo, hi, v, p);
    }

    /*
     * We could use XOR here too but, for some reasons, on Haswell and
     * Power7 using an addition improves hashing performance by 10% for
     * small strings.
     */
    return hi + lo;
}

//-----------------------------------------------------------------------------
// MUM hash internals

/*
 * Here are different primes randomly generated with the equal
 * probability of their bit values.  They are used to randomize input
 * values.
 */
static const uint64_t _mum_block_start_prime = UINT64_C(0xc42b5e2e6480b23b);
static const uint64_t _mum_unroll_prime      = UINT64_C(0x7b51ec3d22f7096f);
static const uint64_t _mum_tail_prime        = UINT64_C(0xaf47d47c99b1461b);
static const uint64_t _mum_finish_prime1     = UINT64_C(0xa9a7ae7ceff79f3f);
static const uint64_t _mum_finish_prime2     = UINT64_C(0xaf47d47c99b1461b);

static const uint64_t _mum_primes[] = {
    UINT64_C(0x9ebdcae10d981691), UINT64_C(0x32b9b9b97a27ac7d),
    UINT64_C(0x29b5584d83d35bbd), UINT64_C(0x4b04e0e61401255f),
    UINT64_C(0x25e8f7b1f1c9d027), UINT64_C(0x80d4c8c000f3e881),
    UINT64_C(0xbd1255431904b9dd), UINT64_C(0x8a3bd4485eee6d81),
    UINT64_C(0x3bc721b2aad05197), UINT64_C(0x71b1a19b907d6e33),
    UINT64_C(0x525e6c1084a8534b), UINT64_C(0x9e4c2cd340c1299f),
    UINT64_C(0xde3add92e94caa37), UINT64_C(0x7e14eadb1f65311d),
    UINT64_C(0x3f5aa40f89812853), UINT64_C(0x33b15a3b587d15c9),
};

// Since unroll_power actually affects hash *values*, not just speed,
// it needs to be a template parameter, so all versions of the hash
// can be tested on all platforms.
template <uint32_t version, uint32_t unroll_power, bool bswap, bool exactmul>
// _MUM_OPTIMIZE("unroll-loops")
static inline uint64_t _mum_hash_aligned( uint64_t seed, const void * key, size_t len ) {
    const uint32_t  _MUM_UNROLL_FACTOR = 1 << unroll_power;
    const uint8_t * str = (const uint8_t *)key;
    uint64_t        u64, result;
    size_t          i;
    size_t          n;

    if ((version == 1) || (version == 3)) {
        result = _mum<exactmul>(seed, _mum_block_start_prime);
    } else {
        result = seed;
    }
    while (len > _MUM_UNROLL_FACTOR * sizeof(uint64_t)) {
        /*
         * This loop could be vectorized when we have vector insns for
         * 64x64->128-bit multiplication.  AVX2 currently only have a
         * vector insn for 4 32x32->64-bit multiplication.
         */
        if ((version == 1) || (version == 2)) {
            for (i = 0; i < _MUM_UNROLL_FACTOR; i++) {
                result ^= _mum<exactmul>(GET_U64<bswap>(str, i * 8) , _mum_primes[i]);
            }
        } else {
            for (i = 0; i < _MUM_UNROLL_FACTOR; i += 2) {
                result ^= _mum<exactmul>(GET_U64<bswap>(str, i * 8) ^ _mum_primes[i],
                        GET_U64<bswap>(str, i * 8 + 8) ^ _mum_primes[i + 1]);
            }
        }
        len   -= _MUM_UNROLL_FACTOR * sizeof(uint64_t);
        str   += _MUM_UNROLL_FACTOR * sizeof(uint64_t);
        /*
         * We will use the same prime numbers on the next iterations --
         * randomize the state.
         */
        result = _mum<exactmul>(result, _mum_unroll_prime);
    }
    n = len / sizeof(uint64_t);
    for (i = 0; i < n; i++) {
        result ^= _mum<exactmul>(GET_U64<bswap>(str, i * 8), _mum_primes[i]);
    }
    len -= n * sizeof(uint64_t); str += n * sizeof(uint64_t);
    switch (len) {
    case 7:
            u64  = GET_U32<bswap>(str, 0);
            u64 |= (uint64_t)str[4] << 32;
            u64 |= (uint64_t)str[5] << 40;
            u64 |= (uint64_t)str[6] << 48;
            return result ^ _mum<exactmul>(u64, _mum_tail_prime);
    case 6:
            u64  = GET_U32<bswap>(str, 0);
            u64 |= (uint64_t)str[4] << 32;
            u64 |= (uint64_t)str[5] << 40;
            return result ^ _mum<exactmul>(u64, _mum_tail_prime);
    case 5:
            u64  = GET_U32<bswap>(str, 0);
            u64 |= (uint64_t)str[4] << 32;
            return result ^ _mum<exactmul>(u64, _mum_tail_prime);
    case 4:
            u64 =  GET_U32<bswap>(str, 0);
            return result ^ _mum<exactmul>(u64, _mum_tail_prime);
    case 3:
            u64  = str[0];
            u64 |= (uint64_t)str[1] <<  8;
            u64 |= (uint64_t)str[2] << 16;
            return result ^ _mum<exactmul>(u64, _mum_tail_prime);
    case 2:
            u64  = str          [0];
            u64 |= (uint64_t)str[1] <<  8;
            return result ^ _mum<exactmul>(u64, _mum_tail_prime);
    case 1:
            u64 = str           [0];
            return result ^ _mum<exactmul>(u64, _mum_tail_prime);
    }
    return result;
}

/* Final randomization of H.  */
template <uint32_t version, bool exactmul>
static inline uint64_t _mum_final( uint64_t h ) {
    if (version == 1) {
        h ^= _mum<exactmul>(h, _mum_finish_prime1);
        h ^= _mum<exactmul>(h, _mum_finish_prime2);
    } else if (version == 2) {
        h ^= ROTL64(h, 33);
        h ^= _mum<exactmul>(h, _mum_finish_prime1);
    } else {
        h = _mum<exactmul>(h, h);
    }
    return h;
}

//-----------------------------------------------------------------------------
// MUM hash externals for SMHasher3

template <uint32_t version, uint32_t unroll_power, bool bswap, bool exactmul>
static void mum_aligned( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint64_t h;

    h = _mum_hash_aligned<version, unroll_power, bswap, exactmul>(seed + len, in, len);
    h = _mum_final<version, exactmul>(h);
    PUT_U64<bswap>(h, (uint8_t *)out, 0);
}

// fwojcik: I believe the fact that the realign versions of the
// hash can have different hashes than the aligned version is
// unintended behavior. The differences come only from 2 places:
//    1) v1 and v3 of the hash have a per-block MUM step, and
//    2) _mum_hash_aligned() uses "while (len > ....." instead of
//      "while (len >= .....".
// Based on this, I'm removing the realign variants for now.
#if defined(NOTYET)

template <uint32_t version, uint32_t unroll_power, bool bswap, bool exactmul>
static void mum_realign( const void * in, const size_t olen, const seed_t seed, void * out ) {
    const uint8_t * str = (const uint8_t *)in;
    const uint32_t  _MUM_BLOCK_LEN = 1024;
    uint64_t        buf[_MUM_BLOCK_LEN / sizeof(uint64_t)];
    size_t          len = olen;
    uint64_t        h   = seed + olen;

    while (len != 0) {
        size_t block_len = len < _MUM_BLOCK_LEN ? len : _MUM_BLOCK_LEN;
        memmove(buf, str, block_len);
        h    = _mum_hash_aligned<version, unroll_power, bswap, exactmul>(h, buf, block_len);
        len -= block_len;
        str += block_len;
    }
    h = _mum_final<version, exactmul>(h);
    PUT_U64<bswap>(h, (uint8_t *)out, 0);
}

#endif

//-----------------------------------------------------------------------------
// MIR hash internals

/*
 * Simple high-quality multiplicative hash passing demerphq-smhsher,
 * faster than spooky, city, or xxhash for strings less 100 bytes.
 * Hash for the same key can be different on different architectures.
 * To get machine-independent hash, use mir_hash_strict which is about
 * 1.5 times slower than mir_hash.
 */
template <bool exact>
static inline uint64_t mir_mum( uint64_t v, uint64_t c ) {
    if (exact) { return _mum<true>(v, c); }
    uint64_t v1 = v >> 32, v2 = (uint32_t)v, c1 = c >> 32, c2 = (uint32_t)c, rm = v2 * c1 + v1 * c2;
    return v1 * c1 + (rm >> 32) + v2 * c2 + (rm << 32);
}

static const uint64_t p1 = UINT64_C(0x65862b62bdf5ef4d), p2 = UINT64_C(0x288eea216831e6a7);

template <bool exactmul>
static inline uint64_t mir_round( uint64_t state, uint64_t v ) {
    state ^= mir_mum<exactmul>(v, p1);
    return state ^ mir_mum<exactmul>(state, p2);
}

template <bool bswap>
static inline uint64_t mir_get_key_part( const uint8_t * v, size_t len ) {
    size_t   i, start = 0;
    uint64_t tail = 0;

    if (len >= sizeof(uint32_t)) {
        tail  = ((uint64_t)(GET_U32<bswap>(v, 0))) << 32;
        start = 4;
    }
    for (i = start; i < len; i++) { tail = (tail >> 8) | ((uint64_t)v[i] << 56); }
    return tail;
}

//-----------------------------------------------------------------------------
// MIR hash externals for SMHasher3

// The bswap and exactmul booleans cover all possible sets of hash
// values from the original mir_hash() in both "strict" mode and
// "relaxed" mode, regardless of machine endianness.
template <bool bswap, bool exactmul>
static void mir_hash( const void * in, const size_t olen, const seed_t seed, void * out ) {
    const uint8_t * v   = (const uint8_t *)in;
    uint64_t        r   = seed + olen;
    size_t          len = olen;

    for (; len >= 16; len -= 16, v += 16) {
        r ^= mir_mum<exactmul>(GET_U64<bswap>(v, 0), p1);
        r ^= mir_mum<exactmul>(GET_U64<bswap>(v, 8), p2);
        r ^= mir_mum<exactmul>(r, p1);
    }
    if (len >= 8) {
        r   ^= mir_mum<exactmul>(GET_U64<bswap>(v, 0), p1);
        len -= 8, v += 8;
    }
    if (len != 0) {
        r ^= mir_mum<exactmul>(mir_get_key_part<bswap>(v, len), p2);
    }
    r = mir_round<exactmul>(r, r);
    PUT_U64<bswap>(r, (uint8_t *)out, 0);
}

//-----------------------------------------------------------------------------
// Also https://github.com/vnmakarov/mir/blob/master/mir-hash.h
REGISTER_FAMILY(mum_mir,
   $.src_url    = "https://github.com/vnmakarov/mum-hash",
   $.src_status = HashFamilyInfo::SRC_FROZEN
 );

REGISTER_HASH(mum1__exact__unroll1,
   $.desc       = "Mum-hash v1, unroll 2^1, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xCB93DE58,
   $.verification_BE = 0xE820D0FB,
   $.hashfn_native   = mum_aligned<1, 1, false, true>,
   $.hashfn_bswap    = mum_aligned<1, 1, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum1__exact__unroll2,
   $.desc       = "Mum-hash v1, unroll 2^2, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x3EEAE2D4,
   $.verification_BE = 0xF23A691C,
   $.hashfn_native   = mum_aligned<1, 2, false, true>,
   $.hashfn_bswap    = mum_aligned<1, 2, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum1__exact__unroll3,
   $.desc       = "Mum-hash v1, unroll 2^3, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x7C0A2F98,
   $.verification_BE = 0x210F4BEB,
   $.hashfn_native   = mum_aligned<1, 3, false, true>,
   $.hashfn_bswap    = mum_aligned<1, 3, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum1__exact__unroll4,
   $.desc       = "Mum-hash v1, unroll 2^4, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x280B2CC6,
   $.verification_BE = 0x0609C4A6,
   $.hashfn_native   = mum_aligned<1, 4, false, true>,
   $.hashfn_bswap    = mum_aligned<1, 4, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum1__inexact__unroll1,
   $.desc       = "Mum-hash v1, unroll 2^1, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x689214DF,
   $.verification_BE = 0x14FBDFDD,
   $.hashfn_native   = mum_aligned<1, 1, false, false>,
   $.hashfn_bswap    = mum_aligned<1, 1, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum1__inexact__unroll2,
   $.desc       = "Mum-hash v1, unroll 2^2, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xA973C6C0,
   $.verification_BE = 0x9C12DFA3,
   $.hashfn_native   = mum_aligned<1, 2, false, false>,
   $.hashfn_bswap    = mum_aligned<1, 2, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum1__inexact__unroll3,
   $.desc       = "Mum-hash v1, unroll 2^3, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x5FC8FC51,
   $.verification_BE = 0x907AB469,
   $.hashfn_native   = mum_aligned<1, 3, false, false>,
   $.hashfn_bswap    = mum_aligned<1, 3, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum1__inexact__unroll4,
   $.desc       = "Mum-hash v1, unroll 2^4, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x2EF256D3,
   $.verification_BE = 0xBF27AAE6,
   $.hashfn_native   = mum_aligned<1, 4, false, false>,
   $.hashfn_bswap    = mum_aligned<1, 4, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

#if defined(NOTYET)
REGISTER_HASH(mum1_realign__exact__unroll1,
   $.desc       = "Mum-hash v1, unroll 2^1, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x9E323D13,
   $.verification_BE = 0x2E655802,
   $.hashfn_native   = mum_realign<1, 1, false, true>,
   $.hashfn_bswap    = mum_realign<1, 1, true, true>
 );

REGISTER_HASH(mum1_realign__exact__unroll2,
   $.desc       = "Mum-hash v1, unroll 2^2, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x139A630F,
   $.verification_BE = 0x2281185A,
   $.hashfn_native   = mum_realign<1, 2, false, true>,
   $.hashfn_bswap    = mum_realign<1, 2, true, true>
 );

REGISTER_HASH(mum1_realign__exact__unroll3,
   $.desc       = "Mum-hash v1, unroll 2^3, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x0F1AC6C6,
   $.verification_BE = 0xE8BF6CE3,
   $.hashfn_native   = mum_realign<1, 3, false, true>,
   $.hashfn_bswap    = mum_realign<1, 3, true, true>
 );

REGISTER_HASH(mum1_realign__exact__unroll4,
   $.desc       = "Mum-hash v1, unroll 2^4, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xF47885FE,
   $.verification_BE = 0xA7961551,
   $.hashfn_native   = mum_realign<1, 4, false, true>,
   $.hashfn_bswap    = mum_realign<1, 4, true, true>
 );

REGISTER_HASH(mum1_realign__inexact__unroll1,
   $.desc       = "Mum-hash v1, unroll 2^1, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xE11FC923,
   $.verification_BE = 0x99623861,
   $.hashfn_native   = mum_realign<1, 1, false, false>,
   $.hashfn_bswap    = mum_realign<1, 1, true, false>
 );

REGISTER_HASH(mum1_realign__inexact__unroll2,
   $.desc       = "Mum-hash v1, unroll 2^2, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xBAFC050E,
   $.verification_BE = 0x9678D798,
   $.hashfn_native   = mum_realign<1, 2, false, false>,
   $.hashfn_bswap    = mum_realign<1, 2, true, false>
 );

REGISTER_HASH(mum1_realign__inexact__unroll3,
   $.desc       = "Mum-hash v1, unroll 2^3, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x56FA3D86,
   $.verification_BE = 0x8EDC90F0,
   $.hashfn_native   = mum_realign<1, 3, false, false>,
   $.hashfn_bswap    = mum_realign<1, 3, true, false>
 );

REGISTER_HASH(mum1_realign__inexact__unroll4,
   $.desc       = "Mum-hash v1, unroll 2^4, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x59787144,
   $.verification_BE = 0xFCAEA377,
   $.hashfn_native   = mum_realign<1, 4, false, false>,
   $.hashfn_bswap    = mum_realign<1, 4, true, false>
 );
#endif

REGISTER_HASH(mum2__exact__unroll1,
   $.desc       = "Mum-hash v2, unroll 2^1, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x9B36F94C,
   $.verification_BE = 0x50F10B41,
   $.hashfn_native   = mum_aligned<2, 1, false, true>,
   $.hashfn_bswap    = mum_aligned<2, 1, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum2__exact__unroll2,
   $.desc       = "Mum-hash v2, unroll 2^2, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x40427228,
   $.verification_BE = 0x43DB198B,
   $.hashfn_native   = mum_aligned<2, 2, false, true>,
   $.hashfn_bswap    = mum_aligned<2, 2, true, true>,
   $.badseeddesc     = "All seeds have byte pairs which produce collisions on some lengths (e.g. 0x08 vs. 0x7f on 32-byte keys)"
 );

REGISTER_HASH(mum2__exact__unroll3,
   $.desc       = "Mum-hash v2, unroll 2^3, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xB5D1CB5C,
   $.verification_BE = 0xA718EDE8,
   $.hashfn_native   = mum_aligned<2, 3, false, true>,
   $.hashfn_bswap    = mum_aligned<2, 3, true, true>,
   $.badseeddesc     = "All seeds have byte pairs which produce collisions on some lengths (e.g. 0x08 vs. 0x7f on 32-byte keys)"
 );

REGISTER_HASH(mum2__exact__unroll4,
   $.desc       = "Mum-hash v2, unroll 2^4, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x59AEDABF,
   $.verification_BE = 0x3B1A2832,
   $.hashfn_native   = mum_aligned<2, 4, false, true>,
   $.hashfn_bswap    = mum_aligned<2, 4, true, true>,
   $.badseeddesc     = "All seeds have byte pairs which produce collisions on some lengths (e.g. 0x08 vs. 0x7f on 32-byte keys)"
 );

REGISTER_HASH(mum2__inexact__unroll1,
   $.desc       = "Mum-hash v2, unroll 2^1, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x1CC6D1E3,
   $.verification_BE = 0x297D8E45,
   $.hashfn_native   = mum_aligned<2, 1, false, false>,
   $.hashfn_bswap    = mum_aligned<2, 1, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum2__inexact__unroll2,
   $.desc       = "Mum-hash v2, unroll 2^2, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x62325A27,
   $.verification_BE = 0x5324AEEA,
   $.hashfn_native   = mum_aligned<2, 2, false, false>,
   $.hashfn_bswap    = mum_aligned<2, 2, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum2__inexact__unroll3,
   $.desc       = "Mum-hash v2, unroll 2^3, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xF4DD9947,
   $.verification_BE = 0x98C9448F,
   $.hashfn_native   = mum_aligned<2, 3, false, false>,
   $.hashfn_bswap    = mum_aligned<2, 3, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum2__inexact__unroll4,
   $.desc       = "Mum-hash v2, unroll 2^4, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x62C46C55,
   $.verification_BE = 0x0E9DDA53,
   $.hashfn_native   = mum_aligned<2, 4, false, false>,
   $.hashfn_bswap    = mum_aligned<2, 4, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

#if defined(NOTYET)
REGISTER_HASH(mum2_realign__exact__unroll1,
   $.desc       = "Mum-hash v2, unroll 2^1, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x3A8751BE,
   $.verification_BE = 0xA3C3C380,
   $.hashfn_native   = mum_realign<2, 1, false, true>,
   $.hashfn_bswap    = mum_realign<2, 1, true, true>
 );

REGISTER_HASH(mum2_realign__exact__unroll2,
   $.desc       = "Mum-hash v2, unroll 2^2, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x7C85EF5A,
   $.verification_BE = 0xE99D6D79,
   $.hashfn_native   = mum_realign<2, 2, false, true>,
   $.hashfn_bswap    = mum_realign<2, 2, true, true>
 );

REGISTER_HASH(mum2_realign__exact__unroll3,
   $.desc       = "Mum-hash v2, unroll 2^3, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x93F25600,
   $.verification_BE = 0xE13A6F00,
   $.hashfn_native   = mum_realign<2, 3, false, true>,
   $.hashfn_bswap    = mum_realign<2, 3, true, true>
 );

REGISTER_HASH(mum2_realign__exact__unroll4,
   $.desc       = "Mum-hash v2, unroll 2^4, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xA0DC8DF8,
   $.verification_BE = 0x6B746384,
   $.hashfn_native   = mum_realign<2, 4, false, true>,
   $.hashfn_bswap    = mum_realign<2, 4, true, true>
 );

REGISTER_HASH(mum2_realign__inexact__unroll1,
   $.desc       = "Mum-hash v2, unroll 2^1, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x2D06BA6A,
   $.verification_BE = 0xF0F929DF,
   $.hashfn_native   = mum_realign<2, 1, false, false>,
   $.hashfn_bswap    = mum_realign<2, 1, true, false>
 );

REGISTER_HASH(mum2_realign__inexact__unroll2,
   $.desc       = "Mum-hash v2, unroll 2^2, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xF645F70A,
   $.verification_BE = 0xC384782D,
   $.hashfn_native   = mum_realign<2, 2, false, false>,
   $.hashfn_bswap    = mum_realign<2, 2, true, false>
 );

REGISTER_HASH(mum2_realign__inexact__unroll3,
   $.desc       = "Mum-hash v2, unroll 2^3, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xA8F0601A,
   $.verification_BE = 0x5F5895AB,
   $.hashfn_native   = mum_realign<2, 3, false, false>,
   $.hashfn_bswap    = mum_realign<2, 3, true, false>
 );

REGISTER_HASH(mum2_realign__inexact__unroll4,
   $.desc       = "Mum-hash v2, unroll 2^4, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x53A9484D,
   $.verification_BE = 0x4C6EBD7D,
   $.hashfn_native   = mum_realign<2, 4, false, false>,
   $.hashfn_bswap    = mum_realign<2, 4, true, false>
 );
#endif

REGISTER_HASH(mum3__exact__unroll1,
   $.desc       = "Mum-hash v3, unroll 2^1, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x3D14C6E2,
   $.verification_BE = 0x360A792D,
   $.hashfn_native   = mum_aligned<3, 1, false, true>,
   $.hashfn_bswap    = mum_aligned<3, 1, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum3__exact__unroll2,
   $.desc       = "Mum-hash v3, unroll 2^2, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x3A556EB2,
   $.verification_BE = 0x752891D0,
   $.hashfn_native   = mum_aligned<3, 2, false, true>,
   $.hashfn_bswap    = mum_aligned<3, 2, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes)"
 );

REGISTER_HASH(mum3__exact__unroll3,
   $.desc       = "Mum-hash v3, unroll 2^3, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x8BD72B8C,
   $.verification_BE = 0xDD8DD247,
   $.hashfn_native   = mum_aligned<3, 3, false, true>,
   $.hashfn_bswap    = mum_aligned<3, 3, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes)"
 );

REGISTER_HASH(mum3__exact__unroll4,
   $.desc       = "Mum-hash v3, unroll 2^4, exact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x0AD998DF,
   $.verification_BE = 0x05832709,
   $.hashfn_native   = mum_aligned<3, 4, false, true>,
   $.hashfn_bswap    = mum_aligned<3, 4, true, true>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mum3__inexact__unroll1,
   $.desc       = "Mum-hash v3, unroll 2^1, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x475D666B,
   $.verification_BE = 0xE75B31F7,
   $.hashfn_native   = mum_aligned<3, 1, false, false>,
   $.hashfn_bswap    = mum_aligned<3, 1, true, false>,
   $.badseeddesc     = "All seeds give zero hashes on keys of all zero bytes if len+seed==0"
 );

REGISTER_HASH(mum3__inexact__unroll2,
   $.desc       = "Mum-hash v3, unroll 2^2, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xF6E13B23,
   $.verification_BE = 0x7B00F4F6,
   $.hashfn_native   = mum_aligned<3, 2, false, false>,
   $.hashfn_bswap    = mum_aligned<3, 2, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes)"
 );

REGISTER_HASH(mum3__inexact__unroll3,
   $.desc       = "Mum-hash v3, unroll 2^3, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xB5560703,
   $.verification_BE = 0x1220D737,
   $.hashfn_native   = mum_aligned<3, 3, false, false>,
   $.hashfn_bswap    = mum_aligned<3, 3, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes)"
 );

REGISTER_HASH(mum3__inexact__unroll4,
   $.desc       = "Mum-hash v3, unroll 2^4, inexact mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xE96A20C0,
   $.verification_BE = 0xE784308C,
   $.hashfn_native   = mum_aligned<3, 4, false, false>,
   $.hashfn_bswap    = mum_aligned<3, 4, true, false>,
   $.badseeddesc     = "All seeds collide on keys of all 0x00 versus all 0xFF for some lengths (e.g. 32 bytes, 80 bytes)"
 );

#if defined(NOTYET)
REGISTER_HASH(mum3_realign__exact__unroll1,
   $.desc       = "Mum-hash v3, unroll 2^1, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x26B6E56E,
   $.verification_BE = 0x3395CE6B,
   $.hashfn_native   = mum_realign<3, 1, false, true>,
   $.hashfn_bswap    = mum_realign<3, 1, true, true>
 );

REGISTER_HASH(mum3_realign__exact__unroll2,
   $.desc       = "Mum-hash v3, unroll 2^2, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x6A60097E,
   $.verification_BE = 0xF7ABC648,
   $.hashfn_native   = mum_realign<3, 2, false, true>,
   $.hashfn_bswap    = mum_realign<3, 2, true, true>
 );

REGISTER_HASH(mum3_realign__exact__unroll3,
   $.desc       = "Mum-hash v3, unroll 2^3, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xD45801EE,
   $.verification_BE = 0x1D6D8F1C,
   $.hashfn_native   = mum_realign<3, 3, false, true>,
   $.hashfn_bswap    = mum_realign<3, 3, true, true>
 );

REGISTER_HASH(mum3_realign__exact__unroll4,
   $.desc       = "Mum-hash v3, unroll 2^4, exact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x65C49B24,
   $.verification_BE = 0xE1C2CEEC,
   $.hashfn_native   = mum_realign<3, 4, false, true>,
   $.hashfn_bswap    = mum_realign<3, 4, true, true>
 );

REGISTER_HASH(mum3_realign__inexact__unroll1,
   $.desc       = "Mum-hash v3, unroll 2^1, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xFB3DE98D,
   $.verification_BE = 0xBBF8D76F,
   $.hashfn_native   = mum_realign<3, 1, false, false>,
   $.hashfn_bswap    = mum_realign<3, 1, true, false>
 );

REGISTER_HASH(mum3_realign__inexact__unroll2,
   $.desc       = "Mum-hash v3, unroll 2^2, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xBFD7CE56,
   $.verification_BE = 0x134317BB,
   $.hashfn_native   = mum_realign<3, 2, false, false>,
   $.hashfn_bswap    = mum_realign<3, 2, true, false>
 );

REGISTER_HASH(mum3_realign__inexact__unroll3,
   $.desc       = "Mum-hash v3, unroll 2^3, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x68CB735E,
   $.verification_BE = 0x47E5152C,
   $.hashfn_native   = mum_realign<3, 3, false, false>,
   $.hashfn_bswap    = mum_realign<3, 3, true, false>
 );

REGISTER_HASH(mum3_realign__inexact__unroll4,
   $.desc       = "Mum-hash v3, unroll 2^4, inexact mult, for aligned-only reads",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_ROTATE               |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x4975BD5E,
   $.verification_BE = 0x8A467520,
   $.hashfn_native   = mum_realign<3, 4, false, false>,
   $.hashfn_bswap    = mum_realign<3, 4, true, false>
 );
#endif

REGISTER_HASH(mir__exact,
   $.desc       = "MIR-hash, exact 128-bit mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_128      |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x00A393C8,
   $.verification_BE = 0x39F99A44,
   $.hashfn_native   = mir_hash<false, true>,
   $.hashfn_bswap    = mir_hash<true, true>,
   $.badseeddesc     = "All seeds produce many collisions on certain key lengths (e.g. 32 bytes, 80 bytes)"
 );

REGISTER_HASH(mir__inexact,
   $.desc       = "MIR-hash, inexact 128-bit mult",
   $.hash_flags =
         0,
   $.impl_flags =
         FLAG_IMPL_MULTIPLY_64_64      |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x422A66FC,
   $.verification_BE = 0xA9A6A383,
   $.hashfn_native   = mir_hash<false, false>,
   $.hashfn_bswap    = mir_hash<true, false>,
   $.seedfixfn       = excludeBadseeds,
   $.badseeddesc     = "All seeds give zero hashes on keys of all zero bytes if len+seed==0"
 );
/* ===================== key-free family driver ===================== */
#include <cstdlib>
#include <cmath>
#include <functional>
#include <string>
static uint64_t sm_state;
static uint64_t splitmix64(void) { uint64_t z = (sm_state += UINT64_C(0x9e3779b97f4a7c15));
  z = (z ^ (z >> 30)) * UINT64_C(0xbf58476d1ce4e5b9); z = (z ^ (z >> 27)) * UINT64_C(0x94d049bb133111eb); return z ^ (z >> 31); }
static uint64_t xs[4];
static inline uint64_t rotl_(uint64_t x, int k) { return (x << k) | (x >> (64 - k)); }
static void rng_init(uint64_t s) { sm_state = s; for (int i = 0; i < 4; i++) xs[i] = splitmix64(); }
static inline uint64_t rng64(void) { const uint64_t r = rotl_(xs[1] * 5, 7) * 9, t = xs[1] << 17;
  xs[2] ^= xs[0]; xs[3] ^= xs[1]; xs[1] ^= xs[2]; xs[0] ^= xs[3]; xs[2] ^= t; xs[3] = rotl_(xs[3], 45); return r; }
static std::vector<uint8_t> unhex(const char *h) { std::vector<uint8_t> v; size_t n = strlen(h);
  for (size_t i = 0; i + 1 < n; i += 2) { unsigned b; sscanf(h + i, "%2x", &b); v.push_back((uint8_t)b); } return v; }
static std::string tohex(const uint8_t *p, size_t n) { std::string s; char b[3]; for (size_t i = 0; i < n; i++) { snprintf(b, 3, "%02x", p[i]); s += b; } return s; }
/* 95% Clopper-Pearson interval, closed forms for the two edge cases, bisection otherwise */
static double betainc_cdf(double x, double a, double b) { /* simple numerical integration fallback */
  const int N = 20000; double s = 0, lb = lgamma(a + b) - lgamma(a) - lgamma(b);
  for (int i = 0; i < N; i++) { double t = x * (i + 0.5) / N; s += exp(lb + (a - 1) * log(t) + (b - 1) * log1p(-t)); } return s * x / N; }
static void cp95(uint64_t k, uint64_t n, double *lo, double *hi) {
  if (k == n) { *hi = 1; *lo = pow(0.025, 1.0 / (double)n); if (k == 0) *lo = 0; return; }
  if (k == 0) { *lo = 0; *hi = 1 - pow(0.025, 1.0 / (double)n); return; }
  /* normal approximation (only used for 0<k<n, not needed for key-free rows) */
  double p = (double)k / n, se = sqrt(p * (1 - p) / n); *lo = p - 1.96 * se; *hi = p + 1.96 * se; (void)betainc_cdf; }
typedef std::function<void(const uint8_t *, size_t, uint64_t, uint64_t, uint8_t *)> HFn; /* msg,len,seedA,seedB,out */
static int g_fail = 0;
static void check_verif(const char *name, uint32_t expect) {
  const HashInfo *h = findHash(name); if (!h) { printf("MISSING %s\n", name); g_fail = 1; return; }
  uint32_t v = sm3_verification(h);
  printf("verification %-24s computed %08X expected %08X registered %08X %s\n", name, v, expect, h->verification_LE,
         (v == expect && v == h->verification_LE) ? "OK" : "MISMATCH");
  if (v != expect || v != h->verification_LE) g_fail = 1;
}
static HFn sm3fn(const char *name) { const HashInfo *h = findHash(name); HashFn f = h->hashfn_native;
  return [f](const uint8_t *m, size_t n, uint64_t s, uint64_t, uint8_t *o) { f(m, n, (seed_t)s, o); }; }
/* seed models: 64 = uniform 64-bit, 32 = uniform 32-bit zero-extended, 128 = two independent 64-bit seeds */
static uint64_t run_pair(const char *label, HFn f, unsigned outbytes, int seedbits, const char *mh, const char *mph,
                         unsigned logN, bool control, int cidx = -1) {
  std::vector<uint8_t> a = unhex(mh), b = unhex(mph);
  if (control) { if (cidx < 0) b.back() ^= 0x01; else b[cidx] ^= 0x01; }
  uint64_t N = 1ULL << logN, hits = 0, exs = 0, exs2 = 0; bool have = false; uint8_t oa[64], ob[64], ea[64] = {0};
  for (uint64_t t = 0; t < N; t++) {
    uint64_t s1 = rng64(), s2 = seedbits == 128 ? rng64() : 0; if (seedbits == 32) s1 &= 0xffffffffULL;
    f(a.data(), a.size(), s1, s2, oa); f(b.data(), b.size(), s1, s2, ob);
    if (!memcmp(oa, ob, outbytes)) { hits++; if (!have) { have = true; exs = s1; exs2 = s2; memcpy(ea, oa, outbytes); } }
  }
  double lo, hi; cp95(hits, N, &lo, &hi);
  printf("%-34s %s seed%-3d |m|=%zu |m'|=%zu L=%zu  %llu/%llu  rate=%.6f  95%%CI[%.8f,%.8f]",
         label, control ? "CONTROL" : "PAIR   ", seedbits, a.size(), b.size(), (std::max(a.size(), b.size()) + 7) / 8,
         (unsigned long long)hits, (unsigned long long)N, (double)hits / N, lo, hi);
  if (have) { printf("  ex seed=%016llx", (unsigned long long)exs); if (seedbits == 128) printf(",%016llx", (unsigned long long)exs2);
    printf(" out=%s", tohex(ea, outbytes).c_str()); }
  printf("\n"); fflush(stdout);
  return hits;
}
/* key-free expectation: all N collide; control: none */
static void expect_keyfree(const char *label, HFn f, unsigned ob, int sb, const char *m, const char *mp, unsigned logN, int cidx = -1) {
  uint64_t h = run_pair(label, f, ob, sb, m, mp, logN, false);
  if (h != (1ULL << logN)) { printf("  !! not every seed\n"); g_fail = 1; }
  uint64_t c = run_pair(label, f, ob, sb, m, mp, logN > 16 ? 16 : logN, true, cidx);
  if (c != 0) { printf("  !! control collided\n"); }
}
/* ---- multicollision set checker: every member must equal member 0 on the full output ---- */
#include <algorithm>
#include <unordered_set>
static uint64_t check_family(const char *label, HFn f, unsigned outbytes, int seedbits,
                             const std::vector<std::vector<uint8_t>> &S, unsigned logK) {
  { std::vector<std::vector<uint8_t>> T = S; std::sort(T.begin(), T.end());
    size_t d = std::unique(T.begin(), T.end()) - T.begin();
    size_t mx = 0; for (auto &m : S) mx = std::max(mx, m.size());
    printf("%s: family of %zu messages, %zu distinct, max length %zu bytes (L=%zu)\n", label, S.size(), d, mx, (mx + 7) / 8);
    if (d != S.size()) { printf("  !! duplicate members\n"); g_fail = 1; } }
  uint64_t K = 1ULL << logK, all = 0, lo16 = 0; uint8_t o0[64], o[64]; uint64_t ex = 0; bool have = false; uint8_t eo[64];
  size_t minlargest = S.size();
  for (uint64_t t = 0; t < K; t++) {
    uint64_t s1 = rng64(), s2 = seedbits == 128 ? rng64() : 0; if (seedbits == 32) s1 &= 0xffffffffULL;
    f(S[0].data(), S[0].size(), s1, s2, o0); size_t same = 1, same16 = 1;
    for (size_t i = 1; i < S.size(); i++) { f(S[i].data(), S[i].size(), s1, s2, o);
      if (!memcmp(o, o0, outbytes)) same++; if (!memcmp(o, o0, 2)) same16++; }
    if (same == S.size()) { all++; if (!have) { have = true; ex = s1; memcpy(eo, o0, outbytes); } }
    if (same16 == S.size()) lo16++;
    minlargest = std::min(minlargest, same);
  }
  double lo, hi; cp95(all, K, &lo, &hi);
  printf("  keys where ALL %zu members share the full %u-bit output: %llu/%llu (95%%CI [%.6f,1]); low-16-bit agreement %llu/%llu; min members sharing member 0's value over keys: %zu\n",
         S.size(), outbytes * 8, (unsigned long long)all, (unsigned long long)K, lo, (unsigned long long)lo16, (unsigned long long)K, minlargest);
  if (have) printf("  example key %016llx -> common output %s\n", (unsigned long long)ex, tohex(eo, outbytes).c_str());
  for (int i = 0; i < 3 && i < (int)S.size(); i++) printf("  member[%d] = %s\n", i, tohex(S[i].data(), S[i].size()).c_str());
  printf("  member[%zu] = %s\n", S.size() - 1, tohex(S.back().data(), S.back().size()).c_str());
  if (all != K) g_fail = 1;
  fflush(stdout); return all;
}
/* MUM v3 and mir at 9..15 bytes: the seed enters only as a length-dependent term; the message enters as
 * fold(w0, p) ^ fold(tail, q) with fold(a,b) = hi64(ab) + lo64(ab) (exact) -- public.  Fix X, choose the t-byte
 * tail freely and solve fold(w0, p) = X ^ fold(tail, q): fold(w,p) is w*p mod 2^64-1 or one less, so the
 * candidates are y*p^-1 and (y+1)*p^-1 mod 2^64-1 (plus 2^64-1 for 0), each checked. */
typedef unsigned __int128 u128;
static const uint64_t MM = ~UINT64_C(0);
static uint64_t mulmodM(uint64_t a, uint64_t b) { u128 r = (u128)a * b; uint64_t lo = (uint64_t)r, hi = (uint64_t)(r >> 64);
  uint64_t s = lo + hi; if (s < lo) s++; if (s == MM) s = 0; return s; }
static bool invmodM(uint64_t p, uint64_t *inv) { /* extended Euclid on 64-bit, modulus 2^64-1 */
  __int128 t = 0, nt = 1; u128 r = MM, nr = p % MM;
  while (nr) { u128 q = r / nr; __int128 tmp = t - (__int128)q * nt; t = nt; nt = tmp; u128 tr = r - q * nr; r = nr; nr = tr; }
  if (r != 1) return false; if (t < 0) t += MM; *inv = (uint64_t)t; return true; }
template <bool exact> static uint64_t fold(uint64_t a, uint64_t b) { return _mum<exact>(a, b); }
static std::vector<uint64_t> solve(uint64_t y, uint64_t p, uint64_t pinv) {
  std::vector<uint64_t> out; uint64_t cands[4]; int n = 0;
  cands[n++] = mulmodM(y % MM, pinv); cands[n++] = mulmodM((y + 1) % MM, pinv);
  for (int i = 0; i < 2; i++) if (cands[i] == 0) cands[n++] = MM;
  std::sort(cands, cands + n); n = std::unique(cands, cands + n) - cands;
  for (int i = 0; i < n; i++) if (fold<true>(cands[i], p) == y) out.push_back(cands[i]);
  return out; }
static uint64_t mir_tailpart(const uint8_t *v, size_t len) { return mir_get_key_part<false>(v, len); }
int main(int argc, char **argv) {
  unsigned logN = argc > 1 ? atoi(argv[1]) : 12; rng_init(argc > 2 ? strtoull(argv[2], 0, 0) : UINT64_C(0x0f550b));
  check_verif("mum3__exact__unroll3", 0x8BD72B8C); check_verif("mum3__exact__unroll4", 0x0AD998DF);
  check_verif("mir__exact", 0x00A393C8); check_verif("mir__inexact", 0x422A66FC); if (g_fail) return 1;
  uint64_t pinv; if (!invmodM(_mum_primes[0], &pinv)) { printf("p0 not invertible\n"); return 1; }
  /* MUM: 10 bytes = word0 (p0) + 2-byte tail (tail prime).  Try targets until >= 2^16 members. */
  for (int attempt = 0; attempt < 16; attempt++) {
    uint64_t X = rng64(); std::vector<std::vector<uint8_t>> S;
    for (uint64_t t = 0; t < 65536; t++) {
      uint64_t y = X ^ fold<true>(t, _mum_tail_prime);
      for (uint64_t w : solve(y, _mum_primes[0], pinv)) { std::vector<uint8_t> m(10); memcpy(m.data(), &w, 8); m[8] = (uint8_t)t; m[9] = (uint8_t)(t >> 8); S.push_back(m); }
    }
    printf("MUM target %016llx: %zu members at 10 bytes\n", (unsigned long long)X, S.size());
    if (S.size() < 65536) continue;
    S.resize(65536);
    check_family("MUM v3 exact 10-byte family (unroll3)", sm3fn("mum3__exact__unroll3"), 8, 64, S, logN);
    check_family("  MUM v3 exact (unroll4)", sm3fn("mum3__exact__unroll4"), 8, 64, S, logN);
    break;
  }
  uint64_t p1inv; if (!invmodM(p1, &p1inv)) { printf("p1 not invertible\n"); return 1; }
  for (int attempt = 0; attempt < 16; attempt++) {
    uint64_t X = rng64(); std::vector<std::vector<uint8_t>> S;
    for (uint64_t t = 0; t < 65536; t++) {
      uint8_t tb[2] = {(uint8_t)t, (uint8_t)(t >> 8)};
      uint64_t y = X ^ fold<true>(mir_tailpart(tb, 2), p2);
      for (uint64_t w : solve(y, p1, p1inv)) { std::vector<uint8_t> m(10); memcpy(m.data(), &w, 8); m[8] = tb[0]; m[9] = tb[1]; S.push_back(m); }
    }
    printf("mir target %016llx: %zu members at 10 bytes\n", (unsigned long long)X, S.size());
    if (S.size() < 65536) continue;
    S.resize(65536);
    check_family("mir.exact 10-byte family", sm3fn("mir__exact"), 8, 64, S, logN);
    break;
  }
  /* mir.inexact: keep members whose inexact terms equal the exact ones (11 bytes, 3-byte tail, first 2^16 kept) */
  { uint64_t X = rng64(); std::vector<std::vector<uint8_t>> S;
    for (uint64_t t = 0; t < (1u << 24) && S.size() < 65536; t++) {
      uint8_t tb[3] = {(uint8_t)t, (uint8_t)(t >> 8), (uint8_t)(t >> 16)}; uint64_t tp = mir_tailpart(tb, 3);
      if (mir_mum<false>(tp, p2) != mir_mum<true>(tp, p2)) continue;
      uint64_t y = X ^ fold<true>(tp, p2);
      for (uint64_t w : solve(y, p1, p1inv)) { if (mir_mum<false>(w, p1) != mir_mum<true>(w, p1)) continue;
        std::vector<uint8_t> m(11); memcpy(m.data(), &w, 8); memcpy(m.data() + 8, tb, 3); S.push_back(m); }
    }
    S.resize(std::min<size_t>(S.size(), 65536));
    check_family("mir exact AND inexact 11-byte family", sm3fn("mir__exact"), 8, 64, S, logN);
    check_family("  mir.inexact", sm3fn("mir__inexact"), 8, 64, S, logN); }
  /* MUM inexact: same idea at 11 bytes */
  { uint64_t X = rng64(); std::vector<std::vector<uint8_t>> S;
    for (uint64_t t = 0; t < (1u << 24) && S.size() < 65536; t++) {
      if (fold<false>(t, _mum_tail_prime) != fold<true>(t, _mum_tail_prime)) continue;
      uint64_t y = X ^ fold<true>(t, _mum_tail_prime);
      for (uint64_t w : solve(y, _mum_primes[0], pinv)) { if (fold<false>(w, _mum_primes[0]) != fold<true>(w, _mum_primes[0])) continue;
        std::vector<uint8_t> m(11); memcpy(m.data(), &w, 8); m[8] = (uint8_t)t; m[9] = (uint8_t)(t >> 8); m[10] = (uint8_t)(t >> 16); S.push_back(m); }
    }
    S.resize(std::min<size_t>(S.size(), 65536));
    check_family("MUM v3 exact AND inexact 11-byte family (unroll3)", sm3fn("mum3__exact__unroll3"), 8, 64, S, logN);
    check_family("  MUM v3 inexact (unroll3)", sm3fn("mum3__inexact__unroll3"), 8, 64, S, logN); }
  /* every length 9..400: build one key-free equal-length pair per length and test 1024 seeds.
   * MUM v3 (unroll3 = 64-byte blocks): if the final segment (after the "while len > 64" loop) has >= 9 bytes,
   * change its last byte and re-solve its word 0 (prime p0); otherwise change word 1 of the last full block and
   * re-solve word 0 of that block through fold((w0^p0)(w1^p1)) (candidates y*(w1^p1)^-1 mod 2^64-1).
   * mir: change the last byte; if len%16 in 9..15 re-solve the final word (p1), else re-solve word 0 of the last
   * full 16-byte block so that fold(w0,p1) ^ fold(w1,p2) is unchanged. */
  auto get64 = [](const std::vector<uint8_t> &m, size_t off) { uint64_t v; memcpy(&v, &m[off], 8); return v; };
  auto put64 = [](std::vector<uint8_t> &m, size_t off, uint64_t v) { memcpy(&m[off], &v, 8); };
  { HashFn hf = findHash("mum3__exact__unroll3")->hashfn_native; unsigned okl = 0, nl = 0;
    for (size_t len = 9; len <= 400; len++) {
      bool done = false;
      for (int attempt = 0; attempt < 64 && !done; attempt++) {
        std::vector<uint8_t> a(len); for (auto &x : a) x = (uint8_t)rng64(); std::vector<uint8_t> b = a;
        size_t rem = len, off = 0; while (rem > 64) { rem -= 64; off += 64; }
        if (rem >= 9) { /* final segment starts at off: words at off, off+8, ...; tail after */
          b[len - 1] ^= 0x5a; size_t nw = rem / 8, tl = rem % 8; uint64_t acc_a = 0, acc_b = 0;
          for (size_t i = 1; i < nw; i++) { acc_a ^= fold<true>(get64(a, off + 8 * i), _mum_primes[i]); acc_b ^= fold<true>(get64(b, off + 8 * i), _mum_primes[i]); }
          if (tl) { uint64_t ta = 0, tb = 0; memcpy(&ta, &a[off + 8 * nw], tl); memcpy(&tb, &b[off + 8 * nw], tl);
            acc_a ^= fold<true>(ta, _mum_tail_prime); acc_b ^= fold<true>(tb, _mum_tail_prime); }
          uint64_t y = fold<true>(get64(a, off), _mum_primes[0]) ^ acc_a ^ acc_b; auto sol = solve(y, _mum_primes[0], pinv);
          if (sol.empty()) continue; put64(b, off, sol[0]);
        } else { size_t bo = off - 64; /* last full block: words bo..bo+56, pairs (0,1) use primes 0,1 */
          uint64_t w0 = get64(a, bo), w1 = get64(a, bo + 8), w1n = w1 ^ 0x5a5a5a5a5a5a5a5aULL;
          uint64_t y = fold<true>(w0 ^ _mum_primes[0], w1 ^ _mum_primes[1]); uint64_t q = w1n ^ _mum_primes[1], qinv;
          if (!invmodM(q, &qinv)) continue; auto sol = solve(y, q, qinv); if (sol.empty()) continue;
          put64(b, bo + 8, w1n); put64(b, bo, sol[0] ^ _mum_primes[0]); }
        if (a == b) continue;
        uint64_t c = 0; uint8_t oa[8], ob[8];
        for (int t = 0; t < 1024; t++) { uint64_t sd = rng64(); hf(a.data(), len, sd, oa); hf(b.data(), len, sd, ob); c += !memcmp(oa, ob, 8); }
        done = true; nl++; okl += (c == 1024);
        if (len == 9 || len == 65 || len == 400) printf("  MUM every-length len %zu: %llu/1024\n", len, (unsigned long long)c);
      }
      if (!done) { nl++; printf("  MUM len %zu: no pair built\n", len); }
    }
    printf("MUM v3 exact unroll3: key-free equal-length pair at every length 9..400: %u/%u lengths collide on 1024/1024 seeds\n", okl, nl); if (okl != nl) g_fail = 1; }
  { HashFn hf = findHash("mir__exact")->hashfn_native; unsigned okl = 0, nl = 0;
    for (size_t len = 9; len <= 400; len++) {
      bool done = false;
      for (int attempt = 0; attempt < 64 && !done; attempt++) {
        std::vector<uint8_t> a(len); for (auto &x : a) x = (uint8_t)rng64(); std::vector<uint8_t> b = a; b[len - 1] ^= 0x5a;
        size_t nb = len / 16, rem = len % 16;
        if (rem >= 9) { size_t o = 16 * nb; uint64_t ta = mir_get_key_part<false>(&a[o + 8], rem - 8), tb = mir_get_key_part<false>(&b[o + 8], rem - 8);
          uint64_t y = fold<true>(get64(a, o), p1) ^ fold<true>(ta, p2) ^ fold<true>(tb, p2); auto sol = solve(y, p1, p1inv); if (sol.empty()) continue; put64(b, o, sol[0]); }
        else { if (nb == 0) break; size_t o = 16 * (nb - 1);
          if (rem == 0) { /* last byte is in w1 of the last block */ uint64_t y = fold<true>(get64(a, o), p1) ^ fold<true>(get64(a, o + 8), p2) ^ fold<true>(get64(b, o + 8), p2);
            auto sol = solve(y, p1, p1inv); if (sol.empty()) continue; put64(b, o, sol[0]); }
          else { b = a; uint64_t w1n = get64(a, o + 8) ^ 0x5a5a5a5a5a5a5a5aULL; uint64_t y = fold<true>(get64(a, o), p1) ^ fold<true>(get64(a, o + 8), p2) ^ fold<true>(w1n, p2);
            auto sol = solve(y, p1, p1inv); if (sol.empty()) continue; put64(b, o + 8, w1n); put64(b, o, sol[0]); } }
        uint64_t c = 0; uint8_t oa[8], ob[8];
        for (int t = 0; t < 1024; t++) { uint64_t sd = rng64(); hf(a.data(), len, sd, oa); hf(b.data(), len, sd, ob); c += !memcmp(oa, ob, 8); }
        done = true; nl++; okl += (c == 1024);
        if (len == 9 || len == 65 || len == 400) printf("  mir every-length len %zu: %llu/1024\n", len, (unsigned long long)c);
      }
      if (!done) { nl++; printf("  mir len %zu: no pair built\n", len); }
    }
    printf("mir.exact: key-free equal-length pair at every length 9..400: %u/%u lengths collide on 1024/1024 seeds\n", okl, nl); if (okl != nl) g_fail = 1; }
  printf(g_fail ? "RESULT: FAIL\n" : "RESULT: PASS\n"); return g_fail;
}
