import ProvenHashes.Polynomial
import ProvenHashes.NH
import ProvenHashes.Tabulation
import ProvenHashes.MultiplyShift
import ProvenHashes.Decoder
import ProvenHashes.Recurrence
import ProvenHashes.Composition

import ProvenHashes.MultiplyAddShift
import ProvenHashes.OddMultiplyShift
import ProvenHashes.MultiplyAddShiftScope
