/* Single-file program generated from: SMHasher3 platform header + include/hashlib/Mathmult.h,
 * SMHasher3 hashes/a5hash.cpp (verbatim, #include lines removed), and the key-free driver below. */
/* === SMHasher3 platform/Platform.h (generated form, clock+thread parts removed) === */
/*
 * DO NOT EDIT THIS FILE
 *
 * It is generated by CMake during build configuration.
 * See <smhasher3>/platform/functions.cmake
 * for documentation on how and why this is generated.
 */
/*
 * SMHasher3
 * Copyright (C) 2021-2022  Frank J. T. Wojcik
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <https://www.gnu.org/licenses/>.
 */
#include <cstdio>    // Allow printf() from anywhere
#include <cstring>   // For memcpy

//-----------------------------------------------------------------------------
// Fixed-width integers (required before all else)
#include <cstdint>
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
typedef unsigned __int128 uint128_t;
typedef          __int128  int128_t;
#pragma GCC diagnostic pop
#define HAVE_INT128
typedef uint64_t  seed_t; 
#define __STDC_FORMAT_MACROS 1 // Some older gcc installations need this
#include <cinttypes>

//-----------------------------------------------------------------------------
// MSVC-specific things (if required)


//-----------------------------------------------------------------------------
// Declarations for Platform.cpp


//-----------------------------------------------------------------------------
// Compiler-specific functions and macros

// Compiler branching hints
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#define expectp(x,p) __builtin_expect_with_probability(!!(x), 1, (p))
#define unpredictable(x) __builtin_unpredictable(x)

// Compiler behavioral bounds hints
#define assume(x) __builtin_assume(x)
#define unreachable() __builtin_unreachable()

// Compiler/CPU data prefetching
#define prefetch(ptr) __builtin_prefetch(ptr)

// Function inlining control
#define FORCE_INLINE __attribute__((__always_inline__)) inline
#define NEVER_INLINE __attribute__((__noinline__))

// Variable aliasing
#define MAY_ALIAS __attribute__((__may_alias__))

// C "restrict" keyword replacement
#define RESTRICT __restrict

// Integer rotation
// CAUTION: These are deliberately unsafe!
// They assume the rotation value is not 0 or >= {32,64}.
// If an invalid rotation amount is given, the result is undefined behavior.
static inline uint32_t _rotl32(uint32_t v, uint8_t n) {
    return (v << n) | (v >> ((-n) & 31));
}
static inline uint32_t _rotr32(uint32_t v, uint8_t n) {
    return (v >> n) | (v << ((-n) & 31));
}
#define ROTL32(v, n) _rotl32(v, n)
#define ROTR32(v, n) _rotr32(v, n)
static inline uint64_t _rotl64(uint64_t v, uint8_t n) {
    return (v << n) | (v >> ((-n) & 63));
}
static inline uint64_t _rotr64(uint64_t v, uint8_t n) {
    return (v >> n) | (v << ((-n) & 63));
}
#define ROTL64(v, n) _rotl64(v, n)
#define ROTR64(v, n) _rotr64(v, n)

// Population count (popcnt/popcount)
#define popcount4(x) __builtin_popcount(x)
#define popcount8(x) __builtin_popcountll(x)

// Leading zero-bit count (ffs/clz)
// CAUTION: Assumes x is not 0!
#define clz4(x) __builtin_clz(x)
#define clz8(x) __builtin_clzll(x)

// Integer byteswapping (endianness conversion)
// You can use the bit-specific ones directly, but the more generic
// versions below are preferred.
#define BSWAP16(x) __builtin_bswap16(x)
#define BSWAP32(x) __builtin_bswap32(x)
#define BSWAP64(x) __builtin_bswap64(x)

//-----------------------------------------------------------------------------
// Generic wrappers for BSWAP*()
template < typename T >
static FORCE_INLINE T BSWAP(T value) {
    switch(sizeof(T)) {
    case 2: value = BSWAP16((uint16_t)value); break;
    case 4: value = BSWAP32((uint32_t)value); break;
    case 8: value = BSWAP64((uint64_t)value); break;
    default: break;
    }
    return value;
}

template < typename T >
static FORCE_INLINE T COND_BSWAP(T value, bool doit) {
    if (!doit || (sizeof(T) < 2)) { return value; }
    return BSWAP(value);
}

//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// User-configurable implementations

// Endianness detection
static FORCE_INLINE bool isLE(void) {
const uint32_t   value = 0xb000000e;
const void *      addr = static_cast<const void *>(&value);
const uint8_t *   lsb  = static_cast<const uint8_t *>(addr);
return ((*lsb) == 0x0e);
}
static FORCE_INLINE bool isBE(void) {
const uint32_t   value = 0xb000000e;
const void *      addr = static_cast<const void *>(&value);
const uint8_t *   lsb  = static_cast<const uint8_t *>(addr);
return ((*lsb) == 0xb0);
}



//-----------------------------------------------------------------------------
// Routines for turning bytes in memory into integers. These move data
// in alignment-safe ways, with optional byte swapping.
//
// memcpy() is the only known way of safely moving data this way;
// "safe" meaning "defined C++ behavior" AND "working regardless of
// alignment". Every memcpy() call here has a fixed size, and modern
// compilers tend to inline these into alignment-safe data moves/loads
// that are best for the platform being compiled for. Earlier
// compilers did not always do this very well, at least on non-x86
// platforms.
//
// If someone ever wanted to allow hashes to use undefined-behavior
// for faster access, this is where different access methods could be
// introduced, such as reading through a union or just doing direct
// memory access by pointer type conversion. Both of those are
// undefined behavior (UB), though! Beware of nasal demons!
//
// It's also plausible to introduce different versions of these which
// handle known-to-be-aligned accesses in a different way, perhaps
// through another template parameter.

template < bool bswap >
static FORCE_INLINE uint64_t GET_U64(const uint8_t * b, const uint32_t i) {
    uint64_t n;
    memcpy(&n, &b[i], 8);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE uint32_t GET_U32(const uint8_t * b, const uint32_t i) {
    uint32_t n;
    memcpy(&n, &b[i], 4);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE uint16_t GET_U16(const uint8_t * b, const uint32_t i) {
    uint16_t n;
    memcpy(&n, &b[i], 2);
    n = COND_BSWAP(n, bswap);
    return n;
}

template < bool bswap >
static FORCE_INLINE void PUT_U16(uint16_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 2);
}

template < bool bswap >
static FORCE_INLINE void PUT_U32(uint32_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 4);
}

template < bool bswap >
static FORCE_INLINE void PUT_U64(uint64_t n, uint8_t * b, const uint32_t i) {
    n = COND_BSWAP(n, bswap);
    memcpy(&b[i], &n, 8);
}

//-----------------------------------------------------------------------------
// Generic vector support
#define VECTOR_SIZE(SZ)  __attribute__ ((vector_size (SZ)))
#define HAVE_GENERIC_VECTOR


//-----------------------------------------------------------------------------
// VLA helper
//
// Allocates on heap when VLA is not available

#if defined(__STDC_NO_VLA__) || defined(_MSC_VER) && !defined(__clang__)
    #include <vector>
    #define VLA_ALLOC(type, name, count) std::vector<type> name(count)
#else
    #define VLA_ALLOC(type, name, count)  \
 _Pragma("GCC diagnostic push");          \
 _Pragma("GCC diagnostic ignored \"-Wvla\""); \
 _Pragma("clang diagnostic ignored \"-Wvla-extension\""); \
 type name[count];                            \
 _Pragma("GCC diagnostic pop");
#endif

//-----------------------------------------------------------------------------
// Debugging helpers
//
// Really wish these could be moved into the CMake generation-time
// detection, but I can't find a reliable way of checking if "-DDEBUG"
// will be passed to the compiler.

#if defined(DEBUG)
  #include <cassert>

  #undef assume
  #define assume(x) assert(x)

  #undef unreachable
  #define unreachable() assert(0)

  #define verify(x) assert(x)
#else
  static void warn_if(bool x, const char * s, const char * fn, uint64_t ln) {
      if (!x) {
          printf("Statement %s is not true: %s:%" PRId64 "\n", s, fn, ln);
      }
  }
  #define verify(x) warn_if(x, #x, __FILE__, __LINE__)
#endif

#define unused(x) (void)(x)

//-----------------------------------------------------------------------------
// Instruction-set architecture header detection, for internal use only

/* #undef HAVE_ARM_NEON */
/* #undef HAVE_ARM_ACLE */
/* #undef HAVE_IMMINTRIN */
/* #undef HAVE_AMMINTRIN */
/* #undef HAVE_X86INTRIN */

//-----------------------------------------------------------------------------
// Instruction-set architecture and platform feature availability

/* #undef HAVE_32BIT_PLATFORM */

/* #undef HAVE_GCC_COMPILER */

/* #undef HAVE_SSE_2 */
/* #undef HAVE_GOOD_LOADU_32 */
/* #undef HAVE_GOOD_LOADU_64 */
/* #undef HAVE_SSSE_3 */
/* #undef HAVE_SSE_4_1 */
/* #undef HAVE_XOP */
/* #undef HAVE_X86_64_CRC32C */
/* #undef HAVE_X86_64_CLMUL */
/* #undef HAVE_X86_64_AES */
/* #undef HAVE_X86_64_SHA1 */
/* #undef HAVE_X86_64_SHA2 */
/* #undef HAVE_AVX */
/* #undef HAVE_AVX2 */
/* #undef HAVE_AVX512_F */
/* #undef HAVE_AVX512_BW */
/* #undef HAVE_AVX512_VL */
/* #undef HAVE_UMULH */
/* #undef HAVE_UMUL128 */
/* #undef HAVE_X86_64_ASM */
/* #undef HAVE_ARM_AES */
/* #undef HAVE_ARM_SHA1 */
/* #undef HAVE_ARM_SHA2 */
/* HAVE_ARM_ASM removed: portable C paths only */
/* HAVE_ARM64_ASM removed */
/* #undef HAVE_PPC_VSX */
/* #undef HAVE_PPC_AES */
/* #undef HAVE_PPC_ASM */

/* === SMHasher3 include/hashlib/Mathmult.h (verbatim) === */
/*
 * Multiplication and addition routines for >=64-bit math,
 * in terms of <=64-bit variables.
 *
 * Copyright (C) 2021-2023  Frank J. T. Wojcik
 * Copyright (C) 2023       jason
 * Copyright (c) 2016 Vladimir Makarov <vmakarov@gcc.gnu.org>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Some of this is based off of code from PMP Multilinear hashes:
 *
 *     Copyright (C) 2021-2022  Frank J. T. Wojcik
 *     Copyright (c) 2014-2021 Reini Urban
 *     Copyright (c) 2014, Dmytro Ivanchykhin, Sergey Ignatchenko, Daniel Lemire
 *     All rights reserved.
 *
 *     Redistribution and use in source and binary forms, with or without
 *     modification, are permitted provided that the following conditions are met:
 *
 *     1. Redistributions of source code must retain the above copyright notice, this
 *        list of conditions and the following disclaimer.
 *     2. Redistributions in binary form must reproduce the above copyright notice,
 *        this list of conditions and the following disclaimer in the documentation
 *        and/or other materials provided with the distribution.
 *
 *     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 *     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *     ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * There are several places here which have different versions of this code
 * for clang, all of which check for that via "defined(__clang__)".
 *
 * This is because clang does not work well with asm constraints. One
 * example is that, given the option, clang has some sort of preference for
 * memory operands. It may spill a register to the stack, and operate on
 * the stack copy. Or it may spill to the stack, operate on the register,
 * and then spill the new value to the stack again, without ever reading or
 * operating on the stack copy even once. Therefore, clang is not given the
 * option of memory operands.
 *
 * This is still true for clang trunk as of July 2023. You can see more
 * about this issue at:
 *    http://stackoverflow.com/questions/16850309/
 *    https://github.com/llvm/llvm-project/issues/20571
 *    https://godbolt.org/z/Wr3EvKnhn
 */

namespace MathMult {

// 32x32->64 multiplication [rhi:rlo = a * b]
static FORCE_INLINE void mult32_64( uint32_t & rlo, uint32_t & rhi, uint32_t a, uint32_t b ) {
    // XXX Are either of these asm blocks better than just the plain code?
#if 0 && defined(HAVE_ARM_ASM)
    __asm__ ("UMULL %w0, %w1, %w2, %w3"
             : "+r" (rlo), "+r" (rhi)
             : "r" (a), "r" (b)
             : "cc", "memory"
    );
#elif 0 && defined(HAVE_X86_64_ASM)
    __asm__ ("mull  %[b]"
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), [b] "rm" (b)
    );
#else
    uint64_t r = (uint64_t)a * (uint64_t)b;
    rhi = (uint32_t)(r >> 32);
    rlo = (uint32_t)r;
#endif
}

// 32x32->64 multiplication [r64 = a32 * b32]
static FORCE_INLINE void mult32_64( uint64_t & r64, uint32_t a32, uint32_t b32 ) {
#if defined(_MSC_VER) && defined(_M_IX86)
    r64 = __emulu(a32, b32);
#else
    r64 = (uint64_t)a32 * (uint64_t)b32;
#endif
}

// 96-bit addition [rhi:rmi:rlo += addhi:addmi:addlo]
static FORCE_INLINE void add96( uint32_t & rlo, uint32_t & rmi, uint32_t & rhi, const uint32_t & addlo,
        const uint32_t & addmi, const uint32_t & addhi ) {
#if defined(HAVE_ARM_ASM)
    __asm__ ("ADDS %w0, %w3, %w0\n\t"
             "ADCS %w1, %w4, %w1\n\t"
             "ADC  %w2, %w5, %w2"
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "r" (addlo), "r" (addmi), "r" (addhi)
             : "cc"
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("addl %3, %0\n\t"
             "adcl %4, %1\n\t"
             "adcl %5, %2"
  #if defined(__clang__)
             : "+r" (rlo),   "+r" (rmi),   "+r" (rhi)
             : "re" (addlo), "re" (addmi), "re" (addhi)
  #else
             : "+g,g,g,g,r,r,r,r" (rlo),  "+g,g,r,r,g,g,r,r" (rmi),  "+g,r,g,r,g,r,g,r" (rhi)
             : "re,re,re,re,m,m,m,m" (addlo), "re,re,m,m,re,re,m,m" (addmi), "re,m,re,m,re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    uint64_t w = (((uint64_t)rmi  ) << 32) + ((uint64_t)rlo  );
    uint64_t r = (((uint64_t)addmi) << 32) + ((uint64_t)addlo) + w;
    rhi += addhi + (r < w);
    rmi  = (uint32_t)(r >> 32);
    rlo  = (uint32_t)(r      );
#endif
}

// 64-bit fused multiply addition [r64 += a * b]
static FORCE_INLINE void fma32_64( uint64_t & r64, uint32_t a, uint32_t b ) {
#if defined(HAVE_ARM_ASM)
    //uint64_t ret;
    __asm__("umaddl %x0, %w1, %w2, %x3" : "=r" (r64) : "r" (a), "r" (b), "r" (r64));
    //r64 = ret;
#else
    uint64_t v;
    MathMult::mult32_64(v, a, b);
    r64 += v;
#endif
}

// 96-bit fused multiply addition [rhi:rmi:rlo += a * b]
static FORCE_INLINE void fma32_96( uint32_t & rlo, uint32_t & rmi, uint32_t & rhi, uint32_t a, uint32_t b ) {
// These #defines are not correct; some arm seems to not support this
#if 0 && defined(HAVE_ARM_ASM)
    uint32_t tmphi, tmplo;
    __asm__ ("UMULL %w3, %w4, %w5, %w6\n\t"
             "ADDS  %w0, %w3, %w0\n\t"
             "ADCS  %w1, %w4, %w1\n\t"
             "ADC   %w2, %w2, #0x0"
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "r" (a), "r" (b)
             : "cc"
    );
#elif defined(HAVE_X86_64_ASM)
    uint32_t tmplo, tmphi;
    __asm__ ("mull %6\n\t"
             "addl %%eax, %0\n\t"
             "adcl %%edx, %1\n\t"
             "adcl $0, %2"
  #if defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc"
    );
#else
    uint32_t tmplo, tmpmi, tmphi = 0;
    mult32_64(tmplo, tmpmi, a, b);
    add96(rlo, rmi, rhi, tmplo, tmpmi, tmphi);
#endif
}

// 64x64->128 multiplication [rhi:rlo = a * b]
static FORCE_INLINE void mult64_128( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_UMUL128)
    rlo = _umul128(a, b, &rhi);
#elif defined(HAVE_UMULH)
    rlo = a * b;
    rhi = __umulh(a, b);
#elif defined(HAVE_ARM64_ASM)
    /*
     * AARCH64 needs 2 insns to calculate 128-bit result of the
     * multiplication.  If we use a generic code we actually call a
     * function doing 128x128->128 bit multiplication. The function
     * is very slow.
     */
    rlo = a * b;
    __asm__ ("umulh %0, %1, %2"
             : "=r" (rhi)
             : "r" (a), "r" (b)
    );
#elif defined(HAVE_PPC_ASM)
    rlo = a * b;
    __asm__ ("mulhdu %0, %1, %2"
             : "=r" (rhi)
             : "r" (a), "r" (b)
    );
#elif defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    /*
     * We want to use AVX2 insn MULX instead of generic x86-64 MULQ
     * where it is possible.  Although on modern Intel processors MULQ
     * takes 3-cycles vs. 4 for MULX, MULX permits more freedom in
     * insn scheduling as it uses less fixed registers.
     */
    __asm__ ("mulxq %3, %1, %0"
  #if defined(__clang__)
             : "=r" (rhi), "=r" (rlo)
             : "%d" (a), "r" (b)
  #else
             : "=r" (rhi), "=r" (rlo)
             : "%d" (a), "rm" (b)
  #endif
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("mulq %3"
  #if defined(__clang__)
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), "r" (b)
  #else
             : "=d" (rhi), "=a" (rlo)
             : "%1" (a), "rm" (b)
  #endif
             : "cc"
    );
#elif defined(HAVE_INT128)
    // Maybe move this before the other x64 ASM methods?
    // Seems like it's more compiler-friendly, but it produces slower code.
    uint128_t r = (uint128_t)a * (uint128_t)b;
    rhi = (uint64_t)(r >> 64);
    rlo = (uint64_t)r;
#else
    /*
     * Implementation of 64x64->128-bit multiplication by four
     * 32x32->64 bit multiplication.
     */
    uint64_t ahi = a >> 32, bhi = b >> 32;
    uint64_t alo = (uint32_t)a, blo = (uint32_t)b;
    uint64_t tmphi   = ahi * bhi;
    uint64_t tmpmi_0 = ahi * blo;
    uint64_t tmpmi_1 = alo * bhi;
    uint64_t tmplo   = alo * blo;
    uint64_t t, carry = 0;

    t      = (tmpmi_0 << 32   ) + tmplo;
    carry += (t        < tmplo);
    rlo    = (tmpmi_1 << 32   ) + t;
    carry += (rlo      < t    );
    rhi    = (tmpmi_0 >> 32   ) + (tmpmi_1 >> 32) + tmphi + carry;
#endif
}

// 64x64->128 multiplication with no cross-lane carry [rhi:rlo ~= a * b]
static FORCE_INLINE void mult64_128_nocarry( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
    /*
     * Implementation of 64x64->128-bit multiplication by four
     * 32x32->64 bit multiplication, excluding the carry bits.  This
     * is a bit faster in the absence of a real 128-bit multiply
     * instruction, and almost as good for hashing.
     */
    uint64_t ahi = a >> 32, bhi = b >> 32;
    uint64_t alo = (uint32_t)a, blo = (uint32_t)b;
    uint64_t tmphi   = ahi * bhi;
    uint64_t tmpmi_0 = ahi * blo;
    uint64_t tmpmi_1 = alo * bhi;
    uint64_t tmplo   = alo * blo;

    rlo = tmplo + (tmpmi_0 << 32) + (tmpmi_1 << 32);
    rhi = tmphi + (tmpmi_0 >> 32) + (tmpmi_1 >> 32);
}

// 128-bit addition special case [rhi:rlo += 0:addlo]
static FORCE_INLINE void add128( uint64_t & rlo, uint64_t & rhi, uint64_t addlo ) {
#if defined(HAVE_X86_64_ASM)
    __asm__ ("addq %2, %0\n\t"
             "adcq $0, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi)
             : "r" (addlo)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi)
             : "re" (addlo)
  #else
             : "+g,r" (rlo), "+g,g" (rhi)
             : "re,m" (addlo)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rhi += (rlo < addlo);
#endif
}

// 128-bit addition [rhi:rlo += addhi:addlo]
static FORCE_INLINE void add128( uint64_t & rlo, uint64_t & rhi, uint64_t addlo, uint64_t addhi ) {
#if defined(HAVE_PPC_ASM)
    __asm__ ("addc %1, %1, %3\n\t"
             "adde %0, %0, %2"
             : "+r" (rhi), "+r" (rlo)
             : "r" (addhi), "r" (addlo)
    );
#elif defined(HAVE_X86_64_ASM)
    __asm__ ("addq %2, %0\n\t"
             "adcq %3, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi)
             : "r" (addlo), "r" (addhi)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi)
             : "re" (addlo), "re" (addhi)
  #else
             : "+g,g,r,r" (rlo), "+g,r,g,r" (rhi)
             : "re,re,m,m" (addlo), "re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rhi += (rlo < addlo);
    rhi += addhi;
#endif
}

// 192-bit addition [rhi:rmi:rlo += addhi:addmi:addlo]
static FORCE_INLINE void add192( uint64_t & rlo, uint64_t & rmi, uint64_t & rhi, const uint64_t & addlo,
        const uint64_t & addmi, const uint64_t & addhi ) {
#if defined(HAVE_X86_64_ASM)
    __asm__ ("addq %3, %0\n\t"
             "adcq %4, %1\n\t"
             "adcq %5, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "r" (addlo), "r" (addmi), "r" (addhi)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi)
             : "re" (addlo), "re" (addmi), "re" (addhi)
  #else
             : "+g,g,g,g,r,r,r,r" (rlo), "+g,g,r,r,g,g,r,r" (rmi), "+g,r,g,r,g,r,g,r" (rhi)
             : "re,re,re,re,m,m,m,m" (addlo), "re,re,m,m,re,re,m,m" (addmi), "re,m,re,m,re,m,re,m" (addhi)
  #endif
             : "cc"
    );
#else
    rlo += addlo;
    rmi += (rlo < addlo);
    rmi += addmi;
    rhi += (rmi < addmi);
    rhi += addhi;
#endif
}

// 128-bit fused multiply addition [rhi:rlo += a * b]
static FORCE_INLINE void fma64_128( uint64_t & rlo, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulxq %5, %2, %3\n\t"
             "addq %2, %0\n\t"
             "adcq %3, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "d" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "rm" (b)
  #endif
             : "cc");
#elif defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulq %5\n\t"
             "addq %%rax, %0\n\t"
             "adcq %%rdx, %1"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "a" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc");
#else
    uint64_t tmplo, tmphi;
    mult64_128(tmplo, tmphi, a, b);
    add128(rlo, rhi, tmplo, tmphi);
#endif
}

// 192-bit fused multiply addition [rhi:rmi:rlo += a * b]
static FORCE_INLINE void fma64_192( uint64_t & rlo, uint64_t & rmi, uint64_t & rhi, uint64_t a, uint64_t b ) {
#if defined(HAVE_AVX2) && defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulxq %6, %3, %4\n\t"
             "addq %3, %0\n\t"
             "adcq %4, %1\n\t"
             "adcq $0, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "d" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=r" (tmplo), "=r" (tmphi)
             : "%d" (a), "rm" (b)
  #endif
             : "cc");
#elif defined(HAVE_X86_64_ASM)
    uint64_t tmplo, tmphi;
    __asm__ ("mulq %6\n\t"
             "addq %%rax, %0\n\t"
             "adcq %%rdx, %1\n\t"
             "adcq $0, %2"
  #if defined(DEBUG)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "a" (a), "r" (b)
  #elif defined(__clang__)
             : "+r" (rlo), "+r" (rmi), "+r" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "r" (b)
  #else
             : "+g" (rlo), "+g" (rmi), "+g" (rhi), "=a" (tmplo), "=d" (tmphi)
             : "%a" (a), "rm" (b)
  #endif
             : "cc");
#else
    uint64_t tmplo, tmpmi, tmphi = 0;
    mult64_128(tmplo, tmpmi, a, b);
    add192(rlo, rmi, rhi, tmplo, tmpmi, tmphi);
#endif
}

// 128x128->128 multiplication [rhi:rlo = ahi:alo * bhi:blo]
static FORCE_INLINE void mult128_128( uint64_t & rlo, uint64_t & rhi, uint64_t alo,
        uint64_t ahi, uint64_t blo, uint64_t bhi ) {
#if defined(HAVE_INT128)
    uint128_t r = (((uint128_t)ahi) << 64) + (uint128_t)alo;
    uint128_t c = (((uint128_t)bhi) << 64) + (uint128_t)blo;
    r   = r * c;
    rhi = (uint64_t)(r >> 64);
    rlo = (uint64_t)r;
#else
    mult64_128(rlo, rhi, alo, blo);
    rhi += bhi * alo;
    rhi += blo * ahi;
#endif
}

} // namespace MathMult

/* ---- minimal stand-in for SMHasher3 Hashinfo.h / Hashlib.h registration ---- */
#include <vector>
#include <set>
#include <string>
#define FLAG_EXPAND_LIST(X) X(HASH_DONOTHING) X(HASH_MOCK) X(HASH_CRYPTOGRAPHIC) X(HASH_CRYPTOGRAPHIC_WEAK) X(HASH_CRC_BASED) X(HASH_AES_BASED) X(HASH_CLMUL_BASED) X(HASH_LOOKUP_TABLE) X(HASH_XL_SEED) X(HASH_SMALL_SEED) X(HASH_NO_SEED) X(HASH_SYSTEM_SPECIFIC) X(HASH_ENDIAN_INDEPENDENT) X(HASH_FLOATING_POINT) \
 X(IMPL_SANITY_FAILS) X(IMPL_SLOW) X(IMPL_VERY_SLOW) X(IMPL_READ_PAST_EOB) X(IMPL_TYPE_PUNNING) X(IMPL_INCREMENTAL) X(IMPL_INCREMENTAL_DIFFERENT) X(IMPL_128BIT) X(IMPL_MULTIPLY) X(IMPL_MULTIPLY_64_64) X(IMPL_MULTIPLY_64_128) X(IMPL_MULTIPLY_128_128) X(IMPL_ROTATE) X(IMPL_ROTATE_VARIABLE) X(IMPL_SHIFT_VARIABLE) X(IMPL_MODULUS) X(IMPL_ASM) X(IMPL_CANONICAL_LE) X(IMPL_CANONICAL_BE) X(IMPL_CANONICAL_BOTH) X(IMPL_SEED_WITH_HINT) X(IMPL_LICENSE_PUBLIC_DOMAIN) X(IMPL_LICENSE_BOOST) X(IMPL_LICENSE_BSD) X(IMPL_LICENSE_MIT) X(IMPL_LICENSE_APACHE2) X(IMPL_LICENSE_ZLIB) X(IMPL_LICENSE_GPL3)
#define FE1(n) FLAG_ENUM_##n,
enum { FLAG_EXPAND_LIST(FE1) FLAG_ENUM_COUNT };
#define FE2(n) static const uint64_t FLAG_##n = 1ULL << FLAG_ENUM_##n;
FLAG_EXPAND_LIST(FE2)
class HashInfo;
typedef void   (*HashFn)(const void *in, const size_t len, const seed_t seed, void *out);
typedef seed_t (*HashSeedfixFn)(const HashInfo *hinfo, const seed_t seed);
struct HashFamilyInfo { enum SrcStatus { SRC_UNKNOWN, SRC_FROZEN, SRC_STABLEISH, SRC_ACTIVE }; const char *name; const char *src_url = ""; int src_status = 0;
  HashFamilyInfo(const char *n) : name(n) {} };
struct HashInfo {
  const char *name, *family; const char *desc = ""; const char *impl = "";
  uint64_t hash_flags = 0, impl_flags = 0; uint32_t bits = 0;
  uint32_t verification_LE = 0, verification_BE = 0;
  HashFn hashfn_native = nullptr, hashfn_bswap = nullptr;
  HashSeedfixFn seedfixfn = nullptr; std::set<seed_t> badseeds; const char *badseeddesc = "";
  uint32_t sort_order = 0;
  HashInfo(const char *n, const char *f) : name(n), family(f) {}
};
static std::vector<HashInfo> &registry() { static std::vector<HashInfo> r; return r; }
static unsigned register_hash(const HashInfo *h) { registry().push_back(*h); return 0; }
static seed_t excludeBadseeds(const HashInfo *hinfo, const seed_t seed) { (void)hinfo; return seed; }
#define CONCAT_INNER(x, y) x ## y
#define CONCAT(x, y) CONCAT_INNER(x, y)
#define REGISTER_FAMILY(N, ...) static HashFamilyInfo THIS_HASH_FAMILY = []{ HashFamilyInfo $(#N); __VA_ARGS__; return $; }(); unsigned CONCAT(N,_ref)
#define REGISTER_HASH(N, ...) static HashInfo CONCAT(Hash_,N) = []{ HashInfo $(#N, THIS_HASH_FAMILY.name); __VA_ARGS__; register_hash(&$); return $; }()
static const HashInfo *findHash(const char *n) { for (auto &h : registry()) if (!strcmp(h.name, n)) return &h; return nullptr; }
/* SMHasher3 lib/Hashinfo.cpp _ComputedVerifyImpl, native endianness, SEED_FORCED (no seedfn in these files) */
static uint32_t sm3_verification(const HashInfo *hi) {
  const uint32_t hb = hi->bits / 8; std::vector<uint8_t> key(256, 0), hashes(hb * 256, 0), total(hb, 0);
  for (int i = 0; i < 256; i++) { hi->hashfn_native(key.data(), i, (seed_t)(256 - i), &hashes[i * hb]); key[i] = (uint8_t)i; }
  hi->hashfn_native(hashes.data(), hb * 256, 0, total.data());
  return (uint32_t)total[0] | ((uint32_t)total[1] << 8) | ((uint32_t)total[2] << 16) | ((uint32_t)total[3] << 24);
}
/* ===================== SMHasher3 hashes/a5hash.cpp (verbatim) ===================== */
/*
 * A5HASH
 * Copyright (C) 2021-2025  Frank J. T. Wojcik
 * Copyright (c) 2025 Aleksey Vaneev
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

//------------------------------------------------------------
#define A5HASH_VAL10 UINT64_C(0xAAAAAAAAAAAAAAAA) ///< `10` bit-pairs.
#define A5HASH_VAL01 UINT64_C(0x5555555555555555) ///< `01` bit-pairs.

template <bool bswap>
static FORCE_INLINE uint32_t a5hash_lu32( const uint8_t * const p ) {
    return GET_U32<bswap>(p, 0);
}

template <bool bswap>
static FORCE_INLINE uint64_t a5hash_lu64( const uint8_t * const p ) {
    return GET_U64<bswap>(p, 0);
}

static FORCE_INLINE void a5hash_umul64( const uint32_t u, const uint32_t v, uint32_t * const rl, uint32_t * const rh ) {
    const uint64_t r = (uint64_t)u * v;

    *rl = (uint32_t)r;
    *rh = (uint32_t)(r >> 32);
}

static FORCE_INLINE void a5hash_umul128( const uint64_t u, const uint64_t v,
        uint64_t * const rl, uint64_t * const rh ) {
    uint64_t rlo, rhi;

    MathMult::mult64_128(rlo, rhi, u, v);
    *rl = rlo;
    *rh = rhi;
}

//------------------------------------------------------------
// 64-bit hash function
template <bool bswap>
static FORCE_INLINE uint64_t a5hash( const void * const Msg0, size_t MsgLen, const uint64_t UseSeed ) {
    const uint8_t * Msg = (const uint8_t *)Msg0;

    uint64_t val01      = A5HASH_VAL01;
    uint64_t val10      = A5HASH_VAL10;

    // The seeds are initialized to mantissa bits of PI.

    uint64_t Seed1 = UINT64_C(0x243F6A8885A308D3) ^ MsgLen;
    uint64_t Seed2 = UINT64_C(0x452821E638D01377) ^ MsgLen;

    a5hash_umul128(Seed2 ^ (UseSeed & val10), Seed1 ^ (UseSeed & val01), &Seed1, &Seed2);

    if (MsgLen > 16) {
        val01 ^= Seed1;
        val10 ^= Seed2;

        do {
            a5hash_umul128(((uint64_t)a5hash_lu32<bswap>(Msg     ) << 32) ^
                                      a5hash_lu32<bswap>(Msg +  4)        ^ Seed1,
                           ((uint64_t)a5hash_lu32<bswap>(Msg +  8) << 32) ^
                                      a5hash_lu32<bswap>(Msg + 12)        ^ Seed2,
                           &Seed1, &Seed2);

            MsgLen -= 16;
            Msg    += 16;

            Seed1  += val01;
            Seed2  += val10;
        } while (MsgLen > 16);
    }

    if (MsgLen == 0) {
        goto _fin;
    }

    if (MsgLen > 3) {
        const uint8_t * Msg4;
        size_t          mo;

        Msg4   = Msg + MsgLen - 4;
        mo     = MsgLen >> 3;

        Seed1 ^= (uint64_t)a5hash_lu32<bswap>(Msg)          << 32 |
                           a5hash_lu32<bswap>(Msg4);
        Seed2 ^= (uint64_t)a5hash_lu32<bswap>(Msg + mo * 4) << 32 |
                           a5hash_lu32<bswap>(Msg4 - mo * 4);
  _fin:

        a5hash_umul128(Seed1        , Seed2, &Seed1, &Seed2);

        a5hash_umul128(Seed1 ^ val01, Seed2, &Seed1, &Seed2);

        return Seed1 ^ Seed2;
    } else {
        Seed1 ^= Msg[0];

        if (--MsgLen != 0) {
            Seed1 ^= (uint64_t)Msg[1] << 8;

            if (--MsgLen != 0) {
                Seed1 ^= (uint64_t)Msg[2] << 16;
            }
        }

        goto _fin;
    }
}

//------------------------------------------------------------
// 32-bit hash function
template <bool bswap, bool small_platform>
static FORCE_INLINE uint32_t a5hash32( const void * const Msg0, size_t MsgLen, const uint32_t UseSeed ) {
    const uint8_t * Msg = (const uint8_t *)Msg0;

    uint32_t val01      = (uint32_t)A5HASH_VAL01;
    uint32_t val10      = (uint32_t)A5HASH_VAL10;

    // The seeds are initialized to mantissa bits of PI.

    uint32_t Seed1 = 0x243F6A88 ^ (uint32_t)MsgLen;
    uint32_t Seed2 = 0x85A308D3 ^ (uint32_t)MsgLen;
    uint32_t Seed3, Seed4;
    uint32_t a, b, c, d;

    if (small_platform) {
        Seed3 = 0xFB0BD3EA;
        Seed4 = 0x0F58FD47;
    } else {
        a5hash_umul64((uint32_t)(MsgLen >> 32) ^ 0x452821E6,
                      (uint32_t)(MsgLen >> 32) ^ 0x38D01377,
                      &Seed3, &Seed4);
    }

    a5hash_umul64(Seed2 ^ (UseSeed & val10), Seed1 ^ (UseSeed & val01), &Seed1, &Seed2);

    if (MsgLen < 17) {
        if (MsgLen > 3) {
            const uint8_t * const Msg4 = Msg + MsgLen - 4;
            size_t mo;

            a =  a5hash_lu32<bswap>(Msg );
            b =  a5hash_lu32<bswap>(Msg4);

            if (MsgLen < 9) {
                goto _fin;
            }

            mo = MsgLen >> 3;

            c  = a5hash_lu32<bswap>(Msg  + mo * 4);
            d  = a5hash_lu32<bswap>(Msg4 - mo * 4);
        } else {
            a = 0;
            b = 0;

            if (MsgLen != 0) {
                a = Msg[0];

                if (MsgLen != 1) {
                    a |= (uint32_t)Msg[1] << 8;

                    if (MsgLen != 2) {
                        a |= (uint32_t)Msg[2] << 16;
                    }
                }
            }

            goto _fin;
        }
    } else {
        val01 ^= Seed1;
        val10 ^= Seed2;

        do {
            const uint32_t s1 = Seed1;
            const uint32_t s4 = Seed4;

            a5hash_umul64(a5hash_lu32<bswap>(Msg)     + Seed1, a5hash_lu32<bswap>(Msg +  4) + Seed2, &Seed1, &Seed2);

            a5hash_umul64(a5hash_lu32<bswap>(Msg + 8) + Seed3, a5hash_lu32<bswap>(Msg + 12) + Seed4, &Seed3, &Seed4);

            MsgLen -= 16;
            Msg    += 16;

            Seed1  += val01;
            Seed2  += s4;
            Seed3  += s1;
            Seed4  += val10;
        } while (MsgLen > 16);

        a = a5hash_lu32<bswap>(Msg + MsgLen -  8);
        b = a5hash_lu32<bswap>(Msg + MsgLen -  4);

        if (MsgLen < 9) {
            goto _fin;
        }

        c = a5hash_lu32<bswap>(Msg + MsgLen - 16);
        d = a5hash_lu32<bswap>(Msg + MsgLen - 12);
    }

    a5hash_umul64(c + Seed3, d + Seed4, &Seed3, &Seed4);

  _fin:
    Seed1 ^= Seed3;
    Seed2 ^= Seed4;

    a5hash_umul64(a + Seed1, b + Seed2, &Seed1, &Seed2);

    a5hash_umul64(val01 ^ Seed1, Seed2, &a, &b);

    return a ^ b;
}

//------------------------------------------------------------
// 128-bit hash function
template <bool bswap, bool truncate>
static FORCE_INLINE uint64_t a5hash128( const void * const Msg0, size_t MsgLen,
        const uint64_t UseSeed, void * const rh ) {
    const uint8_t * Msg = (const uint8_t *)Msg0;

    uint64_t val01      = A5HASH_VAL01;
    uint64_t val10      = A5HASH_VAL10;

    // The seeds are initialized to mantissa bits of PI.

    uint64_t Seed1 = UINT64_C(0x243F6A8885A308D3) ^ MsgLen;
    uint64_t Seed2 = UINT64_C(0x452821E638D01377) ^ MsgLen;
    uint64_t Seed3 = UINT64_C(0xA4093822299F31D0);
    uint64_t Seed4 = UINT64_C(0xC0AC29B7C97C50DD);
    uint64_t a, b, c, d;

    a5hash_umul128(Seed2 ^ (UseSeed & val10), Seed1 ^ (UseSeed & val01), &Seed1, &Seed2);

    if (MsgLen < 17) {
        if (MsgLen > 3) {
            const uint8_t * Msg4;
            size_t          mo;

            Msg4 = Msg + MsgLen - 4;
            mo   = MsgLen >> 3;

            a    = (uint64_t)a5hash_lu32<bswap>(Msg)           << 32 |
                             a5hash_lu32<bswap>(Msg4);
            b    = (uint64_t)a5hash_lu32<bswap>(Msg  + mo * 4) << 32 |
                             a5hash_lu32<bswap>(Msg4 - mo * 4);

  _fin16:
            a5hash_umul128(a + Seed1, b + Seed2, &Seed1, &Seed2);

            a5hash_umul128(val01 ^ Seed1, Seed2, &a, &b);

            a ^= b;

            if (!truncate) {
                a5hash_umul128(Seed1 ^ Seed3, Seed2 ^ Seed4, &Seed3, &Seed4);

                Seed3 ^= Seed4;
                memcpy(rh, &Seed3, 8);
            }

            return a;
        } else {
            a = 0;
            b = 0;

            if (MsgLen != 0) {
                a = Msg[0];

                if (--MsgLen != 0) {
                    a |= (uint64_t)Msg[1] << 8;

                    if (--MsgLen != 0) {
                        a |= (uint64_t)Msg[2] << 16;
                    }
                }
            }

            goto _fin16;
        }
    }

    if (MsgLen < 33) {
        a = (uint64_t)a5hash_lu32<bswap>(Msg)               << 32 |
                      a5hash_lu32<bswap>(Msg +  4);
        b = (uint64_t)a5hash_lu32<bswap>(Msg +  8)          << 32 |
                      a5hash_lu32<bswap>(Msg + 12);
        c = (uint64_t)a5hash_lu32<bswap>(Msg + MsgLen - 16) << 32 |
                      a5hash_lu32<bswap>(Msg + MsgLen - 12);
        d = (uint64_t)a5hash_lu32<bswap>(Msg + MsgLen -  8) << 32 |
                      a5hash_lu32<bswap>(Msg + MsgLen -  4);

  _fin_m:
        a5hash_umul128(c + Seed3, d + Seed4, &Seed3, &Seed4);

  _fin:
        Seed1 ^= Seed3;
        Seed2 ^= Seed4;

        a5hash_umul128(a + Seed1, b + Seed2, &Seed1, &Seed2);

        a5hash_umul128(val01 ^ Seed1, Seed2, &a, &b);

        a ^= b;

        if (!truncate) {
            a5hash_umul128(Seed1 ^ Seed3, Seed2 ^ Seed4, &Seed3, &Seed4);

            Seed3 ^= Seed4;
            memcpy(rh, &Seed3, 8);
        }

        return a;
    } else {
        val01 ^= Seed1;
        val10 ^= Seed2;

        if (MsgLen > 64) {
            uint64_t Seed5 = UINT64_C(0x082EFA98EC4E6C89);
            uint64_t Seed6 = UINT64_C(0x3F84D5B5B5470917);
            uint64_t Seed7 = UINT64_C(0x13198A2E03707344);
            uint64_t Seed8 = UINT64_C(0xBE5466CF34E90C6C);

            do {
                const uint64_t s1 = Seed1;
                const uint64_t s3 = Seed3;
                const uint64_t s5 = Seed5;

                a5hash_umul128(a5hash_lu64<bswap>(Msg)      + Seed1, a5hash_lu64<bswap>(
                        Msg + 32) + Seed2, &Seed1, &Seed2);

                Seed1 += val01;
                Seed2 += Seed8;

                a5hash_umul128(a5hash_lu64<bswap>(Msg +  8) + Seed3, a5hash_lu64<bswap>(
                        Msg + 40) + Seed4, &Seed3, &Seed4);

                Seed3 += s1;
                Seed4 += val10;

                a5hash_umul128(a5hash_lu64<bswap>(Msg + 16) + Seed5, a5hash_lu64<bswap>(
                        Msg + 48) + Seed6, &Seed5, &Seed6);

                a5hash_umul128(a5hash_lu64<bswap>(Msg + 24) + Seed7, a5hash_lu64<bswap>(
                        Msg + 56) + Seed8, &Seed7, &Seed8);

                MsgLen -= 64;
                Msg    += 64;

                Seed5  += s3;
                Seed6  += val10;
                Seed7  += s5;
                Seed8  += val10;
            } while (MsgLen > 64);

            Seed1 ^= Seed5;
            Seed2 ^= Seed6;
            Seed3 ^= Seed7;
            Seed4 ^= Seed8;

            if (MsgLen > 32) {
                goto _tail32;
            }
        } else {
            uint64_t s1;

  _tail32:
            s1 = Seed1;

            a5hash_umul128(a5hash_lu64<bswap>(Msg)      + Seed1, a5hash_lu64<bswap>(Msg +  8) + Seed2, &Seed1, &Seed2);

            Seed1 += val01;
            Seed2 += Seed4;

            a5hash_umul128(a5hash_lu64<bswap>(Msg + 16) + Seed3, a5hash_lu64<bswap>(Msg + 24) + Seed4, &Seed3, &Seed4);

            MsgLen -= 32;
            Msg    += 32;

            Seed3  += s1;
            Seed4  += val10;
        }

        a = a5hash_lu64<bswap>(Msg + MsgLen - 16);
        b = a5hash_lu64<bswap>(Msg + MsgLen -  8);

        if (MsgLen < 17) {
            goto _fin;
        }

        c = a5hash_lu64<bswap>(Msg + MsgLen - 32);
        d = a5hash_lu64<bswap>(Msg + MsgLen - 24);

        goto _fin_m;
    }
}

//------------------------------------------------------------
template <bool bswap>
static void a5hash_64( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint64_t hash = a5hash<bswap>(in, len, (uint64_t)seed);

    PUT_U64<bswap>(hash, (uint8_t *)out, 0);
}

template <bool bswap>
static void a5hash_32( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint32_t hash = a5hash32<bswap, true>(in, len, (uint32_t)seed);

    PUT_U32<bswap>(hash, (uint8_t *)out, 0);
}

template <bool bswap>
static void a5hash_128( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint64_t hashH;
    uint64_t hashL = a5hash128<bswap, false>(in, len, (uint64_t)seed, &hashH);

    PUT_U64<bswap>(hashL, (uint8_t *)out, 0);
    PUT_U64<bswap>(hashH, (uint8_t *)out, 8);
}

template <bool bswap>
static void a5hash_128_64( const void * in, const size_t len, const seed_t seed, void * out ) {
    uint64_t hashL = a5hash128<bswap, true>(in, len, (uint64_t)seed, NULL);

    PUT_U64<bswap>(hashL, (uint8_t *)out, 0);
}

//------------------------------------------------------------
REGISTER_FAMILY(a5hash,
   $.src_url    = "https://github.com/avaneev/a5hash",
   $.src_status = HashFamilyInfo::SRC_STABLEISH
);

REGISTER_HASH(a5hash,
   $.desc       = "a5hash v5.21, 64-bit version",
   $.hash_flags =
         FLAG_HASH_ENDIAN_INDEPENDENT,
   $.impl_flags =
         FLAG_IMPL_CANONICAL_LE      |
         FLAG_IMPL_MULTIPLY          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0xADDE79B3,
   $.verification_BE = 0x11A303D0,
   $.hashfn_native   = a5hash_64<false>,
   $.hashfn_bswap    = a5hash_64<true>
);

REGISTER_HASH(a5hash_32,
   $.desc       = "a5hash v5.21, 32-bit version",
   $.hash_flags =
         FLAG_HASH_SMALL_SEED        |
         FLAG_HASH_ENDIAN_INDEPENDENT,
   $.impl_flags =
         FLAG_IMPL_CANONICAL_LE      |
         FLAG_IMPL_MULTIPLY          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 32,
   $.verification_LE = 0xA948D11B,
   $.verification_BE = 0x9C6196A0,
   $.hashfn_native   = a5hash_32<false>,
   $.hashfn_bswap    = a5hash_32<true>
);

REGISTER_HASH(a5hash_128,
   $.desc       = "a5hash v5.21, 128-bit version",
   $.hash_flags =
         FLAG_HASH_ENDIAN_INDEPENDENT,
   $.impl_flags =
         FLAG_IMPL_CANONICAL_LE      |
         FLAG_IMPL_MULTIPLY          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 128,
   $.verification_LE = 0x89406B11,
   $.verification_BE = 0x890F41CB,
   $.hashfn_native   = a5hash_128<false>,
   $.hashfn_bswap    = a5hash_128<true>
);

REGISTER_HASH(a5hash_128__64,
   $.desc       = "a5hash v5.21, 128-bit version, 64-bit truncated (rh==NULL)",
   $.hash_flags =
         FLAG_HASH_ENDIAN_INDEPENDENT,
   $.impl_flags =
         FLAG_IMPL_CANONICAL_LE      |
         FLAG_IMPL_MULTIPLY          |
         FLAG_IMPL_LICENSE_MIT,
   $.bits = 64,
   $.verification_LE = 0x14AD402C,
   $.verification_BE = 0xA500372C,
   $.hashfn_native   = a5hash_128_64<false>,
   $.hashfn_bswap    = a5hash_128_64<true>
);
/* ===================== longA shared helpers (own code; adapted from the keyfree group) ===================== */
#include <cstdlib>
#include <cmath>
#include <functional>
#include <string>
static uint64_t sm_state;
static uint64_t splitmix64(void) { uint64_t z = (sm_state += UINT64_C(0x9e3779b97f4a7c15));
  z = (z ^ (z >> 30)) * UINT64_C(0xbf58476d1ce4e5b9); z = (z ^ (z >> 27)) * UINT64_C(0x94d049bb133111eb); return z ^ (z >> 31); }
static uint64_t xs[4];
static inline uint64_t rotl_(uint64_t x, int k) { return (x << k) | (x >> (64 - k)); }
static void rng_init(uint64_t s) { sm_state = s; for (int i = 0; i < 4; i++) xs[i] = splitmix64(); }
static inline uint64_t rng64(void) { const uint64_t r = rotl_(xs[1] * 5, 7) * 9, t = xs[1] << 17;
  xs[2] ^= xs[0]; xs[3] ^= xs[1]; xs[1] ^= xs[2]; xs[0] ^= xs[3]; xs[2] ^= t; xs[3] = rotl_(xs[3], 45); return r; }
static std::vector<uint8_t> unhex(const char *h) { std::vector<uint8_t> v; size_t n = strlen(h);
  for (size_t i = 0; i + 1 < n; i += 2) { unsigned b; sscanf(h + i, "%2x", &b); v.push_back((uint8_t)b); } return v; }
static std::string tohex(const uint8_t *p, size_t n) { std::string s; char b[3]; for (size_t i = 0; i < n; i++) { snprintf(b, 3, "%02x", p[i]); s += b; } return s; }
/* 95% Clopper-Pearson interval, closed forms for the two edge cases, bisection otherwise */
static double betainc_cdf(double x, double a, double b) { /* simple numerical integration fallback */
  const int N = 20000; double s = 0, lb = lgamma(a + b) - lgamma(a) - lgamma(b);
  for (int i = 0; i < N; i++) { double t = x * (i + 0.5) / N; s += exp(lb + (a - 1) * log(t) + (b - 1) * log1p(-t)); } return s * x / N; }
static void cp95(uint64_t k, uint64_t n, double *lo, double *hi) {
  if (k == n) { *hi = 1; *lo = pow(0.025, 1.0 / (double)n); if (k == 0) *lo = 0; return; }
  if (k == 0) { *lo = 0; *hi = 1 - pow(0.025, 1.0 / (double)n); return; }
  /* normal approximation (only used for 0<k<n, not needed for key-free rows) */
  double p = (double)k / n, se = sqrt(p * (1 - p) / n); *lo = p - 1.96 * se; *hi = p + 1.96 * se; (void)betainc_cdf; }
typedef std::function<void(const uint8_t *, size_t, uint64_t, uint64_t, uint8_t *)> HFn; /* msg,len,seedA,seedB,out */
static int g_fail = 0;
static void check_verif(const char *name, uint32_t expect) {
  const HashInfo *h = findHash(name); if (!h) { printf("MISSING %s\n", name); g_fail = 1; return; }
  uint32_t v = sm3_verification(h);
  printf("verification %-24s computed %08X expected %08X registered %08X %s\n", name, v, expect, h->verification_LE,
         (v == expect && v == h->verification_LE) ? "OK" : "MISMATCH");
  if (v != expect || v != h->verification_LE) g_fail = 1;
}
static HFn sm3fn(const char *name) { const HashInfo *h = findHash(name); HashFn f = h->hashfn_native;
  return [f](const uint8_t *m, size_t n, uint64_t s, uint64_t, uint8_t *o) { f(m, n, (seed_t)s, o); }; }
/* seed models: 64 = uniform 64-bit, 32 = uniform 32-bit zero-extended, 128 = two independent 64-bit seeds */
static uint64_t run_pair(const char *label, HFn f, unsigned outbytes, int seedbits, const char *mh, const char *mph,
                         unsigned logN, bool control, int cidx = -1) {
  std::vector<uint8_t> a = unhex(mh), b = unhex(mph);
  if (control) { if (cidx < 0) b.back() ^= 0x01; else b[cidx] ^= 0x01; }
  uint64_t N = 1ULL << logN, hits = 0, exs = 0, exs2 = 0; bool have = false; uint8_t oa[64], ob[64], ea[64] = {0};
  for (uint64_t t = 0; t < N; t++) {
    uint64_t s1 = rng64(), s2 = seedbits == 128 ? rng64() : 0; if (seedbits == 32) s1 &= 0xffffffffULL;
    f(a.data(), a.size(), s1, s2, oa); f(b.data(), b.size(), s1, s2, ob);
    if (!memcmp(oa, ob, outbytes)) { hits++; if (!have) { have = true; exs = s1; exs2 = s2; memcpy(ea, oa, outbytes); } }
  }
  double lo, hi; cp95(hits, N, &lo, &hi);
  printf("%-34s %s seed%-3d |m|=%zu |m'|=%zu L=%zu  %llu/%llu  rate=%.6f  95%%CI[%.8f,%.8f]",
         label, control ? "CONTROL" : "PAIR   ", seedbits, a.size(), b.size(), (std::max(a.size(), b.size()) + 7) / 8,
         (unsigned long long)hits, (unsigned long long)N, (double)hits / N, lo, hi);
  if (have) { printf("  ex seed=%016llx", (unsigned long long)exs); if (seedbits == 128) printf(",%016llx", (unsigned long long)exs2);
    printf(" out=%s", tohex(ea, outbytes).c_str()); }
  printf("\n"); fflush(stdout);
  return hits;
}
/* key-free expectation: all N collide; control: none */
static void expect_keyfree(const char *label, HFn f, unsigned ob, int sb, const char *m, const char *mp, unsigned logN, int cidx = -1) {
  uint64_t h = run_pair(label, f, ob, sb, m, mp, logN, false);
  if (h != (1ULL << logN)) { printf("  !! not every seed\n"); g_fail = 1; }
  uint64_t c = run_pair(label, f, ob, sb, m, mp, logN > 16 ? 16 : logN, true, cidx);
  if (c != 0) { printf("  !! control collided\n"); }
}
/* ---- multicollision set checker: every member must equal member 0 on the full output ---- */
#include <algorithm>
#include <unordered_set>
static uint64_t check_family(const char *label, HFn f, unsigned outbytes, int seedbits,
                             const std::vector<std::vector<uint8_t>> &S, unsigned logK) {
  { std::vector<std::vector<uint8_t>> T = S; std::sort(T.begin(), T.end());
    size_t d = std::unique(T.begin(), T.end()) - T.begin();
    size_t mx = 0; for (auto &m : S) mx = std::max(mx, m.size());
    printf("%s: family of %zu messages, %zu distinct, max length %zu bytes (L=%zu)\n", label, S.size(), d, mx, (mx + 7) / 8);
    if (d != S.size()) { printf("  !! duplicate members\n"); g_fail = 1; } }
  uint64_t K = 1ULL << logK, all = 0, lo16 = 0; uint8_t o0[64], o[64]; uint64_t ex = 0; bool have = false; uint8_t eo[64];
  size_t minlargest = S.size();
  for (uint64_t t = 0; t < K; t++) {
    uint64_t s1 = rng64(), s2 = seedbits == 128 ? rng64() : 0; if (seedbits == 32) s1 &= 0xffffffffULL;
    f(S[0].data(), S[0].size(), s1, s2, o0); size_t same = 1, same16 = 1;
    for (size_t i = 1; i < S.size(); i++) { f(S[i].data(), S[i].size(), s1, s2, o);
      if (!memcmp(o, o0, outbytes)) same++; if (!memcmp(o, o0, 2)) same16++; }
    if (same == S.size()) { all++; if (!have) { have = true; ex = s1; memcpy(eo, o0, outbytes); } }
    if (same16 == S.size()) lo16++;
    minlargest = std::min(minlargest, same);
  }
  double lo, hi; cp95(all, K, &lo, &hi);
  printf("  keys where ALL %zu members share the full %u-bit output: %llu/%llu (95%%CI [%.6f,1]); low-16-bit agreement %llu/%llu; min members sharing member 0's value over keys: %zu\n",
         S.size(), outbytes * 8, (unsigned long long)all, (unsigned long long)K, lo, (unsigned long long)lo16, (unsigned long long)K, minlargest);
  if (have) printf("  example key %016llx -> common output %s\n", (unsigned long long)ex, tohex(eo, outbytes).c_str());
  for (int i = 0; i < 3 && i < (int)S.size(); i++) printf("  member[%d] = %s\n", i, tohex(S[i].data(), S[i].size()).c_str());
  printf("  member[%zu] = %s\n", S.size() - 1, tohex(S.back().data(), S.back().size()).c_str());
  if (all != K) g_fail = 1;
  fflush(stdout); return all;
}
/* ===================== longA driver (own code) ===================== */
/* a5hash-128 v5.x (SMHasher3 a5hash_128), inputs > 64 bytes.  Loop (64-byte blocks, words m0..m7):
 *   (S1,S2) = (m0+S1)(m32+S2);  (S3,S4) = (m8+S3)(m40+S4);  (S5,S6) = (m16+S5)(m48+S6);  (S7,S8) = (m24+S7)(m56+S8)
 *   then S1 += val01, S2 += S8old, S3 += S1old, S4 += val10, S5 += S3old, S6 += val10, S7 += S5old, S8 += val10.
 * Only (S1,S2) and val01/val10 carry the seed at the start; S3..S8 start as public constants and the S5 and S7
 * chains stay public for one and two more blocks.  Setting the first factor of a public product to zero makes the
 * product (0,0) whatever the second word is.  Zeroing words (constants):
 *   block 0: m8 = -Seed3, m16 = -Seed5, m24 = -Seed7;  block 1: m16 = -Seed3, m24 = -Seed5;  block 2: m24 = -Seed3
 * frees m40, m48, m56 of block 0, m48, m56 of block 1 and m56 of block 2 (six words, 2^384 messages, one state),
 * for any content after byte 192 and any length >= 224 (block 0 alone: any length >= 96; the tail re-reads the last 32 bytes).
 * Usage: ./a5_long [log2 seeds] [rng seed] */
static const uint64_t C3 = UINT64_C(0xA4093822299F31D0), C5 = UINT64_C(0x082EFA98EC4E6C89), C7 = UINT64_C(0x13198A2E03707344);
static uint64_t ld64le(const uint8_t *p) { uint64_t v = 0; for (int i = 7; i >= 0; i--) v = (v << 8) | p[i]; return v; }
static void st64le(uint8_t *p, uint64_t v) { for (int i = 0; i < 8; i++) p[i] = (uint8_t)(v >> (8 * i)); }
static void zero_words(uint8_t *m, int blocks) {
  st64le(m + 8, (uint64_t)0 - C3); st64le(m + 16, (uint64_t)0 - C5); st64le(m + 24, (uint64_t)0 - C7);
  if (blocks > 1) { st64le(m + 64 + 16, (uint64_t)0 - C3); st64le(m + 64 + 24, (uint64_t)0 - C5); }
  if (blocks > 2) st64le(m + 128 + 24, (uint64_t)0 - C3);
}
static const size_t FREE[6] = { 40, 48, 56, 64 + 48, 64 + 56, 128 + 56 };
int main(int argc, char **argv) {
  unsigned logN = argc > 1 ? atoi(argv[1]) : 12; rng_init(argc > 2 ? strtoull(argv[2], 0, 0) : UINT64_C(0x4c6f6e6745));
  check_verif("a5hash_128", 0x89406B11); check_verif("a5hash_128__64", 0x14AD402C); if (g_fail) return 1;
  HFn f = sm3fn("a5hash_128");
  const size_t lens[6] = { 96, 224, 256, 1024, 65536, 1048576 };  /* free words must lie before the last 32 bytes (read again by the tail) */
  for (int li = 0; li < 6; li++) {
    size_t n = lens[li]; int blocks = n >= 224 ? 3 : 1, nfree = blocks == 3 ? 6 : 3;
    std::vector<uint8_t> A(n); for (auto &x : A) x = (uint8_t)rng64(); zero_words(A.data(), blocks);
    std::vector<uint8_t> B = A; for (int k = 0; k < nfree; k++) st64le(&B[FREE[k]], rng64());
    uint64_t N = UINT64_C(1) << (n > 100000 ? (logN > 8 ? 8 : logN) : logN), hit = 0, ex = 0; uint8_t oa[16], ob[16], eo[16];
    for (uint64_t t = 0; t < N; t++) { uint64_t sd = rng64(); f(A.data(), n, sd, 0, oa); f(B.data(), n, sd, 0, ob); if (!memcmp(oa, ob, 16)) { if (!hit) { ex = sd; memcpy(eo, oa, 16); } hit++; } }
    std::vector<uint8_t> Cc = B; Cc[8] ^= 1; uint64_t ctl = 0; for (int t = 0; t < 256; t++) { uint64_t sd = rng64(); f(A.data(), n, sd, 0, oa); f(Cc.data(), n, sd, 0, ob); ctl += !memcmp(oa, ob, 16); }
    printf("len %8zu (L=%6zu): %d zeroed products, %d free words differ; full 128-bit collisions %llu/%llu; control (zeroing word broken) %llu/256",
           n, (n + 7) / 8, blocks == 3 ? 6 : 3, nfree, (unsigned long long)hit, (unsigned long long)N, (unsigned long long)ctl);
    if (hit) printf("  e.g. seed %016llx -> %s", (unsigned long long)ex, tohex(eo, 16).c_str());
    printf("\n"); if (n <= 256) printf("  m  = %s\n  m' = %s\n", tohex(A.data(), n).c_str(), tohex(B.data(), n).c_str());
    if (hit != N) g_fail = 1;
  }
  { size_t n = 1000; std::vector<uint8_t> A(n); for (auto &x : A) x = (uint8_t)rng64(); zero_words(A.data(), 3);
    std::vector<std::vector<uint8_t>> F; for (uint32_t i = 0; i < 65536; i++) { std::vector<uint8_t> B = A; st64le(&B[FREE[5]], i); st64le(&B[FREE[0]], (uint64_t)i * UINT64_C(0x9E3779B97F4A7C15)); F.push_back(B); }
    check_family("a5hash-128 1000-byte prefix-zeroing family", f, 16, 64, F, logN > 10 ? 10 : logN); }
  printf(g_fail ? "RESULT: FAIL\n" : "RESULT: PASS\n"); return g_fail;
}
